spaceandtimefdn/sxt-proof-of-sql

crates/proof-of-sql/src/base/database/column.rs, crates/proof-of-sql/src/base/math/decimal.rs, crates/proof-of-sql/src/sql/ast/mod.rs, crates/proof-of-sql/src/sql/ast/multiply_expr.rs, crates/proof-of-sql/src/sql/ast/multiply_expr_test.rs, crates/proof-of-sql/src/sql/ast/numerical_util.rs, crates/proof-of-sql/src/sql/ast/provable_expr_plan.rs, crates/proof-of-sql/src/sql/ast/test_utility.rs, crates/proof-of-sql/src/sql/parse/provable_expr_plan_builder.rs, crates/proof-of-sql/src/sql/parse/query_context_builder.rs, crates/proof-of-sql/src/sql/parse/query_expr_tests.rs, crates/proof-of-sql/tests/integration_tests.rs
We need to add support for arithmetic. Now let's continue with `*`.
- Add support for `*` in `proof-of-sql` crate
Yes.
=> feat!: add `MultiplyExpr`

crates/proof-of-sql/benches/scaffold/querys.rs
We need to add new some benches now that we have more features.
Add a new bench query
N/A
=> feat: add arithmetic to benches

crates/proof-of-sql/src/sql/ast/add_subtract_expr.rs, crates/proof-of-sql/src/sql/ast/multiply_expr.rs
I forgot to change names for a few structs in tracing
Fix names in a few places
N/A
=> fix: fix names in tracing

crates/proof-of-sql/README.md, docs/SQLSyntaxSpecification.md
We need to update our docs as we introduce new features. 
- add timestamp to SQL spec
- add numerical operations & new datatypes to supported SQL syntax
N/A
=> docs: update docs up to 0.5.9 features

crates/proof-of-sql-parser/Cargo.toml, crates/proof-of-sql-parser/src/intermediate_ast_tests.rs, crates/proof-of-sql-parser/src/lib.rs, crates/proof-of-sql-parser/src/utility.rs
This PR exists to address non-blocking issues mentioned in #59 without blocking #56. 
- remove `parser-test-utility` feature
- rename `proof-of-sql-parser/src/test_utility.rs` to `utility.rs`
- improve docs for the file above
=> refactor: make intermediate AST utility available without a feature flag

Cargo.toml, crates/proof-of-sql/examples/posql_db/csv_accessor.rs
Our current version of arrow is quite old (version v45). Attempts to update this in the past have been somewhat thwarted by dependent projects depending on an older version of arrow and being stuck to it due to some complicated dependency management. This is now being resolved, and an arrow upgrade to proof-of-sql is required to resolve it.
- arrow dependency upgraded to 51
- deprecation warnings addressed
These changes do not affect existing functionality which is verified by existing tests.
=> build: upgrade to arrow 51

crates/proof-of-sql/src/base/database/column_operation.rs
This PR is split out from #81 and handles comparison operators.
- add = <= and >= to `column_operation.rs`
- remove unnecessary `Copy` and add comments to the file above
Yes
=> feat: add `=`, `<=` and `>=` to `column_operation.rs`

crates/proof-of-sql/src/sql/postprocessing/order_by_expr.rs, crates/proof-of-sql/src/sql/postprocessing/order_by_expr_test.rs, crates/proof-of-sql/src/sql/postprocessing/owned_table_postprocessing.rs, crates/proof-of-sql/src/sql/postprocessing/slice_expr.rs, crates/proof-of-sql/src/sql/postprocessing/test_utility.rs
Remove unnecessary generics from `postprocessing`
- remove `S: Scalar` where it is unnecessary
Existing tests do pass
=> refactor!: remove unnecessary generics from `postprocessing`

crates/proof-of-sql/src/base/database/column_operation.rs, crates/proof-of-sql/src/base/database/column_operation_error.rs, crates/proof-of-sql/src/base/database/owned_column_operation.rs
This PR is split out from #81 and continues #85.
- add `NOT`, `AND` and `OR` to `column_operation.rs`
- add comparison operations to `OwnedColumn`
Yes
=> feat: add logical operations && comparison operations to `OwnedColumn`

crates/proof-of-sql-parser/src/utility.rs, crates/proof-of-sql/src/base/database/owned_table.rs, crates/proof-of-sql/src/sql/postprocessing/error.rs, crates/proof-of-sql/src/sql/postprocessing/mod.rs, crates/proof-of-sql/src/sql/postprocessing/owned_table_postprocessing.rs, crates/proof-of-sql/src/sql/postprocessing/select_expr.rs, crates/proof-of-sql/src/sql/postprocessing/select_expr_test.rs, crates/proof-of-sql/src/sql/postprocessing/test_utility.rs
This is the last PR split out of #48. Please review #87 and then #81 first or look at the third commit.
- add `SelectExpr`
Yes
=> feat: add `SelectExpr`

crates/proof-of-sql/src/base/database/column.rs, crates/proof-of-sql/src/base/database/owned_column.rs
In order not to repeat code for `Column` and `OwnedColumn` we need to add conversion between the two.
Add conversion mechanism between `Column` and `OwnedColumn`
Yes
=> feat: add conversion mechanism between `Column` and `OwnedColumn`

crates/proof-of-sql-parser/src/intermediate_ast.rs, crates/proof-of-sql-parser/src/intermediate_decimal.rs, crates/proof-of-sql-parser/src/posql_time/timestamp.rs, crates/proof-of-sql-parser/src/utility.rs, crates/proof-of-sql/src/sql/postprocessing/error.rs, crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs, crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing_test.rs, crates/proof-of-sql/src/sql/postprocessing/mod.rs
This is the first PR split out of #86.
- add `GroupByPostprocessing`
- improve `proof_of_sql_parser::utility`
Yes
=> feat: add `postprocessing::GroupByPostprocessing`

crates/proof-of-sql/src/base/database/group_by_util.rs, crates/proof-of-sql/src/base/database/owned_column_error.rs, crates/proof-of-sql/src/sql/postprocessing/error.rs, crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs, crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing_test.rs, crates/proof-of-sql/src/sql/postprocessing/owned_table_postprocessing.rs, crates/proof-of-sql/src/sql/postprocessing/test_utility.rs
Please review #94 before reviewing #86 or alternatively check out the second commit.
Add `GroupByPostprocessing`
Yes
=> feat: impl `OwnedTablePostprocessingStep` for `GroupByPostprocessing`

crates/proof-of-sql/src/sql/proof/mod.rs
Fix visibility so that I can use the proof-of-sql crate as a library for my Wasm verifier.
=> fix: fix visibility for usage outside of the crate

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/generic-issue.md
We should have templates to facilitate issue creation
A Feature, Bug, and Generic issue template are added.
NA
=> chore: update issue templates

.github/workflows/lint-and-test.yml, crates/proof-of-sql/Cargo.toml, crates/proof-of-sql/examples/tech_gadget_prices/main.rs, crates/proof-of-sql/examples/tech_gadget_prices/tech_gadget_prices.csv
This PR includes an example of ``tech_gadget_prices`` for Proof of SQL
- A  CSV file with the ``tech_gadget_prices`` in the form of lists with their prices .
- Test script changes required for running the new example
-  Proof of SQL Query related changes for the ``tech_gadget_prices`` example
=> Feat/tech gadget prices Example for Proof of SQL

crates/proof-of-sql/src/base/database/slice_operation.rs
In order to have generic operations on `ColumnarValue` it is necessary to have slice-literal operations.
- add slice-literal operations.
N/A
=> feat: add slice-literal operations

crates/proof-of-sql/src/sql/proof_plans/table_exec.rs
We copied the code from `ProjectionExec` to `TableExec` and make the latter a special case of the former. This is wrong. There is no need to commit any column in `TableExec` since we already grab all the columns in `QueryProof`.
- Not commit columns in `TableExec`.
- Make it clear that we don't have to select all cols. Following conventions in `DataFusion` [TableScan](https://docs.rs/datafusion/latest/datafusion/logical_expr/struct.TableScan.html) in logical planning and [FileScanConfig] in physical planning we can refuse to read columns we don't care about.
=> fix: not commit columns in `TableExec`

crates/proof-of-sql/src/base/slice_ops/add_const.rs, crates/proof-of-sql/src/base/slice_ops/add_const_test.rs, crates/proof-of-sql/src/base/slice_ops/mod.rs, crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- Upstream PRs have been reviewed and merged:
Recently @JayWhite2357 found a vulnerability in our `ProofPlan`s with nontrivial proofs related to range length. Now we are implementing a fix.
- add `range_length_one_evaluation` to `SumcheckMleEvaluations`
- add `range_length` to `FinalRoundBuilder`
- fix the bug in the filter proof.
=> fix: fix filter vulnerability

crates/proof-of-sql/src/base/math/permutation.rs, crates/proof-of-sql/src/sql/postprocessing/order_by_postprocessing.rs, crates/proof-of-sql/src/sql/proof_exprs/comparison_util.rs
Some of our functions are named `unchecked_`.
See commits.
By existing tests.
=> refactor: update functions named `unchecked_`

crates/proof-of-sql/src/sql/proof_gadgets/range_check.rs, crates/proof-of-sql/src/sql/proof_gadgets/range_check_test.rs
Currently, the range check word decomposition is handled entirely in the ```FinalRound```. It is necessary to move this step into the ```FirstRound``` so that it is not possible for any prover to gain a malicious advantage by performing a decomposition while the  challenge alpha is known. Since alpha can only be provided in the ```FinalRound```, moving word decomposition and commitment into the first round effectively erases any possibility that the prover could cheat by gaining knowledge of the verifier challenge in advance.
Existing testing framework is successfully updated
=> refactor: move range check word decomposition to first round builder

crates/proof-of-sql/README.md
=> docs: update README.md

Cargo.toml, crates/proof-of-sql/Cargo.toml, crates/proof-of-sql/src/proof_primitive/hyperkzg.rs, crates/proof-of-sql/src/proof_primitive/mod.rs, crates/proof-of-sql/tests/integration_tests.rs
This PR adds support for the hyperkzg commitment scheme.
This implementation if fairly naive, simply wrapping the implementation in nova. We can make performance improvements later.
Yes
=> feat: add hyperkzg commitment scheme

crates/proof-of-sql/README.md
Fix the typo, the pre word is error, I haved fixed it. 
only fix the typo
no need to test, only fix the typo
=> fix: typo-fix

solidity/scripts/README.md
add a period at the end of sentence .
add a period at the end of sentence .
this pr not relate the code logic.
=> docs: add period at ```README.md```

.github/workflows/lint-and-test.yml, .gitignore, solidity/foundry.toml, solidity/scripts/doc_gen.sh, solidity/scripts/lint-and-test.sh, solidity/slither.config.json, solidity/src/base/ECPrecompiles.pre.sol, solidity/src/base/LagrangeBasisEvaluation.sol, solidity/src/base/MathUtil.sol, solidity/src/base/Transcript.sol, solidity/test/base/ECPrecompiles.t.pre.sol, solidity/test/base/LagrangeBasisEvaluation.t.sol, solidity/test/base/MathUtil.t.sol, solidity/test/base/Transcript.t.sol
This PR does a bit of tidying and cleanup for the existing Solidity code.
* slither is added to the CI
* a doc generation script is added that supports MathJax
* a naming convention is made consistent across the files
Yes
=> chore: improve solidity tooling

.github/workflows/lint-and-test.yml, solidity/scripts/lint-and-test.sh, solidity/test/base/Constants.t.sol
The PR simplifies tests and improves CI
See individual commits.
Yes
=> chore(sol): simplify tests and add `forge fmt` to CI.

crates/proof-of-sql/src/base/database/column.rs, crates/proof-of-sql/src/base/database/column_type_operation.rs, crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
These are some utility functions that will be used by the div and mod gadget.
- sqrt_min_negative function
- try_divide_modulo_column_types
- redefining the return type of modulo
Yes
=> feat: utilities for div mod gadget

crates/proof-of-sql-planner/src/plan.rs, crates/proof-of-sql-planner/tests/e2e_tests.rs
Even though bare `LogicalPlan::Aggregate` doesn't show up among currently supported SQL since that's for cases where there is no aliasing it is crucial for queries such as `select a, b, count(1), sum(c) + sum(d) from tab group by c, d`
- allow bare `Aggregate` in `LogicalPlan`
- fix the bug that if `Aggregate` has aliases things didn't work (mostly for things such as `sum(2 * decimal_column)` which does induces aliasing in the optimized logical plan)
- make (irrelevant) `alias_map` in tests more correct
Yes.
=> feat: allow bare `Aggregate` in `LogicalPlan` in the planner as well as allow aliasing for expressions within `Aggregate`

crates/proof-of-sql-planner/src/expr.rs
This PR completes the addition of `CastExpr` by adding it to the planner
New supported arm for `expr_to_proof_expr` for Cast.
Yes
=> feat: add cast expr to planner

crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
=> feat: scale cast column

crates/proof-of-sql-planner/src/expr.rs
We want to allow queries such as `select $1::bigint` without having to support untyped placeholders in PoSQL.
Support `Expr` such as `CAST($1 AS BIGINT)` or `$1::bigint` for untyped placeholders.
Yes.
=> feat: allow cast-placeholder pattern in the planner

crates/proof-of-sql/src/base/mod.rs
We need to be able to use `PlaceholderError` outside the crate `proof-of-sql` hence we need it pub
See title
Yes.
=> fix: make `PlaceholderError` and `PlaceholderResult` pub

crates/proof-of-sql-planner/src/conversion.rs, crates/proof-of-sql-planner/tests/e2e_tests.rs
We need to make sure our latest feature, parameterized queries, can actually work. However datafusion 38.0.0 optimizer unlike the datafusion 46.0.1 one, errors out on any query including `$1::varchar` or any other explicitly typed placeholder. We need to disable the optimizer rule so that queries can run.
- disable datafusion optimizer rule, `common_sub_expression_eliminate`
- add explicitly typed placeholders to `e2e_tests.rs`
Yes.
=> fix: disable one datafusion optimizer rule, `common_sub_expression_eliminate`

crates/proof-of-sql/benches/jaeger/bin/jaeger_benches.rs
A number of improvements were added that originated from suggestions made in PR #668. Additional parameters to make the tests repeatable and improve speed were added along with document improvements.
- A parameter is added to represent `max_nu` in the Dynamic Dory setup and `sigma` in the Dory setup.
- The file loading for Dynamic Dory is refactored to be used by both Dynamic Dory and Dory setups.
- An optional random seed is added as a cli argument to help with reproducible benches.
Yes
=> bench: add parameters for Dory setup and random seed to Jaeger benchmarks

crates/proof-of-sql/src/sql/proof_exprs/comparison_util.rs, crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
We are simplifying numerical binary ops hence we don't need unused code that will never be used. In this PR we basically undo #331.
- remove unused code in `numerical_util.rs`
Yes.
=> fix: remove unused code in `comparison_util.rs` and `numerical_util.rs`

crates/proof-of-sql-planner/Cargo.toml
We haven't been publishing `proof-of-sql-planner` which we do need to be doing from now on since we need to use it.
Publish `proof-of-sql-planner`
N/A
=> ci: publish `proof-of-sql-planner`

crates/proof-of-sql-planner/src/conversion.rs, crates/proof-of-sql-planner/tests/e2e_tests.rs
In order to avoid parsing twice, we want the planner to use a parsed statement, rather than raw sql, to produce the `DynProofPlan`.
Modifying `conversion` functions to use `Statement`s rather than raw sql.
Yes
=> refactor: receive parsed statement in planner rather than raw sql

crates/proof-of-sql-planner/src/context.rs, crates/proof-of-sql-planner/src/conversion.rs, crates/proof-of-sql-planner/tests/e2e_tests.rs
The use of the `ContextProvider` in the public planner functions is redundant with the `SchemaAccessor`. Therefore, we may remove it from these functions.
Removing the `ContextProvider` from the planner public functions.
Yes
=> refactor!: remove context provider from public planner functions

.github/workflows/release.yaml, ci/publish.sh, crates/proof-of-sql-planner/Cargo.toml
`proof-of-sql` and `proof-of-sql-parser` 0.94.0 have already been released. Hence we made a few changes.
- check for existence of crate before publishing in CI
- add description to `proof-of-sql-planner` crate enabling its publishing
Yes.
=>  fix!: add `proof-of-sql-planner` description && check for existing published crate before publishing

crates/proof-of-sql/src/proof_primitive/hyperkzg/commitment.rs
Commitment computation for hyperkzg in the cpu is not parallelized with the rayon feature enabled like dynamic dory is. This change enables this parallelization for all of the relevant iterators in the hyperkzg cpu commitment code.
- parallelization is enabled for hyperkzg cpu commitment computation iterators if rayon is enabled
These changes do not affect existing business logic, which should be verified by existing tests.
=> feat: parallelize iterators in hyperkzg cpu commitments

LICENSE
Space and Time Labs, Inc. is now MakeInfinite Labs, Inc., as announced [here](https://www.spaceandtime.io/blog/introducing-the-space-and-time-foundation).
Update to the LICENSE file
N/A
=> chore: update LICENSE file

crates/proof-of-sql/src/base/database/join_util.rs
Currently the `join_util` finds multiplicities by taking every unique row and scanning for matches over the entire data table which takes `O(mn)` time. This PR updates the algorithm to do a sorted row multiplicity finder. Sorted indices for the `unique` and `data` tables are found and we only require one pass though the data table to find the multiplicity. The updated algorithm has a time complexity of `O(m log m + n long n)` time.
Benchmarks confirm the improvement. For a table size of `10,000`, a single call to get multiplicities can take over `1.5` seconds. 
This new algorithm can do the work in under `3` ms, a `~670x` speed up.
- The `join_util::get_multiplicities` function is optimized with a sorted row multiplicity finder algorithm.
- A tracing span is added for benchmarks.
Yes, …
=> perf: optimize finding multiplicities in join util

crates/proof-of-sql/src/sql/proof_gadgets/range_check.rs
The private function `count_word_occurences` does not need to take a mutable reference to the word count collection. Instead, it should initialize that collection itself, and return it.
Changing the signature of `count_word_occurences` so that it does not contain a mutable reference.
Yes
=> refactor: simplify counting in range check

crates/proof-of-sql/src/sql/proof_gadgets/range_check.rs
The function `get_logarithmic_derivative` has a mutable reference.
Removing the mutable reference
Yes
=> refactor: get_logarithmic_derivative

crates/proof-of-sql/src/sql/proof_gadgets/range_check.rs
There are several variables in range check that could use better names.
Mostly renames of existing variables in range check
Yes
=> refactor: rename variables in range check

crates/proof-of-sql-planner/tests/e2e_tests.rs
This is a test to verify that implicit casting is handled properly by the planner.
A single end to end test
Yes
=> test: implicit casting in planner

crates/proof-of-sql/src/sql/proof_gadgets/range_check.rs
This is a relatively simple starting test for range check.
One new range check test
Yes
=> test: add simple range check test

crates/proof-of-sql/src/base/commitment/committable_column.rs
Conversion from the `Scalar` column type to a `CommitableCoumn` type in the `committable_columns` module offers an opportunity for parallelism. This PR adds the `if_rayon` macro to the `from` `impl` for the `Scalar` column type.
Benchmarks for the `Filter` query indicates a `2.14x` performance increase in `EqualsExpr::final_round_evaluate`. A `1.07x` performance increase overall.
Before, `EqualsExpr::final_round_evaluate` was `104.15ms`.
After,  `EqualsExpr::final_round_evaluate` is `48.57ms`.
To reproduce these benchmarks: `cargo run --release --bin proof-of-sql-benches -- -s hyper-kzg -q filter`.
- The `from` `impl` for the `Scalar` column type now uses the `if_rayon` macro
Yes
=> perf: add if_rayon macro to the Scalar to CommittableColumn type conversion

crates/proof-of-sql/src/sql/proof/final_round_builder.rs
There is a performance improvement opportunity in the  `final_round_builder` module by adding parallelism to the `evaluate_pcs_proof_mles`  method. This PR reworks the method to use the `if_rayon` macro.
This change improves the performance of `FilterExec::first_round_evaluate`, `FilterExec::final_round_evaluate`, `FirstRoundBuilder::evaluate_pcs_proof_mles`, and `FinalRoundBuilder::evaluate_pcs_proof_mles`. The overall performance improvement for the proof generation time improved by `~40ms`.
Before
After
- `if_rayon` macro is added to the `evaluate_pcs_proof_mles` method in the `final_round_builder` module
Yes
=> perf: add `if_rayon` macro to `evaluate_pcs_proof_mles` in the `final_round_builder` module

crates/proof-of-sql/src/sql/evm_proof_plan/plans.rs
The solidity table exec code will require the column numbers.
Adding column numbers to the `EVMTableExec`.
Yes
=> feat: add column numbers to `EVMTableExec`

crates/proof-of-sql/src/sql/proof_plans/fold_util.rs
In `fold_util.rs` the docs are wrong and I'm now describing the code correctly.
=> docs: correct docs in `fold_util.rs`

crates/proof-of-sql/src/sql/proof_plans/sort_merge_join_exec.rs
There is duplicate logic in sort merge join
New private function to deduplicate logic.
Yes.
=> refactor: simplify sort merge join

solidity/src/base/Constants.sol, solidity/src/base/Errors.sol, solidity/src/base/Queue.pre.sol, solidity/src/builder/VerificationBuilder.pre.sol, solidity/src/proof_gadgets/SignExpr.pre.sol, solidity/test/base/Constants.t.sol, solidity/test/base/Queue.t.pre.sol, solidity/test/builder/VerificationBuilder.t.pre.sol, solidity/test/proof_gadgets/SignExpr.t.pre.sol
We need sign_expr for group by
New sign_expr in solidity.
Yes
=> feat(sol): sign gadget

crates/proof-of-sql/src/proof_primitive/dory/blitzar_metadata_table.rs, crates/proof-of-sql/src/proof_primitive/dory/dory_vmv_helper.rs, crates/proof-of-sql/src/proof_primitive/dory/pack_scalars.rs, crates/proof-of-sql/src/proof_primitive/sumcheck/prover_round.rs, crates/proof-of-sql/src/proof_primitive/sumcheck/prover_state.rs, crates/proof-of-sql/src/sql/proof/query_proof.rs, crates/proof-of-sql/src/sql/proof_exprs/and_expr.rs, crates/proof-of-sql/src/sql/proof_exprs/or_expr.rs, crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs, crates/proof-of-sql/src/sql/proof_plans/sort_merge_join_exec.rs
Clippy is failing
Fixing clippy 
No real functional change
=> chore: fix clippy

crates/proof-of-sql-planner/tests/e2e_tests.rs
We should have at least one proper union test in our e2e tests.
New union test
Yes
=> test: add union all test

docs/SQLSyntaxSpecification.md
=> docs: update SQL spec

solidity/src/base/Array.pre.sol, solidity/test/base/Array.t.pre.sol
We need for the solidity builder to store both the length and the evaluations of our chi columns. So we want to be able to read the chi lengths from the proof, leaving room for the evaluations.
New function `read_uint64_array_as_wordx2_array` for reading uint64 as two words.
Yes
=> feat(sol): add `read_uint64_array_as_uint512_array`

crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
=> refactor: inline `prove_group_by` and `verify_group_by`

crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
=> fix: check chi lengths in slice

solidity/test/base/Array.t.pre.sol, solidity/test/base/Queue.t.pre.sol
We want 100% test coverage on all lines and branches.
Covering two branches that are missing from test coverage.
Yes
=> test(sol): cover uncovered branches

crates/proof-of-sql-planner/tests/evm_tests.rs, crates/proof-of-sql/src/sql/evm_proof_plan/error.rs, crates/proof-of-sql/src/sql/evm_proof_plan/exprs.rs, crates/proof-of-sql/src/sql/proof_exprs/scaling_cast_expr.rs, solidity/src/base/Constants.sol, solidity/src/proof_exprs/AddExpr.pre.sol, solidity/src/proof_exprs/AndExpr.pre.sol, solidity/src/proof_exprs/CastExpr.pre.sol, solidity/src/proof_exprs/EqualsExpr.pre.sol, solidity/src/proof_exprs/InequalityExpr.pre.sol, solidity/src/proof_exprs/MultiplyExpr.pre.sol, solidity/src/proof_exprs/NotExpr.pre.sol, solidity/src/proof_exprs/OrExpr.pre.sol, solidity/src/proof_exprs/ProofExpr.pre.sol, solidity/src/proof_exprs/ScalingCastExpr.pre.sol, solidity/src/proof_gadgets/FoldUtil.pre.sol, solidity/src/proof_plans/FilterExec.pre.sol, solidity/src/proof_plans/GroupByExec.pre.sol, solidity/src/proof_plans/ProjectionExec.pre.sol, solidity/src/proof_plans/ProofPlan.pre.sol, solidity/src/proof_plans/SliceExec.pre.sol, solidity/src/verifier/Verifier.pre.sol, solidity/test/proof_exprs/ProofExpr.t.pre.sol, solidity/test/proof_exprs/ScalingCastExpr.t.pre.sol
Add scaling cast expr to solidity
=> feat(sol): add scaling cast expr to solidity

crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs, solidity/src/proof_plans/GroupByExec.pre.sol, solidity/test/proof_plans/GroupByExec.t.pre.sol, solidity/test/proof_plans/ProofPlan.t.pre.sol
- move result MLEs to first round
=> fix!: move result MLEs to first round for group by

crates/proof-of-sql/src/base/database/join_util.rs
There are a number of opportunities to improve the `join_util` module's `get_sort_merge_join_indexes` function. The first is to make the sorting algorithms parallel using the Rayon crate, this work has been added to a different PR - https://github.com/spaceandtimefdn/sxt-proof-of-sql/pull/988. This PR completes the work by avoiding creating intermediate temporary vectors and popular the result vector directly.
`get_sort_merge_join_indexes` before - 114.79 ms
`get_sort_merge_join_indexes` after - 35.47 ms, a 3.2x speed up
- Multiple intermediate memory allocations in the main loop are avoided to directly populate the result vector using pre-allocated vectors
- A tracing span is added
Yes
=> perf: improve the `join_util` module's `get_sort_merge_join_indexes` function

crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
This PR adds a parallel implementation to the `numerical_utils` module's `multiply_columns` function. Various benchmarks have improved with this change. For example, the Sum Count benchmark query had a 1.42x performance improvement on the Multi-A100 VM with a table size of `1,000,000`. The `MultiplyExpr::final_round_evaluate` saw a 9.42x performance improvement.
Before 2.39s
After 1.72s
This is a first step. Further improvements will investigate doing multiplication inside of the Column module to avoid conversions during each multiplication.
Note: creating an `unsafe_scalar_at` function that avoid returning an Option did not show any performance gains when benchmarked.
- A Rayon implementation is added to the the `numerical_utils` module's `multiply_columns` function
Yes
=> perf: add parallel implementation to the `numerical_utils` module's `multiply_columns` function

crates/proof-of-sql-planner/src/plan.rs
In `DataFusion` we have [TableScan](https://docs.rs/datafusion-expr/latest/datafusion_expr/logical_plan/struct.TableScan.html)s which can not rename or reorder columns. Hence it is absurd to use the current conversion which makes serialized `ProofPlan`s absurdly large. Let's just convert a `DataFusion` `LogicalPlan` `TableScan` without any filter to a `TableScan` rather than a `ProjectionExec` on top of a `TableScan`.
Replace `table_scan_to_projection` with `table_scan_to_proof_plan`.
Yes
=> refactor!: simplify `TableScan` conversion
