- README.md
- crates/proof-of-sql-parser/src/lib.rs
- crates/proof-of-sql/src/lib.rs
When pushing to crates.io, we want the docs to look good.
* The README is embeded in the `proof-of-sql` lib docs.
* The link in the README are turned into absolute, rather than relative, link.
* A link to the `proof-of-sql` crate is added to the `proof-of-sql-parser` crate.
Yes. The docs look good locally. It is possible that pushing to `docs.rs` will result in some other issues, but this is hard to test without pushing.
> docs: prep rustdocs for docs.rs

- Cargo.toml
- crates/proof-of-sql-parser/Cargo.toml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/src/lib.rs
A few of the fields in the `Cargo.toml` files that are required to publish to crates.io are either missing or out of date. This PR fixes them.
> build: update Cargo.toml files for release

- crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs
Recently it was observed that a function within the verifiable_query_result file has an incorrect type mapping:
```rust
fn make_empty_query_result<S: Scalar>(result_fields: Vec<ColumnField>) -> QueryResult<S> {
let table = OwnedTable::try_new(
result_fields
.iter()
.map(|field| {
(
field.name(),
match field.data_type() {
ColumnType::Boolean => OwnedColumn::Boolean(vec![]),
ColumnType::SmallInt => OwnedColumn::SmallInt(vec![]),
// needs to map to Int
ColumnType::Int => OwnedColumn::SmallInt(vec![]),
...
},
)
})
.collect(),
)?;
Ok(QueryData {
table,
verification_hash: Default::default(),
})
}
```
Mapping is adjusted to correct type.
Yes.
> fix: make_empty_query_result correct match arms

- Cargo.toml
Our dependency, `bigdecimal`, restricted `num-bigint` version in 0.4.4, leading to `num-bigint` downgrade to 0.3.3 which caused CI issues for us. Since [the issue](https://github.com/akubera/bigdecimal-rs/issues/128) has been resolved we need to bump our `bigdecimal` version to 0.4.5. 
- Bump `bigdecimal` version to 0.4.5
Yes
> fix: bump `bigdecimal` version to 0.4.5

- crates/proof-of-sql/src/sql/ast/and_expr.rs
- crates/proof-of-sql/src/sql/ast/dense_filter_expr.rs
- crates/proof-of-sql/src/sql/ast/dense_filter_expr_test.rs
- crates/proof-of-sql/src/sql/ast/dense_filter_expr_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/ast/equals_expr.rs
- crates/proof-of-sql/src/sql/ast/inequality_expr.rs
- crates/proof-of-sql/src/sql/ast/literal_expr.rs
- crates/proof-of-sql/src/sql/ast/not_expr.rs
- crates/proof-of-sql/src/sql/ast/or_expr.rs
- crates/proof-of-sql/src/sql/ast/provable_expr_plan.rs
- crates/proof-of-sql/src/sql/ast/test_utility.rs
- crates/proof-of-sql/src/sql/parse/enriched_expr.rs
- crates/proof-of-sql/src/sql/parse/filter_expr_builder.rs
- crates/proof-of-sql/src/sql/parse/mod.rs
- crates/proof-of-sql/src/sql/parse/provable_expr_plan_builder.rs
- crates/proof-of-sql/src/sql/parse/query_context.rs
- crates/proof-of-sql/src/sql/parse/query_expr.rs
- crates/proof-of-sql/src/sql/parse/query_expr_tests.rs
- crates/proof-of-sql/src/sql/parse/where_expr_builder.rs
- crates/proof-of-sql/tests/integration_tests.rs
It is necessary to move provable projections into the prover so that provable queries do not need postprocessing. This is the first PR of the change which is to move provable projections to the prover for filter queries.
- Move `Expression` -> `ProvableExprPlan` to a separate struct, `ProvableExprPlanBuilder` since the process is no longer for where clauses only.
- Add `EnrichedExpr` to be equivalent to the provable version of [Expr](https://docs.rs/datafusion/latest/datafusion/logical_expr/enum.Expr.html#method.alias) in DataFusion for tamperproof queries.
- Allow arbitrary aliased provable expressions as result expressions in dense filters. 
- Remove constraints in `QueryContext` that prevents constants from being used in select.
Existing tests should pass. New tests will be added to …
> feat: generalize `DenseFilterExpr`

- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_helper_gpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_vmv_helper.rs
- crates/proof-of-sql/src/proof_primitive/dory/eval_vmv_re.rs
- crates/proof-of-sql/src/proof_primitive/dory/mod.rs
- crates/proof-of-sql/src/proof_primitive/dory/public_parameters.rs
- crates/proof-of-sql/src/proof_primitive/dory/setup.rs
- crates/proof-of-sql/src/proof_primitive/dory/transpose.rs
When creating a Dory proof the `compute_T_vec_prime` function requires multiple MSMs. The current implementation of this function only supports the use of the Arkworks library, which only runs on the CPU. In an effort to improve the performance of Dory, this PR introduces the Blitzar fixed MSM to `compute_T_vec_prime` when appropriate to perform the MSM computations.
The commit focusing only on performance changes is available [here](https://github.com/spaceandtimelabs/sxt-proof-of-sql/commit/ba506b0b5c4be809ca424e07423c67f15fee6c15).
- `compute_T_vec_prime` now supports Blitzar's fixed MSM if the feature flag `"blitzar"` is turned on. The CPU version using Arkworks is still supported.
- The `transpose_column` and related functions appearing in the `dory_commitment_helper_gpu` class are …
> perf: Dory's compute_T_vec_prime should be able to use Blitzar's fixed MSM (PROOF-876)

- Cargo.toml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/src/base/commitment/column_bounds.rs
- crates/proof-of-sql/src/base/commitment/column_commitment_metadata.rs
- crates/proof-of-sql/src/base/commitment/committable_column.rs
- crates/proof-of-sql/src/base/database/arrow_array_to_column_conversion.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/literal_value.rs
- crates/proof-of-sql/src/base/database/owned_and_arrow_conversions.rs
- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/database/owned_table_test.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor_test.rs
- crates/proof-of-sql/src/base/database/owned_table_utility.rs
- crates/proof-of-sql/src/base/database/record_batch_dataframe_conversion.rs
- crates/proof-of-sql/src/base/database/record_batch_utility.rs
- crates/proof-of-sql/src/base/database/test_accessor_utility.rs
- crates/proof-of-sql/src/base/mod.rs
- crates/proof-of-sql/src/base/polynomial/multilinear_extension.rs
- crates/proof-of-sql/src/base/scalar/mod.rs
- crates/proof-of-sql/src/base/time/mod.rs
- crates/proof-of-sql/src/base/time/timestamp.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_helper_cpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_helper_gpu.rs
- crates/proof-of-sql/src/sql/ast/dense_filter_util.rs
- crates/proof-of-sql/src/sql/ast/filter_result_expr.rs
- crates/proof-of-sql/src/sql/ast/group_by_util.rs
- crates/proof-of-sql/src/sql/proof/provable_query_result.rs
- crates/proof-of-sql/src/sql/proof/provable_result_column.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs
Provides the initial typing support for a postgresql-like ```TimeStamp``` type. The proofs ```TimeStampTZ``` is typed over a custom ```TimeUnit``` and ```TimeZone``` type.
The choice is made to type out TimeStamp in this way because the arrow::datatypes::TimeStamp has a required TimeUnit field and an Option TimeZone  field. Typing out our own TimeStamp with these fields gives us greater control over the arrow type if we want. We can also jut default to seconds and UTC if needed, which would simplify this design a bit.
The ```arrow::datatypes::timezone``` is typed over a ```TimeUnit``` and an optional timezone ```Option<Arc<str>>```. Thus in our application it makes sense to have a mapping of this metadata:
example:
```rust
// arrow datatype mapping to our new timestamp type …
```
> feat!: initial support for timestamp

- crates/proof-of-sql/src/base/commitment/committable_column.rs
- crates/proof-of-sql/src/sql/ast/group_by_util.rs
Incorporates a small amount of feedback from #12 
Corrects naming in tests and removes unsupported feature in group_by_util
yes
> fix: incorporate leftover feedback from previous PR

- crates/proof-of-sql/src/sql/proof/provable_query_result.rs
- crates/proof-of-sql/src/sql/proof/provable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/query_result.rs
- crates/proof-of-sql/src/sql/proof/result_element_serialization.rs
For arithmetic (such as #14) to work it is necessary to separate element decoding error from verification error. There are already `QueryError::Overflow` and `QueryError::InvalidString` that handle some decoding errors. However currently in practice if overflows do take place we get `VerificationError`. This PR will fix this issue.
- add `QueryError::MiscellaneousDecodingError`, `QueryError::InvalidIndexes` and `QueryError::MiscellaneousEvaluationError` to account for decoding errors beyond overflows and invalid strings
- if decoding errors happen we will use them instead of `VerificationError`
- add overflow test in `crates/proof-of-sql/src/sql/proof/provable_query_result_test.rs`
Yes.
> fix!: separate element decoding error from verification error

- crates/proof-of-sql/src/sql/ast/column_expr.rs
- crates/proof-of-sql/src/sql/ast/dense_filter_expr.rs
- crates/proof-of-sql/src/sql/ast/filter_expr.rs
- crates/proof-of-sql/src/sql/ast/group_by_expr.rs
- crates/proof-of-sql/src/sql/ast/group_by_util.rs
- crates/proof-of-sql/src/sql/ast/group_by_util_test.rs
- crates/proof-of-sql/src/sql/ast/proof_plan.rs
- crates/proof-of-sql/src/sql/proof/proof_exprs.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/test_query_expr.rs
The `GroupByExpr` needs to have the result checked for uniqueness of the groups in order to prevent a malicious prover from returning a result that is only partially aggregated.
* `ProofExpr::verifier_evaluate` now accepts an optional result as a parameter.
* `GroupByExpr` uses this result to check that the groups are strictly increasing. This guarantees uniqueness.
Yes.
> fix: add check for group by result uniqueness

- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/sql/ast/add_subtract_expr.rs
- crates/proof-of-sql/src/sql/ast/add_subtract_expr_test.rs
- crates/proof-of-sql/src/sql/ast/comparison_util.rs
- crates/proof-of-sql/src/sql/ast/equals_expr.rs
- crates/proof-of-sql/src/sql/ast/inequality_expr.rs
- crates/proof-of-sql/src/sql/ast/mod.rs
- crates/proof-of-sql/src/sql/ast/numerical_util.rs
- crates/proof-of-sql/src/sql/ast/provable_expr_plan.rs
- crates/proof-of-sql/src/sql/ast/test_utility.rs
- crates/proof-of-sql/src/sql/parse/error.rs
- crates/proof-of-sql/src/sql/parse/provable_expr_plan_builder.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/parse/query_expr_tests.rs
- crates/proof-of-sql/tests/integration_tests.rs
We need to add support for arithmetic. Let's start from + and -.
- Add support for + and - in `proof-of-sql` crate
- generalize `scale_and_subtract_eval` to `scale_and_add_subtract_eval`
- make sure we pass in scales in any operation that can involve decimals
Yes.
> feat: add `AddSubtractExpr`

- .github/workflows/lint-and-test.yml
- .github/workflows/release.yaml
- ci/build.sh
- package.json
Since we want to use 0.x.y versions for now, we modify the behavior via
releaseRules, e.g.
* breaking is set to minor release (by default it's major)
* feat is set to patch (by default it's minor)
Once we release v1.0.0 we should reset these to their intended behavior.
> ci: add semantic-release

- Cargo.toml
- crates/proof-of-sql/src/sql/ast/add_subtract_expr_test.rs
- crates/proof-of-sql/tests/integration_tests.rs
We need to check and make sure that [this fix](https://github.com/spaceandtimelabs/blitzar/pull/144) is properly used.
- bump blitzar version to 3.0.2
- add tests to ensure that commitments work on integer extrema
- fix existing tests that once require workarounds
Yes
> fix: bump blitzar version to 3.0.2

- crates/proof-of-sql/src/base/commitment/column_bounds.rs
- crates/proof-of-sql/src/base/commitment/column_commitment_metadata.rs
- crates/proof-of-sql/src/base/commitment/committable_column.rs
- crates/proof-of-sql/src/base/database/arrow_array_to_column_conversion.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/literal_value.rs
- crates/proof-of-sql/src/base/database/owned_and_arrow_conversions.rs
- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/database/owned_table_test.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor_test.rs
- crates/proof-of-sql/src/base/database/owned_table_utility.rs
- crates/proof-of-sql/src/base/time/mod.rs
- crates/proof-of-sql/src/base/time/timestamp.rs
- crates/proof-of-sql/src/base/time/timezone.rs
The timestamp module is large enough now to warrant its own submodule. It will grow in size with the addition of the intermediate timestamp conversions.
Moves various components of timestamp into appropriate modules.
yes
> refactor: reorganize timestamp

- ci/build.sh
- ci/publish.sh
- package.json
We should automate the release process, including publishing to crates.io.
* `ci/build.sh` is renamed to `ci/publish.sh` and a cargo publish dry run is added.
Note: `cargo publish -p proof-of-sql --dry-run` will fail because it relies on `proof-of-sql-parser` actually being published.
Yes. This script is what was used to publish versions 0.2.1 through 0.3.1. (By removing `--dry-run`.)
> ci: update semantic release to dry run cargo publish 

- ci/publish.sh
Semantic release is failing because `cargo publish -p proof-of-sql --dry-run` fails since it needs `proof-of-sql-parser`, which doesn't publish because it is a dry run.
Commented out the dry-run for `proof-of-sql` publishing.
No
> ci: fix dry-run

- crates/proof-of-sql/src/sql/ast/add_subtract_expr_test.rs
- crates/proof-of-sql/src/sql/ast/aliased_provable_expr_plan.rs
- crates/proof-of-sql/src/sql/ast/dense_filter_expr.rs
- crates/proof-of-sql/src/sql/ast/dense_filter_expr_test.rs
- crates/proof-of-sql/src/sql/ast/dense_filter_expr_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/ast/mod.rs
- crates/proof-of-sql/src/sql/ast/multiply_expr_test.rs
- crates/proof-of-sql/src/sql/ast/test_utility.rs
- crates/proof-of-sql/src/sql/parse/filter_expr_builder.rs
- crates/proof-of-sql/src/sql/parse/query_expr_tests.rs
In new versions of `GroupByExpr` tuple `(ProvableExprPlan<C>, Identifier)` is extremely common. We may as well add a struct for this.
- add `AliasedProvableExprPlan`
- one instance of minor typo fix
> refactor: add `AliasedProvableExprPlan`

- crates/proof-of-sql-parser/src/intermediate_ast.rs
- crates/proof-of-sql/src/sql/ast/aggregate_expr.rs
- crates/proof-of-sql/src/sql/ast/mod.rs
- crates/proof-of-sql/src/sql/ast/provable_expr_plan.rs
- crates/proof-of-sql/src/sql/parse/enriched_expr.rs
- crates/proof-of-sql/src/sql/parse/provable_expr_plan_builder.rs
This is the first PR in generalization of `GroupByExpr`. Following conventions from [datafusion](https://docs.rs/datafusion/latest/datafusion/logical_expr/enum.Expr.html) we allow `AggregateExpr` so that provable aggregations can be expressed in `ProvableExprPlan` and provide relevant conversion.
- add `AggregateExpr` which allows expressions such as `sum(a+b)` to become `ProvableExprPlan`
- allow `Expression` -> `ProvableExprPlan` for aggregations
> feat: add aggregation-related intermediate AST conversions

- ci/publish.sh
This PR automates `cargo publish`.
`--dry-run` is removed and a crates token is added
Not possible.
> ci: automate cargo publish

- .github/workflows/release.yaml
#37 did not enable the `CRATES_TOKEN`. This PR does this.
> ci: enable `CRATES_TOKEN` in env

- crates/proof-of-sql/src/sql/ast/aggregate_expr.rs
- crates/proof-of-sql/src/sql/ast/group_by_expr.rs
- crates/proof-of-sql/src/sql/ast/group_by_expr_test.rs
- crates/proof-of-sql/src/sql/ast/test_utility.rs
- crates/proof-of-sql/src/sql/parse/query_context.rs
- crates/proof-of-sql/src/sql/parse/query_expr_tests.rs
- crates/proof-of-sql/tests/integration_tests.rs
This PR generalizes `GroupByExpr` by relaxing the requirement of `expr` in `SUM(expr)` to arbitrary `ProvableExprPlan` outside aggregation.
Generalize `sum_expr` in `GroupByExpr`
Old tests all pass. We need to get new ones with nontrivial `sum_expr` to pass as well.
> feat: generalize `sum_expr` in `GroupByExpr`

- crates/proof-of-sql/benches/scaffold/benchmark_accessor.rs
- crates/proof-of-sql/benches/scaffold/mod.rs
- crates/proof-of-sql/src/base/commitment/column_commitments.rs
- crates/proof-of-sql/src/base/commitment/commitment_evaluation_proof.rs
- crates/proof-of-sql/src/base/commitment/commitment_evaluation_proof_test.rs
- crates/proof-of-sql/src/base/commitment/mod.rs
- crates/proof-of-sql/src/base/commitment/query_commitments.rs
- crates/proof-of-sql/src/base/commitment/table_commitment.rs
- crates/proof-of-sql/src/base/commitment/vec_commitment_ext.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_evaluation_proof.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_evaluation_proof_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_helper_cpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_helper_gpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_compute_commitments_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_public_setup.rs
- crates/proof-of-sql/src/proof_primitive/dory/mod.rs
- crates/proof-of-sql/src/proof_primitive/dory/public_parameters.rs
- crates/proof-of-sql/src/proof_primitive/dory/setup.rs
- crates/proof-of-sql/src/sql/proof/proof_builder.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs
- crates/proof-of-sql/tests/integration_tests.rs
The setups in Dory are somewhat unwieldy, in particular, there isn't a separation between the public parameters, the precomputed setups, and the parameters for a particular proofs.
The major change involves `PublicParameters`, `ProverSetup`, `VerifierSetup`, `DoryProverPublicSetup`, and `DoryVerifierPublicSetup`. The code for constructing these was made more explicit and broken apart better.
```
let dory_prover_setup = DoryProverPublicSetup::rand(4, 3, &mut test_rng());
let dory_verifier_setup = (&dory_prover_setup).into();
```
```
let public_parameters = PublicParameters::rand(4, &mut test_rng()); // This can be stored on disc and is the actual data from which everything else is generated.
let prover_setup = ProverSetup::from(&public_parameters); // This largely is just a reference to …
```
> refactor!: tidy dory setups

- crates/proof-of-sql/src/base/polynomial/composite_polynomial.rs
- crates/proof-of-sql/src/sql/ast/mod.rs
- crates/proof-of-sql/src/sql/ast/projection_expr.rs
- crates/proof-of-sql/src/sql/ast/projection_expr_test.rs
- crates/proof-of-sql/src/sql/ast/proof_plan.rs
- crates/proof-of-sql/src/sql/ast/test_utility.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
We need to add `ProjectionExpr` both as a faster and simpler alternative to `DenseFilterExpr` when there is no `WHERE` clause and to provide one mechanism to further generalize `GROUP BY` i.e. adding a `ProjectionExpr` after `GroupByExpr` without changing `GroupByExpr` itself. 
Add `ProjectionExpr`.
Yes.
> feat: add `ProjectionExpr`

- crates/proof-of-sql-parser/src/intermediate_ast_tests.rs
- crates/proof-of-sql-parser/src/sql.lalrpop
- crates/proof-of-sql/tests/decimal_integration_tests.rs
- crates/proof-of-sql/tests/integration_tests.rs
- crates/proof-of-sql/tests/timestamp_integration_tests.rs
Our non-tamperproof DQL service as well as most query engines allow `;` at the end of queries. 
Permit `;` in parser
Yes
> feat: permit `;` in parser

- crates/proof-of-sql/benches/README.md
- crates/proof-of-sql/benches/jaeger_benches.rs
In order to run benchmarks easily on Dory proof evaluation performance, this PR adds a new benchmark type to `jaeger_benches`. An argument is added to the command line interface to define the benchmark type. 
Previously, the Jaeger benchmarks were only run on the inner product proof with the command:
`cargo bench -p proof-of-sql --bench jaeger_benches`
which has been updated to
`cargo bench -p proof-of-sql --bench jaeger_benches InnerProductProof`.
The Dory proof evaluation benchmark can be run with
`cargo bench -p proof-of-sql --bench jaeger_benches Dory features="test"`.
- A Jaeger benchmark is added for Dory.
- A command line argument is added to specify which benchmark to run: `InnerProductProof` or `Dory --features="test"`
Yes
> bench: add Jaeger benchmarks for Dory proof evaluation (PROOF-892)

- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/math/mod.rs
- crates/proof-of-sql/src/base/math/permutation.rs
- crates/proof-of-sql/src/sql/postprocessing/error.rs
- crates/proof-of-sql/src/sql/postprocessing/mod.rs
- crates/proof-of-sql/src/sql/postprocessing/order_by_expr.rs
- crates/proof-of-sql/src/sql/postprocessing/order_by_expr_test.rs
- crates/proof-of-sql/src/sql/postprocessing/owned_table_postprocessing.rs
- crates/proof-of-sql/src/sql/postprocessing/test_utility.rs
We need to have a native Rust implementation of postprocessing for `ORDER BY` so that we can remove polars & the `transformation` module.
- add `math::permutation::Permutation`
- add `OwnedColumn::try_permute`
- add `sql::postprocessing::OrderByExpr`
Yes
> feat: implement `postprocessing::OrderByExpr`

- crates/proof-of-sql/src/sql/parse/query_context.rs
- crates/proof-of-sql/src/sql/parse/query_expr.rs
- crates/proof-of-sql/src/sql/parse/query_expr_tests.rs
- crates/proof-of-sql/tests/integration_tests.rs
Recently we found weird postprocessing bugs for group bys. What we found is that
1. Currently provable `GROUP BY`s without a `WHERE` clause are not supported even though to support it is trivial.
2. Currently if a `GROUP BY` clause is provable the `ResultExpr` still incorrectly contains aggregate functions.
- fix postprocessing projection with provable `GROUP BY`
- allow provable group by without `WHERE` clause
- enable 3 ignored tests
Yes
> fix: fix postprocessing projection in provable `GROUP BY`s & allow `WHERE` clause to be omitted

- crates/proof-of-sql-parser/src/error.rs
- crates/proof-of-sql-parser/src/posql_time/unit.rs
- crates/proof-of-sql/src/base/database/column.rs
In DDL, a Timestamp column can be instantiated with the following syntax:
```sql
TIMESTAMP(6)
```
where 6 represents millisecond precision. It appears that the gateway by default supports only nanosecond precision on DDL, however if this changes in the future, we will need a way to parse the time unit from a DDL message in proofs-service. This PR contains a simple string parser that allows for selection of a supported precision for timestamp columns. 
```
column type TIMESTAMP(TIMEUNIT: UTC, TIMEZONE: NANOSECONDS (PRECISION: 9)) 
``` 
yes
> feat: time unit try from string

- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/tests/timestamp_integration_tests.rs
Quick PR to add support for inequality expressions between timestamps. Since theyre represented internally as i64, they can be easily compared against one another.
Adds support for statements with the following syntax:
```
SELECT * FROM table WHERE times <= timestamp '1970-01-01T00:00:00Z
SELECT * FROM table WHERE times >= timestamp '1970-01-01T00:00:00Z
SELECT * FROM table WHERE times > timestamp '1970-01-01T00:00:00Z
SELECT * FROM table WHERE times < timestamp '1970-01-01T00:00:00Z
```
yes
> feat: timestamp inequality support

- crates/proof-of-sql/src/base/scalar/mod.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar_from_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_test.rs
- crates/proof-of-sql/src/sql/ast/group_by_util.rs
- crates/proof-of-sql/tests/integration_tests.rs
It is necessary for us to be able to do comparison and aggregation on decimal columns.
- add `signed_cmp` to `Scalar` definition to do signed Scalar comparison (i.e. `S::MAX_SIGNED` is the largest number and everything "beyond" it wraps around into negative numbers)
- allow decimal comparison
- allow `SUM` of decimals
Yes.
> fix: fix decimal comparison and aggregation

- crates/proof-of-sql-parser/src/posql_time/timezone.rs
Arrow displays inconsistent behavior when instantiating timestamp record columns which include timezones. It is observed that "00:00" is interpreted as a valid timezone string by arrow, but "+00:00" is. 
This PR simply updates the display impl for timezone to match this expectation. 
yes
> fix: timezone display

- crates/proof-of-sql/src/base/commitment/commitment_evaluation_proof.rs
- crates/proof-of-sql/src/base/commitment/mod.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_evaluation_proof.rs
The `Commitment` trait has a `fold_commitments` which is only used internally to the `CommitmentEvaluationProof`, and as a result, is somewhat superfluous, making adding new commitment schemes more complex.
* `Commitment::fold_commitments` is removed.
* `CommitmentEvaluationProof::verify_batched_proof` is no longer a provided method. Instead, `CommitmentEvaluationProof::verify_proof` is a provided method, and implementers must implement `verify_batched_proof` instead.
By existing tests.
> refactor: simplify commitment trait

- crates/proof-of-sql-parser/Cargo.toml
- crates/proof-of-sql-parser/src/error.rs
- crates/proof-of-sql-parser/src/intermediate_ast.rs
- crates/proof-of-sql-parser/src/lib.rs
- crates/proof-of-sql-parser/src/posql_time/error.rs
- crates/proof-of-sql-parser/src/posql_time/mod.rs
- crates/proof-of-sql-parser/src/posql_time/timestamp.rs
- crates/proof-of-sql-parser/src/posql_time/timezone.rs
- crates/proof-of-sql-parser/src/posql_time/unit.rs
- crates/proof-of-sql-parser/src/sql.lalrpop
- crates/proof-of-sql-parser/src/test_utility.rs
- crates/proof-of-sql/src/base/commitment/column_bounds.rs
- crates/proof-of-sql/src/base/commitment/column_commitment_metadata.rs
- crates/proof-of-sql/src/base/commitment/committable_column.rs
- crates/proof-of-sql/src/base/database/arrow_array_to_column_conversion.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/literal_value.rs
- crates/proof-of-sql/src/base/database/owned_and_arrow_conversions.rs
- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/database/owned_table_test.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor_test.rs
- crates/proof-of-sql/src/base/database/owned_table_utility.rs
- crates/proof-of-sql/src/base/database/record_batch_utility.rs
- crates/proof-of-sql/src/base/database/test_accessor_utility.rs
- crates/proof-of-sql/src/sql/parse/error.rs
- crates/proof-of-sql/tests/timestamp_integration_tests.rs
For intermediate AST -> Provable AST and intermediate AST postprocessing evaluation tests in `proof-of-sql` it is a good idea to be able to use shortcuts in `proof_of_sql_parser::test_utility`. 
- put `test_utility.rs` in parser behind a feature flag and allow it to be used by the other crate
- prevent `posql_time` from being unnecessarily convoluted
> refactor: simplify `proof-of-sql-parser`

- crates/proof-of-sql/src/base/database/arrow_array_to_column_conversion.rs
- crates/proof-of-sql/src/base/math/decimal.rs
- crates/proof-of-sql/src/base/scalar/mod.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar.rs
- crates/proof-of-sql/src/sql/parse/error.rs
This PR was split from #56. For evaluation to work it is good if decimal-related errors remain `DecimalError`s as opposed to requiring `ConversionError`. It also lowers the possibility of circular dependencies.
- eliminate any dependency of `proof-of-sql::base` on `proof-of-sql::sql` including references to `sql::parse::ConversionError`
- remove all references to `sql::parse::ParseError` from `decimal.rs`
- refactor `Scalar` def so that `TryFrom<BigInt>` now has `ScalarConversionError`
> refactor: exclusively use `DecimalError` for `proof-of-sql` decimal-related errors

- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_standard_basis_helper.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_structure.rs
- crates/proof-of-sql/src/proof_primitive/dory/mod.rs
We need to add the Dynamic Dory commitment scheme. This is the first PR.
* Added the `compute_dynamic_standard_basis_vecs` method, a helper method used to compute the vectors in the Vector-Matrix-Vector product in the dynamic dory scheme.
* Added `row_and_column_from_index` and `row_start_index` methods. These methods define the structure of the new dynamic dory commitmemt scheme.
Yes
> feat: add Dynamic Dory helper methods

- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_evaluation_proof.rs
- crates/proof-of-sql/src/proof_primitive/dory/extended_dory_inner_product.rs
- crates/proof-of-sql/src/proof_primitive/dory/extended_dory_inner_product_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/extended_dory_reduce.rs
- crates/proof-of-sql/src/proof_primitive/dory/extended_dory_reduce_helper.rs
- crates/proof-of-sql/src/proof_primitive/dory/extended_state.rs
- crates/proof-of-sql/src/proof_primitive/dory/fold_scalars.rs
- crates/proof-of-sql/src/proof_primitive/dory/fold_scalars_test.rs
We need to add the Dynamic Dory commitment scheme. In order to make the existing methods work with the dynamic dory commitment scheme, the method that folds the s tensors within the verify methods needs to be modified. In particular, it needs to have access to all the folding factors at a time in order to fold properly.
The folding of the s tensor is now done once within the `fold_scalars_0_verify` rather than accumulating within each round.
There are 2 main changes to accomplish this:
* During each round/call of `extended_dory_reduce_verify`, instead of mutating the s tensors, the `alpha` folding factors are added to the `state`.
* `fold_s_tensors_verify` is added as a parameter to `extended_dory_inner_product_verify` and `fold_scalars_0_verify`
Existing tests pass.
> refactor: add flexibility for dory verifier folding

- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_standard_basis_helper.rs
This PR adds the verifier folding method for the dynamic dory commitment scheme.
* The `fold_dynamic_standard_basis_tensors` is added and implemented. This method is the verifier's equivalent of `compute_dynamic_standard_basis_vecs`. Ultimately, there is still wrapper code needed to use this method.
Yes
> feat: dynamic dory verifier folding helper

- crates/proof-of-sql/src/base/database/column.rs
This is a clean and explicit solution. Note that for all timestamp types we have `scale = 0` since in #75 time unit is removed anyway. Also this is a refactoring since it doesn't affect functionality.
- Explicitly mention all enum variants in `ColumnType::precision_value` and `ColumnType::scale`
Yes
> refactor: explicitly mention all enum variants in `ColumnType::precision_value` and `ColumnType::scale`

- crates/proof-of-sql/src/base/database/column_operation.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/owned_column_operation.rs
This PR is split out from #70 since it has become too large. The actual content of this PR (that is, what's not in #70) is here: https://github.com/spaceandtimelabs/sxt-proof-of-sql/pull/74/commits/e1667622c3db3b45af75dd1f1bf167f3e2a646e5
- Define `Add`, `Sub` and `Mul` for `OwnedColumn`
Yes.
> feat: define `Add`, `Sub` and `Mul` for `OwnedColumn`

- crates/proof-of-sql/src/base/database/scalar_and_i256_conversions.rs
- crates/proof-of-sql/src/base/scalar/mod.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_test.rs
This PR is a prerequisite of #77. 
- add implementation as a part of `scalar_conversion_to_int` macro which is necessary since blanket implementation of `TryFrom` or `TryInto` is not allowed for traits by Rust
- improve the macro so that `TryInto` is replaced with the more natural `TryFrom`
- replace `std` with `core`
Yes
> feat: add `Into<BigInt>` to `Scalar` & improvement to `Scalar` in general

- crates/proof-of-sql/src/base/database/column_operation.rs
- crates/proof-of-sql/src/base/database/column_operation_error.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/owned_column_operation.rs
Division is needed in postprocessing hence we need to add it. Please merge #70 before reviewing this PR or alternatively look at the latest commit.
- add division to `column_operation`
- implement `Div` for `OwnedColumn`
Yes.
> feat: add division to `column_operation` and `Div` to `OwnedColumn`

- crates/proof-of-sql-parser/src/posql_time/timestamp.rs
- crates/proof-of-sql-parser/src/posql_time/timezone.rs
- crates/proof-of-sql-parser/src/posql_time/unit.rs
- crates/proof-of-sql/src/sql/parse/provable_expr_plan_builder.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/tests/timestamp_integration_tests.rs
Timestamp literals were parsed in seconds despite containing up to nanosecond precision. This caused a situation where equality and inequality queries would fail across the board. This is the first small PR to address this issue. Timestamps of varying, user supplied precisions are now parsed correctly.
yes. next PR is to refactor existing timestamp tests into appropriate ast tests.
> fix: timestamp precision

- crates/proof-of-sql-parser/src/utility.rs
- crates/proof-of-sql/src/base/database/expression_evaluation.rs
- crates/proof-of-sql/src/base/database/expression_evaluation_error.rs
- crates/proof-of-sql/src/base/database/expression_evaluation_test.rs
- crates/proof-of-sql/src/base/database/mod.rs
This PR replaces #56 since we made substantial changes to evaluations in #70, #74, #76 and #78. Please review #87 first or look at the second commit.
- add `PostprocessingEvaluator`
- add arithmetic to `proof_of_sql_parser::utility`
Yes
> feat: add `expression_evaluation.rs` and add arithmetic to `proof_of_sql_parser::utility`

- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/sql/parse/where_expr_builder_tests.rs
- crates/proof-of-sql/tests/timestamp_integration_tests.rs
This is the second small PR that corrects the scaling of differing timestamp precisions for operations such as inequality or equality comparisons.
existing tests pass, incorrect tests are removed. The next PR will contain a large refactor of existing timestamptz tests.
> fix!: timestamp scaling

- crates/proof-of-sql/src/base/database/filter_util.rs
- crates/proof-of-sql/src/base/database/filter_util_test.rs
- crates/proof-of-sql/src/base/database/group_by_util.rs
- crates/proof-of-sql/src/base/database/group_by_util_test.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/sql/ast/dense_filter_expr.rs
- crates/proof-of-sql/src/sql/ast/dense_filter_expr_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/ast/fold_util.rs
- crates/proof-of-sql/src/sql/ast/fold_util_test.rs
- crates/proof-of-sql/src/sql/ast/group_by_expr.rs
- crates/proof-of-sql/src/sql/ast/mod.rs
In order to reuse these utils for both proof generation and postprocessing we need to move them into `base::database`
- move most of `dense_filter_util` and all of `group_by_util` to `base::database`
- rename the remaining file to `fold_util` & the moved one to `filter_util`
> refactor: move `dense_filter_util` and `group_by_util` to `base::database`

- crates/proof-of-sql/src/base/database/group_by_util.rs
This PR continues #91.
-  add `min_aggregate_slice_by_index_counts` and `max_aggregate_slice_by_index_counts` 
Not right now.
> feat: add `min` and `max` to `group_by_utils.rs`

- crates/proof-of-sql/src/proof_primitive/dory/dory_compute_commitments_test.rs
In an effort to support Blitzar's new `packed_msm` interface, we need to make a number of updates to the Dory commitment computation. This PR adds additional tests for committable columns of various types. These tests will help ensure the data packing done for the `packed_msm` interface is done correctly for all supported data types.
- Five tests have been added to the Dory compute commitment test class.
Yes
> test: add mixed committable column tests to the Dory compute commitment test class (PROOF-898)

- crates/proof-of-sql/src/base/database/group_by_util.rs
- crates/proof-of-sql/src/base/database/group_by_util_test.rs
- crates/proof-of-sql/src/sql/ast/group_by_expr.rs
We need to add `max` and `min` to `AggregateColumns` for postprocessing even though we don't make them provable just yet.
- add max and min to `AggregateColumns`
Yes.
> feat: add `MAX` and `MIN` to `AggregateColumns`

- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/database/owned_column_error.rs
- crates/proof-of-sql/src/base/scalar/mod.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_test.rs
We need to be able to convert from scalars back to respective types after doing aggregations.
- add `try_from_scalars` and `try_from_option_scalars` to `OwnedColumn`
Yes.
> feat: add relevant conversions for group by

- crates/proof-of-sql/src/sql/ast/inequality_expr.rs
- crates/proof-of-sql/src/sql/ast/inequality_expr_test.rs
- crates/proof-of-sql/src/sql/ast/sign_expr.rs
- crates/proof-of-sql/src/sql/ast/sign_expr_test.rs
- crates/proof-of-sql/src/sql/proof/mod.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
The `QueryProof::new_from_builder` method is only used in one place: a test. It adds non-trivial complexity to modifying `QueryProof`.
* This commit refactors the offending test by allowing `sign_expr` to, optionally, allow a column of zeros to be considered negative.
* `QueryProof::new_from_builder` is inlined into `QueryProof::new`.
Yes
> refactor: simplify `QueryProof::new`

- crates/proof-of-sql/src/base/database/owned_table.rs
This PR continues our removal of `polars`.
- remove `OwnedTable::apply_polars_filter`
> refactor!: remove `OwnedTable::apply_polars_filter`

- crates/proof-of-sql/src/sql/parse/mod.rs
- crates/proof-of-sql/src/sql/parse/where_expr_builder_tests.rs
This PR cleans up `where_expr_builder_test.rs` by using `proof_of_sql_parser::utility`.
- clean up `where_expr_builder_test.rs`
We changed tests exclusively.
> refactor: clean up `where_expr_builder_test.rs`

- crates/proof-of-sql/src/sql/ast/inequality_expr.rs
- crates/proof-of-sql/src/sql/ast/inequality_expr_test.rs
Suppose I have a table of times denoted in seconds:
```rust
accessor.add_table(
"sxt.table".parse().unwrap(),
owned_table([timestamptz(
"times",
PoSQLTimeUnit::Second,
PoSQLTimeZone::Utc,
test_timestamps,
)]),
0,
);
```
Assume that the table contains the following:
```rust
vec![-1, 0, 1];
```
And I wish to query the following against this table:
```sql
"SELECT * FROM table WHERE times < timestamp '1970-01-01T00:00:00.000000001Z'"
```
One would expect that the query should give back [-1, 0], but instead, after parsing the query and generating a proof:
```rust
// Parse and execute the query
let query = QueryExpr::try_new(
query_str.parse().unwrap(),
"sxt".parse().unwrap(),
&accessor,
)
.unwrap();
let proof = VerifiableQueryResult::<InnerProductProof>::new(query.proof_expr(), &accessor, …
```
> fix: correct scale bug in inequality expr

- crates/proof-of-sql-parser/src/utility.rs
- crates/proof-of-sql/src/sql/parse/error.rs
- crates/proof-of-sql/src/sql/parse/mod.rs
- crates/proof-of-sql/src/sql/parse/query_context.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/parse/query_expr.rs
- crates/proof-of-sql/src/sql/parse/query_expr_tests.rs
- crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs
- crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing_test.rs
- crates/proof-of-sql/src/sql/postprocessing/owned_table_postprocessing.rs
- crates/proof-of-sql/tests/decimal_integration_tests.rs
- crates/proof-of-sql/tests/integration_tests.rs
Please review #86 first. Otherwise please look at the second commit.
- switch from `sql::transform` to `sql::postprocessing`
- remove `sql::parser::ResultExprBuilder`
Yes
> feat!: use `sql::postprocessing` instead of `sql::transform` in `QueryExpr`

- .github/workflows/lint-and-test.yml
- crates/proof-of-sql-parser/Cargo.toml
- crates/proof-of-sql-parser/src/posql_time/unit.rs
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/examples/posql_db/run_example.sh
- crates/proof-of-sql/src/base/commitment/table_commitment.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/test_accessor_utility.rs
- crates/proof-of-sql/src/sql/ast/dense_filter_expr_test.rs
- crates/proof-of-sql/src/sql/ast/filter_expr_test.rs
- crates/proof-of-sql/src/sql/ast/projection_expr_test.rs
- crates/proof-of-sql/src/sql/proof/mod.rs
- crates/proof-of-sql/src/sql/proof/proof_builder_test.rs
- crates/proof-of-sql/src/sql/proof/query_result.rs
Please review #101 and #84 first.
In order to deal with use cases that require really small binaries it is a great idea to put arrow behind a feature flag.
See title
Yes
> refactor!: put `arrow` behind a feature flag

- Cargo.toml
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_helper_gpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/mod.rs
- crates/proof-of-sql/src/proof_primitive/dory/offset_to_bytes.rs
- crates/proof-of-sql/src/proof_primitive/dory/pack_scalars.rs
- crates/proof-of-sql/src/proof_primitive/dory/setup.rs
In order to improve the performance of the Dory protocol, the Dory commitment computation should use Blitzar's `packed_msm` function. Benchmarks indicate that the use of Blitzar's `packed_msm` over `fixed_msm` improves performance of proof generation.
Benchmarks, run on August 15, 2024, for the scalar packing done in this PR, show a speed up over three different VMs.
- Multi-A100 
- 4.48x speed up of `ProofBuilder::commit_intermediate_mles`
- 1.82x speed up of entire benchmark
- Multi-T4
- 3.66x speed up of `ProofBuilder::commit_intermediate_mles`
- 1.81x speed up of entire benchmark
- Single T4
- 1.91x speed up of `ProofBuilder::commit_intermediate_mles`
- 1.30x speed up of entire benchmark
- The `dory_commitment_helper_gpu` module replaces Blitzar's `fixed_msm` function with the more …
> perf: Dory commitments should be done with Blitzar's packed_msm function (PROOF-895)

- Cargo.toml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/src/base/proof/keccak256_transcript.rs
- crates/proof-of-sql/src/base/proof/mod.rs
- crates/proof-of-sql/src/base/proof/transcript.rs
- crates/proof-of-sql/src/base/proof/transcript_core.rs
- crates/proof-of-sql/src/base/proof/transcript_core_test.rs
- crates/proof-of-sql/src/base/proof/transcript_protocol.rs
In order to write the verifier in Solidity, we should enable using a Solidity compatibly public-coin transcript. This PR adds an API for doing so.
* added simplified `Transcript` trait
* implemented `Transcript` trait for `merlin::Transcript`
* added Solidity compatible `Keccak256Transcript`
* added tests for `Transcript` and implementations
Yes
> feat: add simplified `Transcript` trait and implementations

- crates/proof-of-sql/src/base/polynomial/interpolate.rs
- crates/proof-of-sql/src/base/polynomial/interpolate_test.rs
- crates/proof-of-sql/src/base/polynomial/mod.rs
In order for the sumcheck verifier to be able to be verify proofs more efficiently (and for the sake of the solidity port, with less code), the proof should consist of polynomial coefficients rather than evaluations. This PR adds the code to make the conversion. A later PR will do the switch.
* A `interpolate_evaluations_to_reverse_coefficients` method is added.
* Tests for this method are added.
Yes
> feat: add function converting evaluations to coefficients

- crates/proof-of-sql/src/proof_primitive/dory/eval_vmv_re.rs
This reduces the `eval_vmv_re_prove` component of the proof time from one of the larger factors to a negligible amount.
The computation of v2 within `eval_vmv_re_prove` now uses a rayon iterator.
Yes
> perf: parallelize v2 construction within `eval_vmv_re_prove`

- crates/proof-of-sql/src/proof_primitive/dory/offset_to_bytes.rs
- crates/proof-of-sql/src/proof_primitive/dory/pack_scalars.rs
- crates/proof-of-sql/src/proof_primitive/dory/transpose.rs
This PR reduces the cost of packing bytes in order to set up a packed MSM.
`offset_to_bytes` now returns an array rather than allocating a `Vec`.
Yes
> perf: improve `offset_to_bytes` performance

- crates/proof-of-sql/src/sql/proof/proof_plan.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof_plans/dense_filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/dense_filter_exec_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_result_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
This is a simple PR to make it possible to compose `ProofPlan`s which facilitates `SliceExec` and `UnionExec`.
- make `ProofPlan::result_evaluate` and `ProofPlan::prover_evaluate` return `Vec<Column<'a, S>>`
> feat!: allow `ProofPlan::result_evaluate` and `ProofPlan::prover_evaluate` to return columns

- crates/proof-of-sql/src/sql/proof/proof_plan.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof_plans/dense_filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_result_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
Here is the counterpart of #132 for verifiers.
- make `ProofPlan::verifier_evaluate` return `Vec<C::Scalar>`
> refactor!: allow `ProofPlan::verifier_evaluate` to return a vec of evals

- crates/proof-of-sql/benches/scaffold/benchmark_accessor.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/group_by_util_test.rs
- crates/proof-of-sql/src/base/database/owned_column_operation.rs
- crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/column_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/dense_filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/dense_filter_exec_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_result_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
Derives Copy for Column, reducing the need for cloning in production and test code. Note the diff includes changes to test code where this change isnt really necessary, but these changes satisfy clippy.
1. Derives Copy on Column
2. Removes unnecessary clones where applicable 
existing tests pass
> fix: derive copy for Column to prevent unnecessary cloning

- crates/proof-of-sql/src/sql/proof/proof_builder_test.rs
- crates/proof-of-sql/src/sql/proof/proof_plan.rs
- crates/proof-of-sql/src/sql/proof/provable_query_result.rs
- crates/proof-of-sql/src/sql/proof/provable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/result_builder.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test_utility.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec_test.rs
In order to make `ProofPlan`s composable to facilitate `SliceExec`, `UnionExec` and `JoinExec` we need to move result cols out of the `ResultBuilder` which is increasingly a misnomer.
- remove `ResultBuilder::produce_result_column`
- remove result columns from `ResultBuilder`
> refactor!: move result cols out of `ResultBuilder`

- .github/workflows/lint-and-test.yml
Blitzar now checks to the version of the Nvidia driver. It currently throws an error if the version is under `nvidia-driver-560`, causing the CI to fail. This PR installs the Nvidia driver before running tests with the GPU.
- The Test Suite portion of the Github workflow now:
- Adds the NVIDIA package repository since the`nvidia-driver-560` package is not yet available in the default Ubuntu repositories.
- Installs the`nvidia-driver-560` package when installing dependencies.
Yes, via Github CI.
> ci: install Nvidia drivers when running CI (PROOF-911)

- Cargo.toml
In order to get `forge-script` to compile, we needed to use various patches used by foundry. https://github.com/foundry-rs/foundry/pull/8838 removed these. So, we can remove the patches from our `Cargo.toml` file.
Yes
> build: bump forge-script version

- crates/proof-of-sql/src/base/database/column.rs
This PR fixes the function ```max_integer_type``` to safely handle the conversion from ```ColumnType``` into ```integer_bits```, if the type is an integer.
Dont unwrap ```to_integer_bits```, use an ```and_then``` chain instead.
yes, existing tests pass
> fix: safely handle max integer type

- crates/proof-of-sql/benches/scaffold/benchmark_accessor.rs
- crates/proof-of-sql/src/base/commitment/column_commitments.rs
- crates/proof-of-sql/src/base/commitment/mod.rs
- crates/proof-of-sql/src/base/commitment/vec_commitment_ext.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor.rs
- crates/proof-of-sql/src/sql/proof/verification_builder.rs
In a future PR, a NaiveCommitment will be created which has a vector of scalars as a field. Because this field can't implement Copy, Commitment will have to only use Clone.
1. Commitment becomes Clone rather than Copy.
2. Addressing any errors this change introduces.
No new tests
> refactor!: Implement Clone rather than Copy for Commitment

- .github/workflows/lint-and-test.yml
https://github.com/spaceandtimelabs/blitzar/pull/175 makes blitzar panic when there is no GPU rather than falling back to CPU. This PR fixes the CI so that it can run tests on the CPU
See the job.
> ci: set BLITZAR_BACKEND to be cpu

- crates/proof-of-sql/src/base/scalar/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/range_check.rs
This PR brings initial support for the updated range check functionality. It includes compartmentalized functions which handles the decomposition of scalars into words, and it handles the addition of the verifier challenge to each word and inverting the sum, forming the logarithmic derivative of the word and challenge.
yes
> feat: range check: decompose to words and get log derivative

- crates/proof-of-sql/src/base/commitment/column_bounds.rs
- crates/proof-of-sql/src/base/commitment/committable_column.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_helper_cpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/pack_scalars.rs
The ```CommitableColumn``` types are defined as types that can be used to produce an MLE. We need to add support here for committable columns of u8s, as this is the initial word size we have chosen for the range check.
> feat: add a range check word type for mle

- Cargo.toml
- clippy.toml
- crates/proof-of-sql-parser/src/intermediate_ast.rs
- crates/proof-of-sql-parser/src/lib.rs
- crates/proof-of-sql/benches/bench_append_rows.rs
- crates/proof-of-sql/benches/jaeger_benches.rs
- crates/proof-of-sql/benches/posql_benches.rs
- crates/proof-of-sql/examples/hello_world/main.rs
- crates/proof-of-sql/examples/posql_db/main.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/record_batch_utility.rs
- crates/proof-of-sql/src/base/encode/varint_trait.rs
- crates/proof-of-sql/src/base/math/mod.rs
- crates/proof-of-sql/src/base/mod.rs
- crates/proof-of-sql/src/base/polynomial/multilinear_extension.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar_from.rs
- crates/proof-of-sql/src/base/serialize.rs
- crates/proof-of-sql/src/proof_primitive/mod.rs
- crates/proof-of-sql/src/sql/parse/mod.rs
- crates/proof-of-sql/src/sql/parse/query_context.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/proof/result_builder.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
In order to improve our internal documentation, we should be documenting functionality. Enforcing this in CI simplifies review and development.
The `missing_docs_in_private_items` lint with the `missing-docs-in-crate-items` option set to true. This option means that missing docs are only warned if they have `pub(crate)` visibility. We could set this to `false` to be even more stringent. However, this would cause 473 more warnings for missing docs, and is likely a bit too much.
Yes
> docs: add `missing_docs_in_private_items` lint

- crates/proof-of-sql/src/base/commitment/commitment_evaluation_proof.rs
- crates/proof-of-sql/src/base/proof/transcript.rs
- crates/proof-of-sql/src/base/proof/transcript_core.rs
- crates/proof-of-sql/src/base/proof/transcript_protocol.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/proof.rs
In order to better support WASM, as well as enable solidity support, we need to be able to use a simplified transcript. However, the existing `Transcript` trait does not have the appropriate functionality to be able to only use the trait.
* The `Transcript::extend_serialize_as_le` method is added in order to be used as a possible replacement for the `<merlin::Transcript as TranscriptProtocol>::append_auto` method.
* The `Transcript::extend_canonical_serialize_as_le` method is added in order to be used as a possible replacement for the `<merlin::Transcript as TranscriptProtocol>::append_canonical_serialize` method.
* The `Transcript::wrap_transcript` method is added for when a `Transcript` needs to be wrapped in another.
* The sumcheck proof is updated to accept `impl Transcript` instead …
> feat: add functionality to `Transcript` trait and migrate sumcheck to use it

- Cargo.toml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/src/tests/mod.rs
See https://github.com/alloy-rs/alloy/issues/1307 and https://github.com/foundry-rs/foundry/issues/8895 for the background.
Disable solidity tests
Existing tests do pass
> fix: temporarily disable solidity tests

- crates/proof-of-sql/src/base/commitment/mod.rs
- crates/proof-of-sql/src/base/commitment/naive_commitment.rs
- crates/proof-of-sql/src/base/commitment/naive_commitment_test.rs
- crates/proof-of-sql/src/base/commitment/test_evaluation_proof.rs
- crates/proof-of-sql/src/base/scalar/mod.rs
- crates/proof-of-sql/src/base/scalar/test_scalar.rs
- crates/proof-of-sql/src/base/scalar/test_scalar_test.rs
In order to remove InnerProduct from the base directory, there will need to be several new test types so that the InnerProduct types are no longer need for the base tests.
1. New types: TestScalar, NaiveCommitment, TestEvaluationProof.
New unit tests for NaiveCommitment.
> feat: add test commitment and test scalar

- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verification_builder.rs
- crates/proof-of-sql/src/sql/proof/verification_builder_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/and_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/multiply_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/or_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/sign_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
The verifier and prover builders are a bit asymmetric with the `sumcheck_subpolynomial`. Additionally, the explicit use of `random_evaluation` is a bit confusing.
* `produce_sumcheck_subpolynomial_evaluation` now accepts a `SumcheckSubpolynomialType` as a parameter.
* Since this is a (only internal) breaking change, this also modifies `produce_sumcheck_subpolynomial_evaluation` to own it's `eval` parameter rather than borrow.
Yes, by existing code.
> refactor: add SubpolynomialType to verifier builder

- crates/proof-of-sql/README.md
- rust-toolchain.toml
In order to keep rust up to date, we should be periodically updating the toolchain we use.
* Update toolchain.toml
* Update README
> feat: bump rust toolchain to 1.81.0

- Cargo.toml
- crates/proof-of-sql-parser/Cargo.toml
- crates/proof-of-sql-parser/src/error.rs
- crates/proof-of-sql-parser/src/identifier.rs
- crates/proof-of-sql-parser/src/intermediate_ast.rs
- crates/proof-of-sql-parser/src/intermediate_ast_tests.rs
- crates/proof-of-sql-parser/src/intermediate_decimal.rs
- crates/proof-of-sql-parser/src/lib.rs
- crates/proof-of-sql-parser/src/posql_time/error.rs
- crates/proof-of-sql-parser/src/posql_time/timestamp.rs
- crates/proof-of-sql-parser/src/posql_time/timezone.rs
- crates/proof-of-sql-parser/src/resource_id.rs
- crates/proof-of-sql-parser/src/select_statement.rs
- crates/proof-of-sql-parser/src/sql.lalrpop
- crates/proof-of-sql-parser/src/utility.rs
We want to support `no_std` environments. `proof-of-sql-parser` can be `no_std` compatible.
* This PR refactors `proof-of-sql-parser` to mostly allow for `no_std`. Two dependencies: `lalrpop` and `thiserror` are still not `no_std`. See #176.
Yes, existing tests cover this.
> feat: `no_std` parser setup

- .github/workflows/lint-and-test.yml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/group_by_util.rs
- crates/proof-of-sql/src/base/mod.rs
- crates/proof-of-sql/src/base/polynomial/evaluation_vector.rs
- crates/proof-of-sql/src/base/polynomial/multilinear_extension.rs
- crates/proof-of-sql/src/base/rayon_cfg.rs
- crates/proof-of-sql/src/base/scalar/commitment_utility.rs
- crates/proof-of-sql/src/base/slice_ops/batch_inverse.rs
- crates/proof-of-sql/src/base/slice_ops/inner_product.rs
- crates/proof-of-sql/src/base/slice_ops/mod.rs
- crates/proof-of-sql/src/base/slice_ops/mul_add_assign.rs
- crates/proof-of-sql/src/base/slice_ops/slice_cast.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_helper_gpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_reduce_helper.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_vmv_helper.rs
- crates/proof-of-sql/src/proof_primitive/dory/eval_vmv_re.rs
- crates/proof-of-sql/src/proof_primitive/dory/pairings.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/prover_round.rs
- crates/proof-of-sql/src/sql/postprocessing/order_by_postprocessing.rs
- crates/proof-of-sql/src/sql/proof/composite_polynomial_builder.rs
- crates/proof-of-sql/src/sql/proof_exprs/comparison_util.rs
One of the components of this repo that is not `no_std` is rayon.
* The `slice_cast` module is simplified and leveraged more.
* An `if_rayon!` macro is added. This is the key to the majority of this PR.
```rust
macro_rules! if_rayon {
($rayon_value: expr, $else_value: expr) => {{
#[cfg(feature = "rayon")]
{
($rayon_value)
}
#[cfg(not(feature = "rayon"))]
{
($else_value)
}
}};
}
```
* A `rayon` feature flag is added and the `if_rayon!` macro is used everywhere `rayon` shows up.
An additional test run is added for the non-rayon code. This significantly slows down the CI job, so we may want to think through a better way to test this code. Perhaps the rayon can be isolated to a smaller module, and only that module tested.
> feat: add `rayon` feature flag

- crates/proof-of-sql/benches/scaffold/benchmark_accessor.rs
- crates/proof-of-sql/src/base/commitment/mod.rs
- crates/proof-of-sql/src/base/commitment/naive_commitment.rs
- crates/proof-of-sql/src/base/commitment/vec_commitment_ext.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_commitment.rs
Mentioned in #165 
-  Modified the `Commitment` trait's `compute_commitments` method to return `Vec<Self>` instead of mutating a pre-allocated slice.
- Updated implementations for `NaiveCommitment`, `DoryCommitment`, and `DynamicDoryCommitment` to align with the new trait definition.
Fixes #165 
/claim #165
> feat: refactor Commitment trait to return Vec<Self> instead of mutating slice

- crates/proof-of-sql/src/base/commitment/mod.rs
This change allows for custom column representations to be used in the commitment API by implementing a borrowing conversion to `CommittableColumn`. For my use case, I preferred doing this over implementing a conversion to `OwnedColumn` to avoid copying, and over implementing a conversion to `Column` to avoid invoking an allocator.
`CommittableColumn` is made public.
These changes do not affect functionality, which is verified by existing tests.
> feat: publicize CommittableColumn

- .github/workflows/lint-and-test.yml
- Cargo.toml
- crates/proof-of-sql-parser/src/lib.rs
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/src/base/commitment/mod.rs
- crates/proof-of-sql/src/lib.rs
- crates/proof-of-sql/src/sql/parse/query_expr_tests.rs
- crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs
We want `no_std` support.
* Added a `std` and `perf` feature to `proof-of-sql`.
* Made `proof-of-sql-parser` `no_std`.
* Updated dependency features to disable `std` usage where not needed.
* Added CI jobs to ensure these features always pass.
The one caveat is that lalrpop needs a patch while waiting on https://github.com/lalrpop/lalrpop/pull/953 in order to have true `no_std` support. To test `no_std` compatibility, we can build on a target that does not support `std`. There is a new CI job that targets `thumbv7em-none-eabi`. This fails without the lalrpop patch.
Once `lalrpop` cuts a release, we can simply bump the version and remove the patch in the CI.
Yes
> feat: add `std` feature and almost full `no_std` support.

- .github/workflows/lint-and-test.yml
- Cargo.toml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/src/tests/mod.rs
- crates/proof-of-sql/src/tests/sol_test.rs
- crates/proof-of-sql/src/tests/sol_test_util.rs
#166 disabled solidity tests due to instability in the forge repo.
* Added a new `ForgeScript` type to enable testing. This type only depends on the published version of `alloy-sol-types`, which should be stable enough for our purposes.
* Refactored the existing tests to use this instead.
* Updated the CI to run these tests.
Yes
> ci: reenable solidity tests

- Cargo.toml
This PR upgrades blitzar to add support for Send and Sync via a default impl on MsmHandle.
Upgrades blitzar to 3.3.0
existing tests pass
> chore: upgrade blitzar to 3.3.0 for send/sync on MsmHandle

- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_structure.rs
The GPU implementation of the dynamic Dory commitment computation requires a number of helper methods in the dynamic Dory structure. This PR implements methods that will be used by the GPU implementation.
- Add `index_from_row_and_column` method which is the inverse of `row_and_column_from_index` method. Given a `row` and `column` it will provide the `index` of the original data. The method also handles cases where `row` and `column` do not provide a valid `index`.
- Add `matrix_size` method which returns the width and height of the dynamic Dory matrix structure that will hold the given data.
- Made helper methods `const` for compile-time evaluation.
- Add temporary `#[allow(dead_code)]` to address `cargo clippy` warnings - these will be removed when the dynamic Dory commit computation is …
> feat: add helper methods to dynamic Dory structure (PROOF-919)

- .github/workflows/lint-and-test.yml
- Cargo.toml
Bump `lalrpop` to support https://github.com/lalrpop/lalrpop/pull/957
- Bump `lalrpop` to 0.22.0
- Remove patch from the no std check in CI
Yes
> feat: bump `lalrpop` to 0.22.0 and remove patch from the no std check in CI

- crates/proof-of-sql/src/base/polynomial/composite_polynomial.rs
- crates/proof-of-sql/src/base/polynomial/composite_polynomial_test.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/mod.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/proof_test.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/test_cases.rs
The tests we have for sumcheck do not cover as many edge cases as they should. This PR adds many more tests cases.
See the individual commits.
* Added CompositePolynomial::rand and `CompositePolynomial::hypercube_sum` - These two methods are useful for generating test cases for sumcheck.
* Added `sumcheck::test_cases` module that enumerates a bunch of test cases that we should be testing. These test cases are intended to be re-used. In particular, 
* Added a test for all of these test cases.
Yes
> test: improve sumcheck test coverage

- .github/workflows/check-approver.yaml
We want to ensure external contributions (e.g. from a fork) are always approved by Jay.
> ci: add check-approver workflow

- .github/workflows/check-approver.yaml
Instead of triggering on pull request events, we'll now trigger on review submissions. This will handle the case where an approval was not immediately triggering the workflow.
> ci: update check-approver to trigger on pull request review submission

- crates/proof-of-sql/src/base/commitment/column_bounds.rs
- crates/proof-of-sql/src/base/commitment/column_commitment_metadata.rs
- crates/proof-of-sql/src/base/commitment/column_commitments.rs
- crates/proof-of-sql/src/base/commitment/committable_column.rs
- crates/proof-of-sql/src/base/commitment/table_commitment.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/database/owned_table.rs
- crates/proof-of-sql/src/base/database/scalar_and_i256_conversions.rs
- crates/proof-of-sql/src/base/database/table_ref.rs
- crates/proof-of-sql/src/base/math/decimal.rs
- crates/proof-of-sql/src/lib.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_public_setup.rs
- crates/proof-of-sql/src/proof_primitive/dory/setup.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/proof.rs
- crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs
- crates/proof-of-sql/src/sql/postprocessing/order_by_postprocessing.rs
- crates/proof-of-sql/src/sql/postprocessing/owned_table_postprocessing.rs
- crates/proof-of-sql/src/sql/postprocessing/select_postprocessing.rs
- crates/proof-of-sql/src/sql/postprocessing/slice_postprocessing.rs
- crates/proof-of-sql/src/sql/proof/provable_query_result.rs
We have cargo clippy running in our CI in order to enforce code quality. In order to increase our standards, we should enable the clippy::pedantic lint group.
This PR fixes  `clippy::must_use_candidate` and `clippy::range_plus_one` warnings for `proof-of-sql` lib.
Yes. In order to test individual lints, we can use the following command:
`cargo clippy --lib -p proof-of-sql -- -W clippy::lint_name`
> chore: resolve `clippy::must_use_candidate` and `clippy::range_plus_one` lints in `proof-of-sql`

- .github/workflows/lint-and-test.yml
We have added `clippy::pedantic` support for the `proof-of-sql-parser` crate. Therefore, we're introducing a Clippy check in the CI to enforce the `clippy::pedantic` linter. At this time, we won't include pedantic in the `.toml` file since the `proof-of-sql` library doesn't support it yet.
> ci: add `clippy::pedantic` linter to `proof-of-sql-parser`

- crates/proof-of-sql/src/base/bit/bit_distribution.rs
- crates/proof-of-sql/src/base/commitment/column_commitments.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/column_operation.rs
- crates/proof-of-sql/src/base/database/expression_evaluation.rs
- crates/proof-of-sql/src/base/encode/scalar_varint.rs
- crates/proof-of-sql/src/base/encode/varint_trait.rs
- crates/proof-of-sql/src/base/math/decimal.rs
- crates/proof-of-sql/src/base/math/permutation.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar.rs
- crates/proof-of-sql/src/proof_primitive/dory/pack_scalars.rs
- crates/proof-of-sql/src/sql/parse/dyn_proof_expr_builder.rs
- crates/proof-of-sql/src/sql/proof/composite_polynomial_builder.rs
- crates/proof-of-sql/src/sql/proof/proof_builder.rs
- crates/proof-of-sql/src/sql/proof/provable_query_result.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/sumcheck_subpolynomial.rs
- crates/proof-of-sql/src/sql/proof_exprs/sign_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
We have cargo clippy running in our CI in order to enforce code quality. In order to increase our standards, we should enable the clippy::pedantic lint group.
This PR fixes `clippy::explicit_iter_loop`, `clippy::implicit_clone` and `clippy::uninlined_format_args` warnings for proof-of-sql lib.
Yes.
> chore: resolve `clippy::explicit_iter_loop`, `clippy::implicit_clone` and `clippy::uninlined_format_args` lints in `proof-of-sql`

- .github/workflows/lint-and-test.yml
Merge queues help improve merge velocity.
* The CI jobs now run on the merge queue
N/A
> ci: enable CI for merge queue

- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/column_operation.rs
- crates/proof-of-sql/src/lib.rs
- crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs
- crates/proof-of-sql/src/sql/proof/composite_polynomial_builder.rs
- crates/proof-of-sql/src/sql/proof_exprs/comparison_util.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
We have cargo clippy running in our CI in order to enforce code quality. In order to increase our standards, we should enable the clippy::pedantic lint group.
This PR fixes `clippy::similar_names`, `clippy::many_single_char_names` & `clippy::module_name_repetitions` warnings for proof-of-sql lib.
Currently I have completely allowed  `clippy::module_name_repetitions` lint as it appears to be too strict.
Yes
> chore: resolve `clippy::similar_names`, `clippy::many_single_char_names` & `clippy::module_name_repetitions`  lints in `proof-of-sql`

- crates/proof-of-sql/src/base/commitment/column_bounds.rs
- crates/proof-of-sql/src/base/commitment/committable_column.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/group_by_util.rs
- crates/proof-of-sql/src/base/database/literal_value.rs
- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/polynomial/multilinear_extension.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_commitment_helper_cpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/pack_scalars.rs
- crates/proof-of-sql/src/sql/proof/provable_query_result.rs
- crates/proof-of-sql/src/sql/proof/provable_result_column.rs
We have cargo clippy running in our CI in order to enforce code quality. In order to increase our standards, we should enable the clippy::pedantic lint group.
This PR fixes `clippy::match_same_arms` warnings for proof-of-sql lib.
Yes.
> chore: resolve `clippy::match_same_arms` lints in proof-of-sql

- .github/pull_request_template.md
- CONTRIBUTING.md
`CONTRIBUTING.md` is seriously out of date now that we are an open source project. Furthermore the PR template needs an example so that we can set adequate expectations for contribution.
- remove all outdated references
- improve sample `cargo test` command
- add references to code quality checks
- add `Getting Started` with Rust installation and repo forking guide
- improve the PR template by linking to `CONTRIBUTING.md` and add an example
N/A since there are no code changes.
> docs: update `CONTRIBUTING.md` and PR template

- CONTRIBUTING.md
- crates/proof-of-sql/README.md
Our contributing guidelines and README exclude people without Linux + GPU's from running the tests/code.
Documentation explaining how to disable Blitzar and/or GPU acceleration.
NA
> docs: add blitzar workaround

- crates/proof-of-sql/src/proof_primitive/dory/dory_compute_commitments_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_commitment_helper_cpu.rs
The dynamic Dory commitment computation does not currently handle empty columns as expected. This was uncovered after a test formatting error was discovered. Both the empty column case and formatting error are addressed.
- The empty column case is handled in the `dynamic_dory_commitment_helper_cpu` module. Tests for this function are in - https://github.com/spaceandtimelabs/sxt-proof-of-sql/pull/242
- Tests for empty Dory commitments are corrected.
Yes
> fix: dynamic Dory commitment computation should handle empty columns

- crates/proof-of-sql/src/proof_primitive/dory/public_parameters.rs
These implementations do not use any std functionality. The save_to_file and load_from_file utilities do, which remain behind the "std" feature.
Being able to serialize and deserialize public parameters will be important for some no_std use cases.
`#[cfg(feature = "std")]` has been removed from `ark-serialize` trait implementations on `PublicParameters`.
No. These changes do not affect existing functionality, which is verified by existing tests.
> feat: remove std requirement for ark-serialize implementations

- CONTRIBUTING.md
I was going through this project and tried to run the tests locally but they failed because my machine was missing `lld`, so i added it as an instruction under the "Install Rust" section in `Contributing.md`
Adds one line to `CONTRIBUTING.md` telling the reader to install `lld`
Ran the CI checks script but it keeps killing my terminal, but I am making the PR anyway since I don't think a simple doc change would break anything
> docs: Add lld as a pre-requisite to setup the dev environment

- crates/proof-of-sql/src/base/scalar/mont_scalar.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar_test.rs
`TryFrom<BigInt> for MontScalar<T>` is implemented improperly, and never overflows
The implementation is fixed.
Yes. Tests are added.
> fix: implement `TryFrom<BigInt> for MontScalar<T>` properly

- Cargo.toml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/src/lib.rs
- crates/proof-of-sql/src/utils/mod.rs
- crates/proof-of-sql/src/utils/parse.rs
> feat: add `find_bigdecimals`

- scripts/run_ci_checks.sh
The command `exit 1` is called if a failure occurs when executing the commands in the `scripts/run_ci_checks` shell script. The `exit 1` command closes the terminal in places like VSCode, the Ubuntu terminal, and Terminator. This makes debugging failures difficult since the tests results are not visible to the user.
- The `run_ci_checks.sh` shell script is updated to count the number of test failures when executing the commands and leave the terminal open after the script has run for users to see the test results.
Yes
> ci: the run_ci_checks shell script should not close the terminal if a failure occurs

- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/column_operation.rs
- crates/proof-of-sql/src/base/database/group_by_util.rs
- crates/proof-of-sql/src/base/math/decimal.rs
- crates/proof-of-sql/src/base/scalar/mod.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar_test.rs
- crates/proof-of-sql/src/base/scalar/scalar.rs
- crates/proof-of-sql/src/base/scalar/scalar_ext.rs
- crates/proof-of-sql/src/base/scalar/test_scalar.rs
- crates/proof-of-sql/src/base/scalar/test_scalar_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/inequality_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
Some helper code for `Scalar`s is scattered a bit. This PR clean this up.
* Moved signed_cmp to ScalarExt trait.
* Replaced scale_scalar with ScalarExt::pow10
Yes
> refactor!: add `ScalarExt`

- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor.rs
- crates/proof-of-sql/src/base/database/test_accessor.rs
The `test` feature is unwieldy and makes the repo difficult to use. This PR helps with this a bit.
The `test` feature no longer gates `OwnedTableTestAccessor`, which is helpful for examples and simple uses.
NA
> feat: expose `OwnedTableTestAccessor` without `test` feature

- crates/proof-of-sql/benches/README.md
- crates/proof-of-sql/benches/jaeger_benches.rs
- crates/proof-of-sql/src/proof_primitive/dory/public_parameters.rs
It is important to be able to run benchmarks on the newly implemented dynamic Dory evaluation proof. This PR introduces Jaeger benchmarks that will run the dynamic Dory evaluation proof.
- Jaeger benchmarks are introduced that measure the dynamic Dory evaluation proof time.
- To simplify calling benchmarks, the `test` flag is removed from Dory `public_parameters` module when creating random test values.
Yes
> bench: jaeger benchmarks should be able to run the dynamic Dory evaluation proof

- crates/proof-of-sql/src/proof_primitive/dory/public_parameters.rs
The Dory public parameters should be compatible between various choices of `max_nu`. Currently, this is not the case.
Reorganize the generation of `PublicParameters` so that `max_nu` only extends it, instead of otherwise modifying it.
NA
> feat!: make public_parameters extendable

- crates/proof-of-sql/src/proof_primitive/dory/blitzar_metadata_table.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_commitment_helper_gpu.rs
Currently the dynamic Dory commitment computation on the GPU includes zeros for all offset values. This means adding a single commit with a large offset will require a significant chunk of unnecessary memory. This PR handles offsets more efficiently truncating all zero rows of the dynamic Dory structure matrix when crating the Blitzar metadata tables.
- The `blitzar_metadata_tables` module now truncates rows of the dynamic Dory structure matrix that are fully contained in the offset.
- Tests are updated in the `blitzar_metadata_tables` module to test the new behavior.
- The `Gamma_2` value in the `dynamic_dory_commitment_helper_gpu` module now uses the offset.
Yes
> perf: dynamic Dory commitment computation on the GPU should efficiently handle the offset

- Cargo.toml
- crates/proof-of-sql/src/proof_primitive/dory/public_parameters.rs
- crates/proof-of-sql/src/proof_primitive/dory/setup.rs
This PR adds support for a conversion from pre-generated public parameters and a blitzar handle into a ProverSetup. This helps skip an expensive step to generate parameters and should significantly decrease the amount of time to load the parameters. It serves as a step towards file i/o for the parameters.
existing tests pass. a round trip test is forthcoming in a future PR.
> feat: proversetup fileio

- crates/proof-of-sql/src/proof_primitive/dory/setup.rs
- crates/proof-of-sql/src/proof_primitive/dory/setup_test.rs
Adds an accessor function for the blitzar MSM handle to allow for file loading of the handle
stated above
existing tests pass
> feat: accessor function for bliztar msm handle

- crates/proof-of-sql/src/base/database/arrow_schema_utility.rs
- crates/proof-of-sql/src/base/database/mod.rs
There are situations where we infer arrow schemas using the official arrow crate functions which will produce arrow schemas that are not fully posql compatible.
This patch adds a function to give us posql compatible arrow schemas: arrow_schema_utility::get_posql_compatible_schema()
Yes
> feat: add arrow_schema_utility

- .github/workflows/lint-and-test.yml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/examples/dog_breeds/dog_breeds.csv
- crates/proof-of-sql/examples/dog_breeds/main.rs
Add an additional dog_breeds example to help improve documentation.
dog_breeds example is added.
Yes.
```
Parsing the query: SELECT COUNT(*) AS total_breeds FROM breeds...
Done in 0.375095 ms.
Generating proof...Done in 37.559131 ms.
Verifying proof...Verified in 12.053492 ms.
Query Result:
Ok(OwnedTable { table: {Identifier { name: "total_breeds" }: BigInt([25])} })
Parsing the query: SELECT Name FROM breeds WHERE Size = 'Large'...
Done in 0.639886 ms.
Generating proof...Done in 71.741361 ms.
Verifying proof...Verified in 28.358727000000002 ms.
Query Result:
Ok(OwnedTable { table: {Identifier { name: "name" }: VarChar(["Labrador Retriever", "German Shepherd", "Bernese Mountain Dog", "Rottweiler", "Golden Retriever", "Great Dane", "Akita", "Doberman Pinscher", "Irish Setter", "Alaskan …
```
> feat: dog_breeds example

- .github/workflows/lint-and-test.yml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/examples/wood_types/main.rs
- crates/proof-of-sql/examples/wood_types/wood_types.csv
- crates/proof-of-sql/src/base/database/arrow_schema_utility.rs
- docs/SQLSyntaxSpecification.md
Add an additional wood_types example to help improve documentation.
wood_types example is added.
This patch includes a change to arrow_schema_utility::get_posql_compatible_schema to use a smaller precision and scale in order to allow for arithmetic on these columns (otherwise we will fail because we will overflow).
Yes.
```
Parsing the query: SELECT COUNT(*) AS total_wood_types FROM woods...
Done in 0.32695100000000005 ms.
Generating proof...Done in 29.766170000000002 ms.
Verifying proof...Verified in 13.525808 ms.
Query Result:
Ok(OwnedTable { table: {Identifier { name: "total_wood_types" }: BigInt([10])} })
Parsing the query: SELECT common_use, SUM(density) as total_density, COUNT(*) as wood_count FROM woods GROUP BY common_use ORDER BY total_density DESC...
Done in 0.591261 ms. …
```
> feat: wood_types example

- .github/workflows/lint-and-test.yml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/examples/dinosaurs/dinosaurs.csv
- crates/proof-of-sql/examples/dinosaurs/main.rs
Add an additional dinosaurs example to help improve documentation.
dinosaurs example is added.
Yes.
```
Parsing the query: SELECT COUNT(*) AS total_dinosaurs FROM dinosaurs...
Done in 0.33194799999999997 ms.
Generating proof...Done in 32.412333000000004 ms.
Verifying proof...Verified in 10.905069 ms.
Query Result:
Ok(OwnedTable { table: {Identifier { name: "total_dinosaurs" }: BigInt([10])} })
Parsing the query: SELECT name, weight_tons FROM dinosaurs WHERE diet = 'Carnivore' ORDER BY weight_tons DESC LIMIT 1...
Done in 0.482765 ms.
Generating proof...Done in 50.824058 ms.
Verifying proof...Verified in 22.844692 ms.
Query Result:
Ok(OwnedTable { table: {Identifier { name: "name" }: VarChar(["Spinosaurus"]), Identifier { name: "weight_tons" }: Decimal75(Precision(75), 30, …
```
> feat: dinosaurs example

- .github/workflows/lint-and-test.yml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/examples/sushi/fish.csv
- crates/proof-of-sql/examples/sushi/main.rs
Add sushi example to improve documentation.
+ added sushi example
Yes
```
Parsing the query: SELECT * FROM fish...
Done in 3.734125 ms.
Generating proof...Done in 155.35108400000001 ms.
Verifying proof...Verified in 47.697167 ms.
Query Result:
OwnedTable { table: {Identifier { name: "nameen" }: VarChar(["Tuna", "Tuna", "Tuna", "Bonito", "Yellowtail", "Salmon", "Sea Bream", "Sea Bass", "Mackerel", "Sardine", "Scallops", "Ark-shell clams"]), Identifier { name: "nameja" }: VarChar(["Maguro", "Maguro", "Maguro", "Katsuo", "Hamachi", "Salmon", "Tai", "Suzuki", "Aji", "Iwashi", "Hotate", "Akagai"]), Identifier { name: "kinden" }: VarChar(["Lean Red Meat", "Medium Fat Read Meat", "Fatty Red Meat", "Red Meat", "Red Meat", "White Fish", "White Fish", "White Fish", "Silver Skinned", "Silver …
```
> feat: add sushi example

- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_commitment_helper_cpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_structure.rs
In order for lightweight environments, without GPUs, to compute commitments, we should be able to compute commitments faster on a CPU.
The dynamic dory commitment computation now computes fewer Scalar Multiplications.
Also, rayon is leveraged for parallelism.
Yes.
> perf: make dynamic dory cpu commitment computation more efficient

- crates/proof-of-sql/src/sql/proof/proof_plan.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec_test.rs
An upstream crates needs to know what tables are being queried against from the proof plan.
`ProofPlan::get_table_references` is added
Yes
> feat: add `ProofPlan::get_table_references`

- crates/proof-of-sql/src/base/database/columnar_value.rs
- crates/proof-of-sql/src/base/database/mod.rs
We need to add `ColumnarValue` so that we can remove `table_length` from `ProofExpr::result_evaluate` which helps with `ProofPlan` composition.
- add `base::database::ColumnarValue `
Yes
> feat: add `base::database::ColumnarValue`

- crates/proof-of-sql/src/sql/proof_exprs/comparison_util.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
To prepare to remove `table_length` from `ProofExpr::result_evaluate` and return `ColumnarValue` we need to add operations on `ColumnarValue`.
- add comparison operations on `ColumnarValue`.
- add numerical operations on `ColumnarValue`.
Will be tested in a future PR.
> feat: add `ColumnarValue` operations

- .cargo/config.toml
- .github/workflows/lint-and-test.yml
The rustfmt config used in CI is tedious to type hence it is helpful to add it as an alias to `config.toml`.
- add `cargo f` and `cargo cl` aliases to `config.toml`
- remove fmt customization from CI to unify it
Yes
> ci: add to config.toml and unify fmt customization

- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/empty_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/mod.rs
The point of `EmptyExec` is to serve as a source `ProofPlan` (together with `TableExec` which I will add soon) so that composition of `ProofPlan`s is natural and so that we become more compatible with DataFusion.
Typical query using `EmptyExec`: `SELECT "I'm not from a table haha" as message` 
- add `EmptyExec`
N/A
> feat: add `EmptyExec`

- crates/proof-of-sql-parser/Cargo.toml
- crates/proof-of-sql-parser/src/lib.rs
- crates/proof-of-sql-parser/src/posql_time/unit.rs
- crates/proof-of-sql-parser/src/sqlparser.rs
In order to allow #235 to be done in time for JOIN-related integrations we need to get `proof-of-sql-parser` -> `sqlparser` adaptions done. Large parts of the work going forward can then become more manageable.
- add `sqlparser.rs` with adaptations
Yes
> feat: add basic sqlparser adaptions

- crates/proof-of-sql/src/base/database/column_operation_error.rs
- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/base/database/owned_column_operation.rs
- crates/proof-of-sql/src/base/database/slice_decimal_operation.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/proof_exprs/add_subtract_expr.rs
This change is made to simplify column operations partly in order to simplify `owned_column_operation.rs` and partly in preparation for the new version of provable arithmetic expressions.
- replace `BinaryOp` and `UnaryOp` in `ColumnOperationError` with strings
> refactor!: remove parser structs from `ColumnOperationError`

- Cargo.toml
- crates/proof-of-sql/src/base/polynomial/evaluation_vector_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_helper.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_standard_basis_helper.rs
The Arkworks project have released a new version of their crates - `0.5.0`. This PR updates the Arkworks crates. Additionally it upgrades the `blitzar` crate to a version that supports the updated Arkworks crate.
Benchmarks indicate no impact to performance is expected with the upgrade.
- Arkworks crates are updated to version `0.5.0`
- The `blitzar` crate is updated to version `4.0.0`
- All build errors related to the update are addressed
Yes by running tests and benchmarks.
> feat!: upgrade Arkworks and Blitzar crates to latest versions

- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/table.rs
- crates/proof-of-sql/src/base/database/table_test.rs
- crates/proof-of-sql/src/base/database/table_test_accessor.rs
- crates/proof-of-sql/src/base/database/table_test_accessor_test.rs
- crates/proof-of-sql/src/base/database/table_utility.rs
In order to make `ProofPlan`s composable it is helpful to add `Table` which will replace `DataAccessor` in `ProofExpr`. In order to add tests that aren't too tedious it is necessary to add table utilities analogous to owned table ones.
- add `Table`
- add table utilities in `table_utility.rs`
- add `TableTestAccessor
Yes.
> feat: add `Table` && `TableTestAccessor` && table utilities

- crates/proof-of-sql/src/base/database/expression_evaluation.rs
- crates/proof-of-sql/src/sql/parse/dyn_proof_expr_builder.rs
- crates/proof-of-sql/src/sql/parse/error.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
This PR addresses the need to replace the `proof_of_sql_parser::intermediate_ast::UnaryOp` with the `sqlparser::ast::UnaryOp` in the `proof-of-sql` crate as part of a larger transition toward integrating the `sqlparser` .
This change is a subtask of issue #235, with the main goal of streamlining the repository by switching to the `sqlparser` crate and gradually replacing intermediary constructs like `proof_of_sql_parser::intermediate_ast` with `sqlparser::ast`.
- All instances of `proof_of_sql_parser::intermediate_ast::UnaryOp` have been replaced with `sqlparser::ast::UnaryOp`
-  Every usage of `UnaryOp` has been updated to maintain the …
> refactor!:  `proof_of_sql_parser::intermediate_ast::UnaryOp` with `sqlparser::ast::UnaryOp` in the proof-of-sql crate

- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/test_accessor.rs
- crates/proof-of-sql/src/sql/proof/proof_plan.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
Since I had auto-merge on NITs didn't get addressed. I promised to file a PR to resolve them today and hence I do now.
- remove `UnimplementedTestAccessor` which is no longer used
- remove `ProofPlan::is_empty` which is only used in `VerifiableQueryResult` by inlining
- make code more compact in `query_proof_test.rs` and `verifiable_query_result_test.rs`
> fix!: address NITs in PR #361

- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/utils/commitment-utility/main.rs
- crates/proof-of-sql/utils/generate-parameters/round_trip_test.rs
It is nice for people to be able to inspect serialized commitments and table metadata from a commitments file.
- add `commitment-utility`
It runs.
> feat: add `commitment-utility`

- crates/proof-of-sql/src/base/map.rs
- crates/proof-of-sql/src/sql/proof/proof_plan.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof/verification_builder.rs
- crates/proof-of-sql/src/sql/proof/verification_builder_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/add_subtract_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/aggregate_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/and_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/column_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/inequality_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/literal_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/multiply_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/not_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/or_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/sign_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/sign_expr_test.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/empty_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
Implementations of `verifier_evaluate` no longer rely on the commitment type.
All uses of a `Commitment` generic are removed from `verifier_evaluate`. See individual commits in this PR.
> refactor: remove `Commitment` references from `verifier_evaluate`

- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/database/owned_table.rs
`OwnedTable` Serialization is needed upstream.
`serde` is derived for both `OwnedTable` and `OwnedColumn`.
NA
> feat: derive serde for `OwnedTable`/`OwnedColumn`

- crates/proof-of-sql/src/base/map.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/mod.rs
- crates/proof-of-sql/src/sql/proof_plans/table_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/table_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/test_utility.rs
`TableExec` is to be the most common source `ProofPlan` when all `ProofPlan`s become composable. Basically all it does is reading from a table. I plan to remove table reading functionalities from all other `ProofPlan`s soon.
- add `TableExec`
N/A
> feat: add `TableExec`

- crates/proof-of-sql/src/base/database/table.rs
- crates/proof-of-sql/src/base/database/table_utility.rs
- crates/proof-of-sql/src/sql/proof/proof_plan.rs
- crates/proof-of-sql/src/sql/proof/provable_query_result.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/empty_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/table_exec.rs
To make `ProofPlan`s composable it is more natural for us to return `Table`s in `result_evaluate` and `final_round_evaluate` in `ProofPlan`.
- replace output of `result_evaluate` and `final_round_evaluate` of `ProofPlan` with `Table`
- add `Table::columns`, `ProvableQueryResult::new_from_table` to simplify the code
Yes.
> refactor!: replace output of `result_evaluate` and `final_round_evaluate` of `ProofPlan` with `Table`

- crates/proof-of-sql/benches/README.md
- crates/proof-of-sql/benches/jaeger_benches.rs
The latest Jaeger all-in-one Docker image, version `1.63.0`, has a bug. After running benchmarks you cannot view the output from the UI - https://github.com/jaegertracing/jaeger/issues/6200. This PR updates the documents referencing the Jaeger all-in-one image version to point to the latest working version - `1.62.0`.
- Docs are updated to specify the latest working Jaeger all-in-one Docker image version - `1.62.0`.
Yes
> docs: specify the jaeger all-in-one docker image version

- crates/proof-of-sql/src/base/database/accessor.rs
- crates/proof-of-sql/src/sql/proof/proof_plan.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/empty_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/table_exec.rs
This is the next step in making `ProofPlan` composable. Let's centralize fetching of table maps using `DataAccessor` to `query_proof.rs`.
See above.
Existing tests do pass.
> refactor!: replace `DataAccessor` in `ProofPlan` with `IndexMap`

- .github/workflows/lint-and-test.yml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/README.md
- crates/proof-of-sql/examples/hello_world/README.md
- crates/proof-of-sql/examples/hello_world/main.rs
- crates/proof-of-sql/examples/posql_db/README.md
- crates/proof-of-sql/examples/posql_db/main.rs
Closes #383 
Tests cannot currently be run on alternative architectures because they
enable the blitzar dependency.
However, this is not strictly necessary, because all tests using blitzar
are behind the blitzar feature flag.
So, this removes blitzar as a dev dependency, as well as making a couple related changes to the README and CI.
- fix: remove blitzar as a dev-dependency
- docs: simplify README cargo test command excluding blitzar feature
- ci: check all targets in feature-specific checks of Check package job
These changes do not change existing functionality, which is verified by existing tests.
> fix: remove blitzar as a dev-dependency

- crates/proof-of-sql/src/sql/proof/final_round_builder.rs
- crates/proof-of-sql/src/sql/proof/final_round_builder_test.rs
- crates/proof-of-sql/src/sql/proof/first_round_builder.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/inequality_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/sign_expr_test.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec_test.rs
Currently there are still places where `FinalRoundBuilder::table_length` is used in `ProofExpr` which is wrong when we start composing `ProofPlan`s. Moreover in cases where a `ProofPlan` causes its output table to be longer than any of the input tables (e.g. joins and unions) we need to bump the `max_row_num`.
- remove `table_length` from `FinalRoundBuilder`
- add `range_length` to `FirstRoundBuilder` to track the max table length in a query (updates are NOT to be applied to any `ProofPlan` that can not cause its output table to have more rows than any of its inputs such as filter and projection)
- update `range_length` after …
> refactor!: move `table_length` to `FirstRoundBuilder`

- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/column_operation_error.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/table.rs
- crates/proof-of-sql/src/base/database/table_operation_error.rs
- crates/proof-of-sql/src/base/database/union_util.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
In order to support `UnionExec` we need to add union utils and have them tested.
- rename `Column::as_scalar` to `Column::into_scalar` since `as_` methods such as `as_boolean` serve different purposes
- add `as_` method for every enum variant in `Column`
- add `union_util.rs` which contains column and table unioning.
Will be.
> feat: add union utils

- crates/proof-of-sql/src/base/database/join_util.rs
- crates/proof-of-sql/src/base/database/mod.rs
Now let's add the simplest form of join without adding its proof yet, that is, the cross join. Cross joins are not that common but they are easier to implement than inner joins since they don't require sorting or matching.
- add `cross_join`
Yes.
> feat: add `cross_join`

- crates/proof-of-sql/benches/scaffold/mod.rs
- crates/proof-of-sql/examples/albums/main.rs
- crates/proof-of-sql/examples/avocado-prices/main.rs
- crates/proof-of-sql/examples/books/main.rs
- crates/proof-of-sql/examples/brands/main.rs
- crates/proof-of-sql/examples/census/main.rs
- crates/proof-of-sql/examples/countries/main.rs
- crates/proof-of-sql/examples/dinosaurs/main.rs
- crates/proof-of-sql/examples/dog_breeds/main.rs
- crates/proof-of-sql/examples/hello_world/main.rs
- crates/proof-of-sql/examples/plastics/main.rs
- crates/proof-of-sql/examples/programming_books/main.rs
- crates/proof-of-sql/examples/rockets/main.rs
- crates/proof-of-sql/examples/space/main.rs
- crates/proof-of-sql/examples/stocks/main.rs
- crates/proof-of-sql/examples/sushi/main.rs
- crates/proof-of-sql/examples/tech_gadget_prices/main.rs
- crates/proof-of-sql/examples/vehicles/main.rs
- crates/proof-of-sql/examples/wood_types/main.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test_utility.rs
- crates/proof-of-sql/tests/integration_tests.rs
- crates/proof-of-sql/tests/timestamp_integration_tests.rs
`VerifiableQueryResult::verify` is more complex than it needs to be
See individual commit messages.
> refactor!: simplify VerifiableQueryResult::verify

- crates/proof-of-sql/src/base/database/order_by_util.rs
- crates/proof-of-sql/src/base/database/order_by_util_test.rs
- crates/proof-of-sql/src/base/database/table_operation_error.rs
We need to add this function in order to perform sort-merge joins.
See title.
Yes.
> feat: add `compare_single_row_of_tables`

- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
We need to make sure we use the correct table lengths in filter since that's why #379 failed till today. Thanks @JayWhite2357 for spotting the problem and providing the fix!
- make sure we use a col with 1s up to input length as opposed to an all 1 column in filter for `c_fold * c_star - input_ones = 0` constraint
Existing tests do pass. Moreover slicing tests pass.
> fix!: fix filter so that filter-filter and filter-slice compositions can work

- crates/proof-of-sql/src/base/database/owned_table.rs
- crates/proof-of-sql/src/base/map.rs
Conversions from `Table` to `OwnedTable` will be useful in future PRs.
`From<&Table>` and `From<Table>` are implemented for `OwnedTable`.
Yes
> chore: add conversion from `Table` to `OwnedTable`.

- crates/proof-of-sql/examples/albums/main.rs
- crates/proof-of-sql/examples/avocado-prices/main.rs
- crates/proof-of-sql/examples/books/main.rs
- crates/proof-of-sql/examples/brands/main.rs
- crates/proof-of-sql/examples/census/main.rs
- crates/proof-of-sql/examples/countries/main.rs
- crates/proof-of-sql/examples/dinosaurs/main.rs
- crates/proof-of-sql/examples/dog_breeds/main.rs
- crates/proof-of-sql/examples/hello_world/main.rs
- crates/proof-of-sql/examples/plastics/main.rs
- crates/proof-of-sql/examples/programming_books/main.rs
- crates/proof-of-sql/examples/rockets/main.rs
- crates/proof-of-sql/examples/space/main.rs
- crates/proof-of-sql/examples/stocks/main.rs
- crates/proof-of-sql/examples/sushi/main.rs
- crates/proof-of-sql/examples/tech_gadget_prices/main.rs
- crates/proof-of-sql/examples/vehicles/main.rs
- crates/proof-of-sql/examples/wood_types/main.rs
- crates/proof-of-sql/src/sql/proof/mod.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs
- crates/proof-of-sql/tests/integration_tests.rs
- crates/proof-of-sql/tests/timestamp_integration_tests.rs
`QueryProof` exposes uneeded internals and is wrapped by `VerifiableQueryResult`, which should be used instead
See individual commits
This PR is mostly updating tests/examples.
> refactor!: make `QueryProof` private in favor of `VerifiableQueryResult`

- crates/proof-of-sql/src/base/proof/error.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/mod.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/test_utility.rs
- The following upstream PRs have been merged:
This PR replaces #121 and is designed to test whether our `ProofPlan`s are truly composable now.
- add `SliceExec`.
Yes.
> feat: add `SliceExec`

- crates/proof-of-sql/src/sql/proof/first_round_builder.rs
- crates/proof-of-sql/src/sql/proof/proof_plan.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof_plans/empty_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/table_exec.rs
We should have obvious correspondence between how one eval lengths are produced and consumed just like how we handle intermediate MLEs.
- move one eval lengths from `ProofPlan::first_round_builder` output to `FirstRoundBuilder`
Yes.
> refactor!: move one eval lengths from `ProofPlan::first_round_evaluate` output to `FirstRoundBuilder`

- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
This PR is partly the equivalent of #401 for `GroupbyExec`. Moreover we should move the temporary `GroupByExec` top level restriction to `GroupByExec` itself so that we don't have to keep it everywhere.
- Replace blanket 1 columns with columns with 1 up to input length in `GroupByExec`.
- Move `GroupByExec` composition restriction to `GroupByExec` itself.
> fix!: fix `GroupByExec` input length in proof && move `GroupByExec` top level restriction to `GroupByExec` itself

- crates/proof-of-sql/src/base/database/column_index_operation.rs
- crates/proof-of-sql/src/base/database/column_operation_error.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/slice_operation.rs
In sort-merge joins we need to be able to apply columns to possibly repetitive indexes. Hence let's add this before actually adding `sort_merge_join`.
- add `ColumnOperationError::IndexOutOfBounds`.
- add `apply_slice_to_indexes` in `slice_operation.rs`.
- add `IndexOp` and `ApplyIndexOp` to apply the new op to `Column`s.
Yes.
> feat: add `column_index_operation`

- crates/proof-of-sql/benches/scaffold/querys.rs
- crates/proof-of-sql/benches/scaffold/random_util.rs
The Jaeger benchmarks only measure a small number of queries with a limited amount of column types.. This PR expands the benchmarks to include more queries over most column types.
The `Decimal75` and `TimestampTZ` column types are still not supported in the benchmarks `random_util` module. They are not used in the new queries.
- The `random_util` module is expanded to support most column types.
- Additional queries are added which measure supported SQL functions inside the Jaeger benchmarks.
- The arithmetic query is updated to produce a smaller output table.
Yes.
> bench: add more queries to jaeger benches

- crates/proof-of-sql/src/sql/proof_plans/demo_mock_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/mod.rs
In order to test proof functionality, it can be helpful to create a mock `ProofPlan`. This PR include boilerplate code demonstrating how to do this.
See rationale.
Yes.
> test: add DemoMockPlan

- crates/proof-of-sql-parser/src/posql_time/timestamp.rs
- crates/proof-of-sql-parser/src/posql_time/timezone.rs
- crates/proof-of-sql/benches/bench_append_rows.rs
- crates/proof-of-sql/src/base/arrow/arrow_array_to_column_conversion.rs
- crates/proof-of-sql/src/base/commitment/column_bounds.rs
- crates/proof-of-sql/src/base/commitment/column_commitment_metadata.rs
- crates/proof-of-sql/src/base/commitment/committable_column.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/expression_evaluation_test.rs
- crates/proof-of-sql/src/base/database/owned_table.rs
- crates/proof-of-sql/src/base/database/owned_table_test.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor_test.rs
- crates/proof-of-sql/src/base/database/owned_table_utility.rs
- crates/proof-of-sql/src/base/database/table_test.rs
- crates/proof-of-sql/src/base/database/table_test_accessor_test.rs
- crates/proof-of-sql/src/base/database/table_utility.rs
- crates/proof-of-sql/src/proof_primitive/dory/blitzar_metadata_table.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_compute_commitments_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_compute_commitments_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/pack_scalars.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/parse/where_expr_builder_tests.rs
- crates/proof-of-sql/src/sql/proof_exprs/comparison_util.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/inequality_expr_test.rs
- crates/proof-of-sql/tests/timestamp_integration_tests.rs
The `PoSQLTimeZone` type has multiple representations for the same value, leading to complex upstream usage.
See the commit messages.
Yes, by existing, refactored, tests.
> fix!: normalize posqltimezone

- crates/proof-of-sql/src/base/commitment/mod.rs
- crates/proof-of-sql/src/base/commitment/naive_commitment.rs
- crates/proof-of-sql/src/base/proof/transcript.rs
- crates/proof-of-sql/src/base/proof/transcript_core.rs
- crates/proof-of-sql/src/base/proof/transcript_core_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_commitment.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
Serde is not easily portable to other languages, Solidity in particular. This is part of an effort to remove the dependency on serde _within_ proof verification.
* `Commitment::append_to_transcript` is added and implemented. This is leveraged to append the commitments to the transcript instead of always using postcard/serde.
* `Transcript::extend_as_le` is added and implemented to facilitate this.
Yes
> refactor!: remove commitment serialization from proof creation

- crates/proof-of-sql/src/base/polynomial/composite_polynomial.rs
- crates/proof-of-sql/src/base/polynomial/mod.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/proof.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/proof_test.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
`CompositePolynomialInfo` is used in 2 test and one other place. Removing it simplifies the verifier code. This is especially pertinent to the Solidity port.
See commits.
NA
> refactor: remove `CompositePolynomialInfo`

- crates/proof-of-sql-parser/src/error.rs
> docs: Cannot parse

- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/database/owned_column_error.rs
- crates/proof-of-sql/src/base/database/owned_table.rs
- crates/proof-of-sql/src/base/proof/error.rs
- crates/proof-of-sql/src/base/proof/transcript.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/query_result.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test_utility.rs
`postcard` does not port well to other language (e.g. Solidity). So, we need a simpler way to use the transcript.
See the individual commits.
* chore: add and implement `Transcript::extend_as_be_from_refs`
* chore: add `OwnedColumn::try_coerce_scalar_to_numeric`
* chore: add `OwnedTable::try_coerce_with_fields`
* chore: `impl From<TableCoercionError> for QueryError`
* chore: add `extend_transcript_with_owned_table` method
* refactor!: use `OwnedTable` to serialize onto transcript - This is the primary commit, and the motivation behind the others
Yes
> refactor!: make result serialization Solidity compatible

- crates/proof-of-sql/src/proof_primitive/sumcheck/mod.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/proof.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/proof_test.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/prover_round.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/prover_state.rs
- crates/proof-of-sql/src/sql/proof/final_round_builder.rs
- crates/proof-of-sql/src/sql/proof/final_round_builder_test.rs
- crates/proof-of-sql/src/sql/proof/make_sumcheck_polynomial.rs
- crates/proof-of-sql/src/sql/proof/make_sumcheck_state.rs
- crates/proof-of-sql/src/sql/proof/mod.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/sumcheck_subpolynomial.rs
- crates/proof-of-sql/src/sql/proof/verification_builder.rs
- crates/proof-of-sql/src/sql/proof/verification_builder_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/and_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/multiply_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/or_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/sign_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
The sumcheck implementation uses memory inefficiently. This is primarily due to unneeded cloning during the `ProverState` creation. This PR does some setup work for a followup PR that will solve this.
There are several small changes in this PR that are relatively disconnected.
A main overarching goal is the creation of the `make_sumcheck_prover_state` function.
In the next PR, this will be refactored to directly create the `ProverState`.
Yes
> refactor: setup for sumcheck memory usage reduction

- crates/proof-of-sql/src/base/polynomial/multilinear_extension.rs
- crates/proof-of-sql/src/base/polynomial/multilinear_extension_test.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/prover_state.rs
- crates/proof-of-sql/src/sql/proof/composite_polynomial_builder.rs
- crates/proof-of-sql/src/sql/proof/sumcheck_subpolynomial.rs
In `Bumpalo` if we allocate a non-empty slice and then an empty one they have the same positions hence it is necessary to differentiate between them by adding the slice length to the identifier.
See above.
Yes.
> fix: `MultilinearExtension::id` uniqueness

- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/table_evaluation.rs
- crates/proof-of-sql/src/base/database/union_util.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/mod.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/test_utility.rs
- crates/proof-of-sql/src/sql/proof_plans/union_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/union_exec_test.rs
- The following upstream PRs have been approved and merged:
We need to add support for `UNION ALL`.
- add `UnionExec`
- add some code to simplify debugging of sumchecks
Yes.
> feat: add `UnionExec`

- crates/proof-of-sql/src/base/commitment/commitment_evaluation_proof.rs
- crates/proof-of-sql/src/base/commitment/naive_evaluation_proof.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_evaluation_proof.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_commitment_evaluation_proof.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof/verification_builder.rs
- crates/proof-of-sql/src/sql/proof/verification_builder_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/and_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/multiply_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/or_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/sign_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/sign_expr_test.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/union_exec.rs
The `VerificationBuilder` should be simplified for easier porting to Solidity.
See individual commits.
Yes, by existing code.
> refactor: simplify into `consume_mle_evaluations`

- crates/proof-of-sql/src/proof_primitive/dory/blitzar_metadata_table.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_commitment_helper_gpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_compute_commitments_test.rs
The dynamic Dory commitment computation on the GPU will try to divide by zero if it is provided an empty commitable column vector. This PR fixes the empty committable column vector case.
- The `dynamic_dory_commitment_helper_gpu` and `blitzar_metadata_tables` modules handle empty committable column vectors.
- Tests are added for empty committable column cases.
Yes
> fix: dynamic dory commitment GPU computation should handle empty committable columns

- crates/proof-of-sql/src/evm_compatibility/dyn_proof_plan_serializer/constants.rs
- crates/proof-of-sql/src/evm_compatibility/dyn_proof_plan_serializer/error.rs
- crates/proof-of-sql/src/evm_compatibility/dyn_proof_plan_serializer/mod.rs
- crates/proof-of-sql/src/evm_compatibility/dyn_proof_plan_serializer/serialize_proof_expr.rs
- crates/proof-of-sql/src/evm_compatibility/dyn_proof_plan_serializer/serialize_proof_plan.rs
- crates/proof-of-sql/src/evm_compatibility/dyn_proof_plan_serializer/serializer.rs
- crates/proof-of-sql/src/evm_compatibility/mod.rs
- crates/proof-of-sql/src/evm_compatibility/primitive_serialize_ext.rs
- crates/proof-of-sql/src/evm_compatibility/serialize_query_expr.rs
- crates/proof-of-sql/src/lib.rs
- crates/proof-of-sql/src/sql/proof/proof_plan.rs
- crates/proof-of-sql/src/sql/proof_exprs/column_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/literal_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/table_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/empty_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/table_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/union_exec.rs
We need Solidity to be able to read Proof Plans.
An initial implementation of serialization for Proof Plan is added.
Yes
> feat: EVM compatible proof plan serialization 

- crates/proof-of-sql/src/base/mod.rs
- crates/proof-of-sql/src/base/sqlparser.rs
- crates/proof-of-sql/src/sql/parse/where_expr_builder_tests.rs
- crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs
- crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing_test.rs
- crates/proof-of-sql/src/sql/postprocessing/test_utility.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
This change simplifies the codebase since `proof_of_sql::base::sqlparser::ident` only does one thing which is to call `From<&str>` on `Ident`. Let's simplify the codebase here.
See title.
Yes.
> refactor: remove `base::sqlparser::ident` since `into()` is simpler

- crates/proof-of-sql/README.md
- crates/proof-of-sql/benches/scaffold/random_util.rs
- crates/proof-of-sql/examples/hello_world/README.md
- crates/proof-of-sql/examples/posql_db/main.rs
- crates/proof-of-sql/src/base/arrow/owned_and_arrow_conversions.rs
- crates/proof-of-sql/src/base/arrow/record_batch_conversion.rs
- crates/proof-of-sql/src/base/commitment/column_commitment_metadata_map.rs
- crates/proof-of-sql/src/base/commitment/column_commitments.rs
- crates/proof-of-sql/src/base/commitment/mod.rs
- crates/proof-of-sql/src/base/commitment/table_commitment.rs
- crates/proof-of-sql/src/base/database/owned_table.rs
- crates/proof-of-sql/src/base/database/owned_table_utility.rs
- crates/proof-of-sql/src/base/database/table.rs
- crates/proof-of-sql/src/base/database/table_utility.rs
- crates/proof-of-sql/src/sql/parse/query_expr_tests.rs
- crates/proof-of-sql/src/sql/postprocessing/error.rs
- crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs
- crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/test_utility.rs
To update docs to reflect the migration of Identifier -> Ident
- Updated docs in the proof-of-sql crate with Ident
Part of  #235
> refactor!: identifier to ident and update docs

- .github/workflows/lint-and-test.yml
- .gitignore
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/sol_src/base/LagrangeBasisEvaluation.sol
- crates/proof-of-sql/sol_src/tests/TestYulImport.t.psol
- crates/proof-of-sql/src/base/polynomial/lagrange_basis_evaluation.rs
- crates/proof-of-sql/utils/yul-preprocessor/main.rs
In order to port the verifier to Solidity, we need to write some code in Yul.
Simplified the existing Rust lagrange basis evaluation.
Added a YUL port.
Added some tooling around YUL code.
Yes
> feat: yul lagrange basis evaluation

- crates/proof-of-sql/src/base/database/join_util.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/table_operation_error.rs
- The following upstream PRs have been approved and merged:
This PR adds the actual sort-merge join process which completes a part of #394.
- add `sort_merge_join`.
Yes.
> feat: add `sort_merge_join`

- crates/proof-of-sql-parser/src/posql_time/error.rs
If do not replace the description for UnsupportedPrecision, both ParsingError and UnsupportedPrecision will display the same error message.
Updated the #[snafu(display(...))] attribute for the UnsupportedPrecision variant to provide a more specific error message.
The same error message will be used for different types of errors, making it difficult to understand the specific cause of the failure. When analyzing errors, it will be difficult to determine which specific error occurred — a general parsing issue or specifically an unsupported precision.
N/A since it is message-only
> fix: clarify error message for UnsupportedPrecision

- Cargo.toml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/src/base/scalar/scalar_ext.rs
- crates/proof-of-sql/src/base/scalar/test_scalar_test.rs
There is a need for conversions between `Scalar`s and `U256`, so there is not a need to use limbs (`[u64; 4]`).
There will be two new functions for converting a `Scalar` to `U256` and vice versa, allowing wrapping.
These functions are tested using `TestScalar`.
> feat: u256 conversions

- crates/proof-of-sql/src/sql/proof/final_round_builder.rs
- crates/proof-of-sql/src/sql/proof/final_round_builder_test.rs
- crates/proof-of-sql/src/sql/proof/verification_builder.rs
- crates/proof-of-sql/src/sql/proof/verification_builder_test.rs
- crates/proof-of-sql/src/sql/proof_gadgets/range_check.rs
- crates/proof-of-sql/src/sql/proof_gadgets/sign_expr_test.rs
Currently, `post_result_challenges` is treated as a stack instead of a queue. For the EVM verifier, it is simpler to work with the challenges as a queue.
`VecDeque` and `pop_front` is used instead of `Vec` and `pop` respectively for the `post_result_challenges`.
> refactor!: reverse `post_result_challenges` consumption

- crates/proof-of-sql/src/base/arrow/scalar_and_i256_conversions.rs
- crates/proof-of-sql/src/base/commitment/committable_column.rs
- crates/proof-of-sql/src/base/database/owned_table_utility.rs
- crates/proof-of-sql/src/base/database/table_utility.rs
- crates/proof-of-sql/src/base/encode/scalar_varint.rs
- crates/proof-of-sql/src/base/encode/u256.rs
- crates/proof-of-sql/src/base/encode/varint_trait_test.rs
- crates/proof-of-sql/src/base/polynomial/interpolate.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar.rs
- crates/proof-of-sql/src/base/scalar/test_scalar.rs
- crates/proof-of-sql/src/base/slice_ops/batch_inverse.rs
- crates/proof-of-sql/src/proof_primitive/dory/pack_scalars.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/prover_round.rs
- crates/proof-of-sql/src/sql/parse/query_context.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/postprocessing/mod.rs
- crates/proof-of-sql/src/sql/postprocessing/test_utility.rs
- crates/proof-of-sql/src/sql/proof/result_element_serialization.rs
- crates/proof-of-sql/src/sql/proof_gadgets/mod.rs
- crates/proof-of-sql/src/sql/proof_gadgets/range_check.rs
- crates/proof-of-sql/src/sql/proof_gadgets/range_check_test.rs
- crates/proof-of-sql/src/sql/proof_plans/fold_util.rs
- crates/proof-of-sql/tests/decimal_integration_tests.rs
- crates/proof-of-sql/tests/integration_tests.rs
- crates/proof-of-sql/tests/timestamp_integration_tests.rs
- crates/proof-of-sql/utils/commitment-utility/main.rs
- rust-toolchain.toml
udeps stop working after an update. Hence let's bump Rust to get CI to work again.
- bump Rust to 1.84.0
- clippy fixes
> fix: bump Rust to 1.84.0 and related fixes

- crates/proof-of-sql-parser/src/posql_time/timestamp.rs
- crates/proof-of-sql-parser/src/utility.rs
Some comments don't really line up with the code hence I fixed it.
See above.
N/A
> fix: mismatch between comments and code regarding data types

- crates/proof-of-sql/src/base/commitment/mod.rs
- crates/proof-of-sql/src/base/commitment/naive_commitment.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_commitment.rs
- crates/proof-of-sql/src/proof_primitive/hyperkzg.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
We will want to serialize commitments in a manner compatible with the transcript. This facilitates doing this without duplicating code.
`Commitment::append_to_transcript` is removed and `to_transcript_bytes` is added instead. Usage is replaced as well.
Yes.
> refactor: replace `Commitment::append_to_transcript` with `to_transcript_bytes`

- crates/proof-of-sql/src/base/proof/transcript_core.rs
- crates/proof-of-sql/src/base/proof/transcript_core_test.rs
- crates/proof-of-sql/src/base/scalar/mod.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar_test.rs
- crates/proof-of-sql/src/base/scalar/scalar.rs
- crates/proof-of-sql/src/base/scalar/scalar_ext.rs
- crates/proof-of-sql/src/base/scalar/test_scalar.rs
- crates/proof-of-sql/src/base/scalar/test_scalar_test.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment.rs
- crates/proof-of-sql/src/proof_primitive/hyperkzg.rs
The current mechanism for drawing a challenge is a bit opaque. This simplifies it.
When drawing a challenge from the transcript, it is 32 bytes long. Instead of using `[u64; 4]` to coerce it into a `Scalar`, it is more straightforward to simply drop the first few bits. This can be accomplished by masking the challenged by a `CHALLENGE_MASK` before converting to a `Scalar`.
Additionally, this PR updates the `Scalar` implementations so that we have a blanket implementation of `impl<T> Scalar for MontScalar<T>`. This removes the need to manually figure out the constants for each Scalar type.
Yes.
> refactor!: update scalar challenges to use mask

- crates/proof-of-sql/src/sql/proof/query_proof.rs
The source of the data/commitments for referenced columns is different from final round mles. They are also handle very differently. So, they should be separated in the proof as well.
See rationale and title.
> refactor: separate column evaluations from final round mle evaluations

- crates/proof-of-sql/src/base/polynomial/lagrange_basis_evaluation.rs
- crates/proof-of-sql/src/base/polynomial/lagrange_basis_evaluation_test.rs
- crates/proof-of-sql/src/base/polynomial/mod.rs
- crates/proof-of-sql/src/base/scalar/scalar.rs
For joins it is necessary to have not only one evaluations but also evaluations of rho = (0, 1, 2, \cdots, n-1) vectors. Hence we need to add them to our proofs.
- an algorithm to compute rho evaluations
Yes.
> feat: add rho eval

- crates/proof-of-sql/src/base/scalar/scalar_ext.rs
- crates/proof-of-sql/src/evm_compatibility/primitive_serialize_ext.rs
> fix: code comments errors 

- crates/proof-of-sql/examples/posql_db/README.md
- crates/proof-of-sql/src/base/proof/transcript_core.rs
Hope helps! 
Since we added `HashJoinExec` in #323 it has been possible to do provable inner joins. However performance is not satisfactory in some cases. Hence we need to fix the problem by implement `NestedLoopJoinExec` and speed up the code
for `HashJoinExec`.
-->
While reviewing the docs found errors in the comments to the code.
Example:
- Add `NestedLoopJoinExec`.
- Speed up `HashJoinExec`.
- Route joins to `NestedLoopJoinExec` if the outer input is sufficiently small.
-->
> fix: comments errors in codebase

- crates/proof-of-sql/src/base/proof/error.rs
- crates/proof-of-sql/src/sql/proof/verification_builder.rs
These changes are beneficial since we shouldn't panic in `VerificationBuilder`.
See title.
Existing tests do pass.
> fix: add two error variants in `ProofSizeMismatch` and use them in `VerificationBuilder`

- Cargo.toml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/src/base/proof/transcript.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar.rs
The EVM requires big-endian serialization. This PR aligns with this, while keeping this transparent for the Rust code.
* MontScalar limbs are reversed before serialization. This ensures that the Scalar is encoded in big endian form when using an appropriate serializer (Other Scalar implementations do not need to do this.)
* `bincode` (with big-endian, fixint) is used instead of postcard in the `Keccak256Transcript`.
By existing test. Other PRs will eventually demonstrate EVM compatibility.
> chore!: give MontScalar and Keccak256Transcript EVM friendly serialization

- .github/workflows/lint-and-test.yml
- scripts/run_ci_checks.sh
- scripts/run_posql_examples.sh
- scripts/run_test_jobs.sh
Currently, we have shell scripts to run the CI jobs locally before submitting commits to a PR, to ensure that remote CI jobs are successful with as few runs as possible. The current check job includes several computationally expensive examples that should not be included in in a check workflow. Making this refactor makes local CI simulation more reliable and reduces load of the remote CI runners.
> refactor: move examples out of check script, create scripts for testing and examples

- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test_utility.rs
The QueryProof creation currently has a lot of custom transcript handling that differs from the QueryProof's serialization format. While the transcript handling aligns with EVM verification, it requires custom serialization. This PR makes it so that the two are identical.
* The QueryProof is broken up into smaller parts, each of which is put onto the transcript in aggregate. This simplifies the code.
* Each message uses serde to serialize the message and put it on the transcript. The underlying transcript dictates the actual serialization format.
They are tested by existing tests. Future PRs will have tests showing EVM compatibility.
> refactor!: use only serde to extend transcript in QueryProof

- crates/proof-of-sql/benches/README.md
- crates/proof-of-sql/benches/jaeger_benches.rs
- crates/proof-of-sql/src/proof_primitive/hyperkzg.rs
Add Jaeger benchmarks for the HyperKZG commitment scheme.
- Jaeger benchmarks are added to the HyperKZG commitment scheme.
Yes
> bench: add Jaeger benchmarks for HyperKZG commitment

- crates/proof-of-sql-parser/src/utility.rs
The original code uses a .into() call after the Expression::Aggregation { ... }. However, the expr field type in AliasedResultExpr expects Box<Expression>, and the additional conversion via .into() may be redundant. The correct way is to directly create the Box<Expression> without using .into().
> fix: type conversion in expression aggregation

- crates/proof-of-sql/src/sql/proof/verification_builder.rs
- crates/proof-of-sql/src/sql/proof_gadgets/mod.rs
- crates/proof-of-sql/src/sql/proof_gadgets/shift.rs
- crates/proof-of-sql/src/sql/proof_gadgets/shift_test.rs
This PR depends on #462.
Shifting is necessary for uniqueness which is necessary to prove inner joins.
- add shift gadget
- fix a typo in `VerificationBuilder::try_consume_rho_evaluation`
Yes.
> feat: add shift gadget

- crates/proof-of-sql/src/sql/evm_proof_plan/plans.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/tests.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/fold_util.rs
- crates/proof-of-sql/src/sql/proof_plans/fold_util_test.rs
This is the last bit of changes required in the Rust code in order to make the Rust prover/verifier compatible with the EVM verifier.
See commits
Existing tests cover these refactors.
> refactor!: evm verifier setup

- crates/proof-of-sql/src/base/arrow/column_arrow_conversions.rs
- crates/proof-of-sql/src/base/arrow/owned_and_arrow_conversions.rs
- crates/proof-of-sql/src/base/commitment/column_bounds.rs
- crates/proof-of-sql/src/base/commitment/committable_column.rs
- crates/proof-of-sql/src/base/commitment/naive_commitment.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/column_index_operation.rs
- crates/proof-of-sql/src/base/database/column_repetition_operation.rs
- crates/proof-of-sql/src/base/database/filter_util.rs
- crates/proof-of-sql/src/base/database/group_by_util.rs
- crates/proof-of-sql/src/base/database/order_by_util.rs
- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor.rs
- crates/proof-of-sql/src/base/database/union_util.rs
- crates/proof-of-sql/src/base/polynomial/multilinear_extension.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar.rs
- crates/proof-of-sql/src/base/scalar/scalar.rs
- crates/proof-of-sql/src/proof_primitive/dory/blitzar_metadata_table.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_helper_cpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/dynamic_dory_commitment_helper_cpu.rs
- crates/proof-of-sql/src/proof_primitive/dory/pack_scalars.rs
- crates/proof-of-sql/src/proof_primitive/hyperkzg.rs
- crates/proof-of-sql/src/sql/proof/provable_query_result.rs
- crates/proof-of-sql/src/sql/proof/provable_result_column.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test_utility.rs
Currently, range proofs operate by breaking scalar-backed values into smaller words, with a size of 8 bits at the moment. These words are then committed to as part of the range proof, but because there currently exists no column type for u8, we commit to full size scalars instead. This causes a rather large overhead during proof times because we are committing to 256 bits instead of just 8.
#481 resolves this somewhat by refactoring the bit and bytesize methods used during the proof, but a cleaner solution is to just support the u8 as a column type. This PR introduces full posql support for the u8 column type and removes the ```RangeCheckWord``` type altogether.
> feat: replace RangeCheckWord with full Uint8 support

- crates/proof-of-sql/src/sql/proof_gadgets/mod.rs
- crates/proof-of-sql/src/sql/proof_gadgets/monotonic.rs
- crates/proof-of-sql/src/sql/proof_gadgets/monotonic_test.rs
Replaces #487 and #502
In order to do inner joins and ordering we need to be able to prove that a single column is increasing, strictly or not.
- add monotonic gadget.
Yes.
> feat: add monotonic gadget

- crates/proof-of-sql/src/base/arrow/arrow_array_to_column_conversion.rs
- crates/proof-of-sql/src/base/arrow/column_arrow_conversions.rs
- crates/proof-of-sql/src/base/arrow/owned_and_arrow_conversions.rs
- crates/proof-of-sql/src/base/commitment/column_bounds.rs
- crates/proof-of-sql/src/base/commitment/column_commitment_metadata.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/column_arithmetic_operation.rs
- crates/proof-of-sql/src/base/database/column_comparison_operation.rs
- crates/proof-of-sql/src/base/database/column_operation_error.rs
- crates/proof-of-sql/src/base/database/literal_value.rs
- crates/proof-of-sql/src/base/database/order_by_util.rs
- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/database/owned_table_utility.rs
- crates/proof-of-sql/src/base/database/table_utility.rs
- docs/SQLSyntaxSpecification.md
#498 introduced minimal support for unsigned bytes as a PoSQL datatype. This was enough for commitments and other basic functionality. This PR introduces full-fledged support for Uint8 in anticipation of an upgrade to the PoSQL internal service (ProofsService).
Covered in existing tests
> feat: full Uint8 support

- crates/proof-of-sql/src/base/database/join_util.rs
- crates/proof-of-sql/src/base/database/order_by_util.rs
- crates/proof-of-sql/src/base/database/table_operation_error.rs
We need to add slice operations required for joins.
- add `ordered_set_union` and `get_multiplicities`
Yes
> feat: add helper functions to `join_utils`

- crates/proof-of-sql/src/base/database/join_util.rs
- crates/proof-of-sql/src/base/scalar/scalar.rs
- crates/proof-of-sql/src/sql/proof_gadgets/membership_check.rs
- crates/proof-of-sql/src/sql/proof_gadgets/membership_check_test.rs
We want to let membership check gadget take care of multiplicity computation to reduce the amount of duplicates in the sort merge join code.
See above.
Yes.
> refactor: fix membership check

- .github/workflows/lint-and-test.yml
- solidity/scripts/check_coverage.sh
- solidity/scripts/pre_forge.sh
- solidity/src/base/Constants.sol
- solidity/src/base/MathUtil.sol
- solidity/src/base/Transcript.sol
- solidity/test/base/MathUtil.t.sol
- solidity/test/base/Transcript.t.sol
This PR is the first of many breaking #508 into manageable pieces.
The following Yul functions are added, along with testing around them. They will be imported in future PRs.
* `log2_up`
* `draw_challenge`
* `draw_challenges`
* `append_calldata`
Yes
> feat: add Yul Transcript and MathUtil libraries

- crates/proof-of-sql/src/base/polynomial/multilinear_extension.rs
- crates/proof-of-sql/src/sql/proof/composite_polynomial_builder.rs
- crates/proof-of-sql/src/sql/proof/composite_polynomial_builder_test.rs
- crates/proof-of-sql/src/sql/proof/make_sumcheck_state.rs
- crates/proof-of-sql/src/sql/proof/mod.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/sumcheck_subpolynomial.rs
- crates/proof-of-sql/src/sql/proof/sumcheck_term_optimizer.rs
The sumcheck prover currently consumes a lot of memory.
See individual commits. Broadly speaking, this is just a refactor of `make_sumcheck_prover_state`, so it is fairly isolated.
Yes
> perf: reduce sumcheck memory usage

- crates/proof-of-sql/src/base/commitment/column_commitment_metadata.rs
- crates/proof-of-sql/src/base/commitment/column_commitment_metadata_map.rs
- crates/proof-of-sql/src/base/commitment/commitment_evaluation_proof.rs
- crates/proof-of-sql/src/base/commitment/committable_column.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_commitment.rs
I have corrected several typographical errors and improved the clarity of comments in the code. These changes include fixing spelling mistakes, removing redundant words, and ensuring variable names are accurate. This enhances the overall readability and accuracy of the documentation.
> docs: Fix typos

- .github/workflows/lint-and-test.yml
- .gitignore
- solidity/foundry.toml
- solidity/scripts/README.md
- solidity/scripts/check_coverage.sh
- solidity/scripts/install_deps.sh
- solidity/scripts/lint-and-test.sh
- solidity/scripts/pre_forge.sh
- solidity/scripts/preprocess_yul_imports.sh
- solidity/src/base/Constants.sol
- solidity/src/base/ECPrecompiles.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/base/ECPrecompiles.t.pre.sol
- solidity/test/base/Transcript.t.sol
This PR is the one of many breaking #508 into manageable pieces. In particular, this provides methods for elliptic curve operations.
The following Yul functions are added, along with some tests around them. They will be imported in future PRs.
* `ec_add`
* `ec_mul`
* `ec_pairing_x2`
* `ec_mul_assign`
* `calldata_ec_add_assign`
* `calldata_ec_mul_add_assign`
In addition to these methods, there is a lot of work done to preprocessing and CI to enable code coverage and tests to work properly.
Somewhat. It is difficult do any kind of thorough testing because the only mechanism that solidity has of computing ec operations is the precompiles.
> feat: add ECPrecompiles Yul library

- crates/proof-of-sql/utils/generate-parameters/round_trip_test.rs
The dory parameter generation module includes a test that uses the tempdir crate to test saving and loading the params from a file. This is a fairly non-consequential test that does not need to run in the CI on every check job. The reason ignore is being added here is because the tempdir crate is having intermittent segmentation faults that are causing local and remote/CI testing jobs to occasionally fail.
This PR ignores the dory param file saving and loading tests from the CI workflow.
Yes
> test: ignore param file loading tests

- crates/proof-of-sql/README.md
I’ve corrected the typo in the word "arithmatization" to the proper spelling, "**arithmetization**".
This update ensures consistency and accuracy in the codebase.
> docs: typo fix in README.md

- crates/proof-of-sql/src/base/scalar/mont_scalar.rs
- crates/proof-of-sql/src/base/scalar/scalar.rs
- crates/proof-of-sql/src/sql/proof_gadgets/membership_check.rs
- crates/proof-of-sql/src/sql/proof_gadgets/membership_check_test.rs
- crates/proof-of-sql/src/sql/proof_gadgets/mod.rs
- crates/proof-of-sql/src/sql/proof_gadgets/monotonic.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
- crates/proof-of-sql/src/sql/proof_plans/mod.rs
- crates/proof-of-sql/src/sql/proof_plans/sort_merge_join_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/sort_merge_join_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/test_utility.rs
- docs/protocols/inner_join.tex
Depends on the following PRs:
Closes #394.
We need to add sort merge inner joins.
- add `SortMergeJoinExec`
- add `Column::rho` and `Table::add_rho_column`
Will be.
> feat: add `SortMergeJoinExec`

- solidity/src/base/Constants.sol
- solidity/src/proof/Sumcheck.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/proof/Sumcheck.t.pre.sol
This PR is the one of many breaking the EVM verifier into manageable pieces. In particular, this provides the sumcheck verifier.
The `verify_sumcheck_proof` Yul function is added and tested.
Yes
> feat(sol): add sumcheck verifier

- scripts/run_posql_examples.sh
---
**# Rationale for this change**
The regular expression `^  [A-Za-z0-9_]+:` in the current script correctly captures lines containing job names, but it is limited to letters, digits, and underscores, which doesn't account for job names with hyphens (e.g., `deploy-prod` or `build-linux`). This could lead to issues if such job names are used in the workflow YAML files.
**# What changes are included in this PR?**
I’ve updated the regex in the script to allow job names containing hyphens as well, making it more flexible. The updated regex now correctly matches job names with letters, numbers, underscores, and hyphens:
```bash
sed -n -E '/^  examples:/,/^  [[:space:]]+[a-zA-Z0-9_-]+:/p' "$YAML_FILE"
```
This ensures that the script can handle job names like `deploy-prod` or `build-linux`, …
> chore: Fixed regex to correctly match job names with hyphens

- solidity/test/proof/Sumcheck.t.pre.sol
One of the sumcheck fuzz tests fails occasionally because a trivial proof is occasionally generated.
Trivial proof filtering is made more robust.
Yes, even when running the test 10000 times, there are no longer failures.
> test: fix flaky sumcheck fuzz test

- .github/workflows/lint-and-test.yml
- solidity/.solhint.json
- solidity/.solhintignore
- solidity/scripts/preprocess_yul_imports.sh
- solidity/src/base/ECPrecompiles.pre.sol
- solidity/src/base/LagrangeBasisEvaluation.sol
- solidity/src/base/Transcript.sol
- solidity/src/proof/Sumcheck.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/base/LagrangeBasisEvaluation.t.sol
- solidity/test/base/Transcript.t.sol
- solidity/test/proof/Sumcheck.t.pre.sol
This PR improves the solhint linting.
* Using `solhint:all` instead of `solhint:recommended`
* Using `.solhintignore` file.
* Cover everything in `solidity` rather than just `src`.
Yes
> chore: improve solhint linting

- crates/proof-of-sql/src/sql/proof_gadgets/mod.rs
- crates/proof-of-sql/src/sql/proof_gadgets/permutation_check.rs
- crates/proof-of-sql/src/sql/proof_gadgets/permutation_check_test.rs
- docs/protocols/permutation.tex
In order to define `OrderByExec` we need to have permutation.
The permutation gadget
Yes.
> feat: add permutation gadget

- solidity/README.md
We should have documentation explaining how to install dependencies for development
The documentation is added.
Yes. I just reinstalled these, so they work from a clean Ubuntu install.
> docs: add solidity README with dev dependencies installation

- solidity/scripts/lint-and-test.sh
- solidity/src/base/Constants.sol
- solidity/src/base/ECPrecompiles.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/base/ECPrecompiles.t.pre.sol
We will need these EC operations in the next PR.
* The generators and negatives of the generators are added as constants.
* `constant_ec_mul_add_assign` and `ec_add_assign` are added
* Ci/tooling related is slightly updated.
Yes. Most of the PR is testing the above, as well as improving the overall EC tests.
> feat(sol): add EC generator values and other EC operations

- solidity/src/base/Constants.sol
- solidity/src/proof/VerificationBuilder.sol
- solidity/test/base/Constants.t.sol
- solidity/test/base/ECPrecompiles.t.pre.sol
- solidity/test/proof/VerificationBuilder.t.sol
The verifier needs to retain/build state while traversing the proof plan. This PR mirrors the `VerificationBuilder` in the rust code.
* The base VerificationBuilder library is added.
* The `challenges`, `final_round_mle`, and `chi_evaluation` queues are added.
Yes
> feat(sol): add VerificationBuilder library and initial queues

- solidity/src/base/Constants.sol
- solidity/src/proof/VerificationBuilder.sol
- solidity/test/base/Constants.t.sol
- solidity/test/proof/VerificationBuilder.t.sol
This is a follow-up to #531 that is dependent on #544. 
- add queue for first round MLEs
- add queue for rho evals
Yes.
> feat(sol): add queues for first round MLEs and rho evals

- solidity/src/base/Constants.sol
- solidity/src/hyperkzg/HyperKZGHelpers.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/hyperkzg/HyperKZGHelpers.t.pre.sol
The HyperKZG verifier can be broken down into smaller methods in order to facilitate more granular unit testing.
3 helper methods:
* `run_transcript`, which computes the challenges
* `bivariate_evaluation`, which computes the bivariate evaluation of the `v` vector in the HyperKZG proof.
* `check_v_consistency`, which checks the consistency of the `v` vector
Yes
> feat(sol): add HyperKZG helpers

- .github/workflows/lint-and-test.yml
- solidity/test/base/Errors.t.sol
- solidity/test/proof/VerificationBuilder.t.pre.sol
Foundry just upgraded `v.1.0.0` to `stable`. This broke some tests.
* Pinned the CI foundry version to `v1.0.0`.
* Fixed the failing tests.
Yes
> chore: pin foundry to v1.0.0 and fix related issues

- solidity/.solhint.json
- solidity/src/hyperkzg/HyperKZGHelpers.pre.sol
- solidity/src/proof/Sumcheck.pre.sol
- solidity/test/hyperkzg/HyperKZGHelpers.t.pre.sol
The HyperKZG verifier can be broken down into smaller methods in order to facilitate more granular unit testing. This is the second (of two) PRs creating helper methods.
2 helper methods:
* `univariate_group_evaluation` to compute
$$ \sum_{i=0}^{m-1} e^i \mathbf{g}_i $$
* `compute_gl_msm` to compute
$$ g_L := \left(d^2 + d + 1\right)\cdot \left(\mathbf{C} + \sum_{i=0}^{m-1} q^{i+1}\cdot \mathbf{com}_i\right) + r\cdot\mathbf{w}_0 - dr \cdot\mathbf{w}_1 + (dr)^2\cdot\mathbf{w}_2 + b\cdot (-\mathbf{G}) $$
Yes
> feat(sol): add HyperKZG MSM helpers

- crates/proof-of-sql/src/base/database/order_by_util.rs
- crates/proof-of-sql/src/base/database/order_by_util_test.rs
- crates/proof-of-sql/src/base/database/owned_table.rs
- crates/proof-of-sql/src/sql/parse/query_context.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/parse/query_expr.rs
- crates/proof-of-sql/src/sql/parse/query_expr_tests.rs
- crates/proof-of-sql/src/sql/postprocessing/error.rs
- crates/proof-of-sql/src/sql/postprocessing/order_by_postprocessing.rs
- crates/proof-of-sql/src/sql/postprocessing/order_by_postprocessing_test.rs
- crates/proof-of-sql/src/sql/postprocessing/test_utility.rs
This PR addresses the need to replace the `proof_of_sql_parser::OrderBy` with the `sqlparser::ast::OrderByExpr` in the `proof-of-sql` crate as part of a larger transition toward integrating the `sqlparser` .
This change is a subtask of issue #235, with the main goal of streamlining the repository by switching to the `sqlparser` crate and gradually replacing intermediary constructs like `proof_of_sql_parser::intermediate_ast` with `sqlparser::ast`.
- All instances of `proof_of_sql_parser::OrderBy` have been replaced with `sqlparser::ast::OrderByExpr`
-  Every usage of `OrderBy` has been updated to maintain the original functionality, …
> refactor!: `proof_of_sql_parser::intermediate_ast::OrderBy` with `sqlparser::ast::OrderByExpr` in the proof-of-sql crate

- .github/workflows/lint-and-test.yml
Codecov provides nice coverage report viewing, and is free for public repos. This PR uploads the coverage report to Codecov.
It will need to be fully tested on the next PR.
> ci: upload coverage report to codecov

- solidity/src/base/Constants.sol
- solidity/src/base/Errors.sol
- solidity/src/base/Queue.pre.sol
- solidity/src/proof/VerificationBuilder.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/base/Errors.t.sol
- solidity/test/base/Queue.t.pre.sol
- solidity/test/proof/VerificationBuilder.t.pre.sol
The VerificationBuilder has a lot of redundant code
* a `dequeue` method is added to the Queue library
* the VerificationBuilder methods are updated to use this method to manage the queues
NOTE: this is a large PR. Look at the individual commits. The majority of the changes are very repetitive and also add lots of documentation. The actual code is greatly simplified.
Yes
> refactor(sol): add `Queue` library and leverage it in `VerificationBuilder`

- .github/workflows/lint-and-test.yml
- Cargo.toml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/examples/posql_db/run_example.sh
- crates/proof-of-sql/src/base/proof/transcript.rs
- crates/proof-of-sql/src/proof_primitive/mod.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/tests.rs
- crates/proof-of-sql/src/utils/log.rs
- crates/proof-of-sql/tests/integration_tests.rs
There is a bug in our CI that checks for no_std compatibility. In the meantime, many incompatibilities have been let through. This PR fixes *most* of them. The exception is `sqlparser`, whose `serde` flag enables `serde/std`. We cannot address this one officially until a version of `sqlparser` is released without this issue, and we upgrade to it. In the meantime, complete no_std can be achieved with the following fork:
```toml
[patch.crates-io]
sqlparser = { git = "https://github.com/tlovell-sxt/datafusion-sqlparser-rs.git", rev = "a828cbea22cf19bb6b4596f902bdd6f4d14a00b8" }
```
The commits provide a decent summary of what has changed:
- **fix: put nova-snark dependency and hyperkzg module behind feature flag**
- **fix: use bincode 2.0.0 release candidate for no_std compatibility**
- …
> fix: address many no_std compatibility issues

- .github/workflows/lint-and-test.yml
CI is not releasing
This pull request includes a small change to the `.github/workflows/lint-and-test.yml` file. The change adjusts the coverage threshold for the CI enforcement.
* [`.github/workflows/lint-and-test.yml`](diffhunk://#diff-9a979a1e38ba79e2c75e54c4bf21fe1a2a1b935e1736666565f992e634dadd0fL203-R203): Lowered the fail-under-lines threshold from 95 to 94 in the `Enforce Coverage Threshold` step.
> ci: reduce coverage threshold

- crates/proof-of-sql/src/sql/logical_plans/error.rs
- crates/proof-of-sql/src/sql/logical_plans/expr.rs
- crates/proof-of-sql/src/sql/logical_plans/mod.rs
- crates/proof-of-sql/src/sql/mod.rs
This PR is inspired by `DataFusion`.
We do expect to have proof and postprocessing nodes coexisting for a long time. Hence it is necessary to introduce `Expr` and `LogicalPlan` to make it easier to detect schema errors (e.g. `select not_a_column from tab` and `select * from tab where not_a_bool_col`) and separate the process of processing a query into logical nodes from routing them to proof and postprocessing nodes. 
- add `sql/logical_plans` directory
- add `logical_plans::Expr`
- add `LogicalPlanError`
Will be.
> feat: add `logical_plans::Expr`

- .github/workflows/lint-and-test.yml
- solidity/test/proof/VerificationBuilder.t.pre.sol
We will want to use `--via-ir` and `--optimize` in production, so we should run tests using all combinations. This could also help identify any hidden Yul/assembly bugs.
> chore: use `--via-ir` and `--optimize` in the CI test suite

- crates/proof-of-sql/src/sql/logical_plans/mod.rs
- crates/proof-of-sql/src/sql/logical_plans/plan.rs
Depends on the following PRs
Depends on #556
Add `LogicalPlan`.
- add `LogicalPlan`
Will be.
> feat: add `logical_plans::LogicalPlan`

- solidity/src/base/Constants.sol
- solidity/src/base/Errors.sol
- solidity/src/proof/VerificationBuilder.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/base/Errors.t.sol
- solidity/test/proof/VerificationBuilder.t.pre.sol
This continues to expand the VerificationBuilder, making it mirror the rust code.
Primary changes are around adding the methods `builder_produce_zerosum_constraint` and `builder_produce_identity_constraint`.
Note: this depends on #550 and somewhat motivated it, hence why it in draft.
Yes
> feat(sol): add constraint methods to `VerificationBuilder` library

- Cargo.toml
chrono `v0.4.40` implemented a `quarter` method that causes build errors when building with arrow. See bug https://github.com/apache/arrow-rs/issues/7196 and this commit https://github.com/apache/arrow-rs/pull/7210. The suggested workaround is to pin chrono to `v0.4.39`.
- Pins chrono to the latest version that works with arrow, `v0.4.39`
Yes
> fix: pin chrono to avoid build errors with arrow

- Cargo.toml
- crates/proof-of-sql/benches/README.md
- crates/proof-of-sql/benches/jaeger_benches.rs
- crates/proof-of-sql/src/proof_primitive/hyperkzg.rs
HyperKZG performance can be improved by doing commitment computation on the GPU. This PR implements a GPU version of the HyperKZG commitment computation.
The HyperKZG commitment computation run on the CPU (from the `main` branch) 
The HyperKZG commitment computation using the GPU implementation from this PR 
The GPU commitment computation shows a `5.1x` performance improvement on the same query.
- HyperKZG GPU commitment computation implementation and tests are added in commit https://github.com/spaceandtimelabs/sxt-proof-of-sql/pull/577/commits/b79c98195347415b610da399a7354dc34ceb986b
- `blitzar` is update to version `4.3.0`
- `nova-snark` is updated to version `0.40.0`
Yes
> feat: implement GPU version or HyperKZG commitment computation

- solidity/src/base/Constants.sol
- solidity/src/base/Errors.sol
- solidity/src/base/SwitchUtil.pre.sol
- solidity/src/proof_exprs/LiteralExpr.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/base/Errors.t.sol
- solidity/test/base/SwitchUtil.t.pre.sol
- solidity/test/proof_exprs/LiteralExpr.t.pre.sol
We need to add the SQL nodes to the solidity verifier.
* Added a `case_const` function to "compile-time" assert that two constants are equal. This is because Yul does not support constants in case statements.
* Added `literal_expr_evaluate` function.
Yes
> feat(sol): add literal expression

- crates/proof-of-sql/src/sql/proof_exprs/column_expr_test.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/test_utility.rs
- crates/proof-of-sql/src/sql/proof_plans/union_exec_test.rs
We need to make it possible to compose `ProjectionExec` with `ProofPlan`s. After this generalization it should work at least in situations where there is one input table.
- replace `TableExpr` in `ProjectionExec` with `Box<DynProofPlan>`
Yes.
> feat!: allow `ProjectionExec` to take general inputs

- solidity/src/base/Constants.sol
- solidity/src/base/Errors.sol
- solidity/src/proof/VerificationBuilder.pre.sol
- solidity/src/proof_exprs/ColumnExpr.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/base/Errors.t.sol
- solidity/test/proof/VerificationBuilder.t.pre.sol
- solidity/test/proof_exprs/ColumnExpr.t.pre.sol
We need to add the SQL nodes to the solidity verifier.
* Added column evaluations to the verification builder. This diverges slightly from the Rust code, but reduces the stack size, which is critical in the EVM.
* Added `column_expr_evaluate`.
Yes
> feat(sol): add column expression

- Cargo.toml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/src/base/arrow/arrow_array_to_column_conversion.rs
- crates/proof-of-sql/src/base/arrow/column_arrow_conversions.rs
- crates/proof-of-sql/src/base/arrow/owned_and_arrow_conversions_test.rs
- crates/proof-of-sql/src/base/database/column.rs
- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/base/math/decimal.rs
One missing piece of proof-of-sql's VarBinary column support is conversion from arrow's binary data type.
Unfortunately this is easy to miss as adding new columns without adding this conversion does not trigger any compilation issues. A couple new roundtrip tests have been added that should help developers catch this in the future. I figured that the best way to write these tests was with proptest.
Let me know if there are any objections to introducing this dev-dependency. I intentionally put it and the associated tests in a separate commit so I can remove it easily.
- **fix: remove blitzar requirement for arrow_array_to_column_conversion tests**
- **fix: convert arrow's Binary column to VarBinary**
- **test: add proptests for column type and arrow conversions**
Yes.
> fix: convert arrow's Binary column to VarBinary

- .github/workflows/lint-and-test.yml
In [Rustup 1.28.0](https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html) which was released yesterday it is no longer true that the active toolchain is automatically installed. Hence we need to install it explicitly in CI or CI breaks.
Really thanks @tlovell-sxt for finding the actual source of the problem!
- adjust CI so that relevant toolchains are manually installed
N/A
> build: explicitly install the active toolchain in ci because rustup 1.28.0 no longer does so by default

- solidity/src/base/Array.pre.sol
- solidity/src/base/Constants.sol
- solidity/src/base/Errors.sol
- solidity/src/proof/VerificationBuilder.pre.sol
- solidity/src/proof_exprs/ColumnExpr.pre.sol
- solidity/test/base/Array.t.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/base/Errors.t.sol
- solidity/test/proof/VerificationBuilder.t.pre.sol
- solidity/test/proof_exprs/ColumnExpr.t.pre.sol
We need to port the verifier to the EVM. This is one part of it.
Added `get_array_element` and `builder_get_table_chi_evaluation` methods.
Yes
> feat(sol): add table chi evaluations

- solidity/test/base/FieldUtil.sol
- solidity/test/base/FieldUtil.t.sol
- solidity/test/base/LagrangeBasisEvaluation.t.sol
- solidity/test/hyperkzg/HyperKZGHelpers.t.pre.sol
- solidity/test/proof/Sumcheck.t.pre.sol
- solidity/test/proof/VerificationBuilder.t.pre.sol
- solidity/test/proof_exprs/LiteralExpr.t.pre.sol
Working with `mulmod` and `addmod` is tedious and unclear. While it is needed for efficient execution, we should have more clarity around tests.
* The `FF` type is added in `tests` that acts as a field type with modulus `MODULUS`.
* Several methods are implemented in the `F` module. In particular, `F.from` and `F.into` allow for conversions to and from the `FF` type.
* Existing tests are refactored to use this type.
Yes
> test(sol): add `FieldUtils`

- crates/proof-of-sql/src/base/encode/u256.rs
- crates/proof-of-sql/src/base/scalar/mont_scalar.rs
- rust-toolchain.toml
Since Rust 1.85.0 has been around for about two weeks it is time for us to upgrade to it.
- bump Rust to 1.85.0
- relevant clippy-related changes
Yes.
> chore: bump Rust to 1.85.0

- .github/workflows/lint-and-test.yml
- Cargo.toml
- crates/proof-of-sql-planner/Cargo.toml
- crates/proof-of-sql-planner/src/context.rs
- crates/proof-of-sql-planner/src/error.rs
- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql-planner/src/util.rs
In order to take advantage of name resolution and logical plan from datafusion we would like to add a new planner crate. This PR is a part of #580 since #580 is getting large.
- add `proof-of-sql-planner` crate with the following
- `PlannerError` and `PlannerResult`
- `PoSqlContextProvider` and `PoSqlTableSource`
- utils that perform datafusion <-> PoSql conversions
- let CI check for `no_std` for `proof-of-sql` and `proof-of-sql-parser` crates since `proof-of-sql-planner` which uses `datafusion` requires `std`
Yes.
> feat: add minimal `proof-of-sql-planner` crate && relevant CI change

- crates/proof-of-sql/src/proof_primitive/hyperkzg.rs
We don't want the naive implementation of `compute_commitments_impl` padding the scalars with zeroes
Refactoring `compute_commitments_impl` to not pad the scalars with zeroes
Yes
> refactor: refactor HyperKZG compute_commitments_impl

- crates/proof-of-sql-planner/Cargo.toml
- crates/proof-of-sql-planner/src/util.rs
It is necessary to add timestamps to `scalar_value_to_literal_value`. 
- add timestamp to `scalar_value_to_literal_value`
Yes.
> feat: allow timestamps in `datafusion::common::ScalarValue` -> `LiteralValue` conversion

- crates/proof-of-sql/src/base/arrow/arrow_array_to_column_conversion.rs
- crates/proof-of-sql/src/base/arrow/owned_and_arrow_conversions.rs
> fix: typo fixes

- crates/proof-of-sql/src/base/bit/bit_distribution.rs
- crates/proof-of-sql/src/sql/proof_gadgets/sign_expr.rs
> fix: typo fix `base::bit::BitDistrubutionError` to `BitDistributionError`

- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/base/database/literal_value.rs
> fix: minor typos in code

- crates/proof-of-sql-planner/src/df_util.rs
- crates/proof-of-sql-planner/src/error.rs
- crates/proof-of-sql-planner/src/expr.rs
- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
Depends on #596.
Following #596 now we need to add conversion of `datafusion::logical_expr::Expr` to `DynProofExpr`.
- add conversion of `datafusion::logical_expr::Expr` to `DynProofExpr`
- add a few more error variants in `ProofExpr`
- add `df_util.rs` for datafusion-related helper functions
Yes.
> feat: add `datafusion::logical_expr::Expr` -> `ProofExpr`

- crates/proof-of-sql/src/sql/proof/mock_verification_builder.rs
- crates/proof-of-sql/src/sql/proof/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/and_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/test_utility.rs
- crates/proof-of-sql/src/sql/proof_gadgets/permutation_check.rs
This will add a test implementation of `VerificationBuilder` to make testing verifier_evaluate easier.
- New `MockVerificationBuilder`
- New test utility `verify_row_by_row` which returns a matrix of bools, indicating failing and passing constraints
- New `and_expr` tests to showcase the new utilities.
Yes
> feat: mock verification builder

- solidity/test/base/ECPrecompiles.t.pre.sol
- solidity/test/hyperkzg/HyperKZGHelpers.t.pre.sol
Some of the fuzz tests rely on random sampling not choosing very low probability samples. However, the foundry fuzz tests are not fully random, so some edge cases need to be filtered out. Some tests do not filter enough.
* Fixed flakiness in `testFuzzECPairingX2WithValidInputsThatDoNotSumToZero`: if a+b = 0 as field elements, the test will/should fail. This is now filtered out.
* Fixed flakiness in `testFuzzRevertsVConsistency`. If r = 0 and x[i] = 0, the test will/should fail. This is now filtered out.
NA
> test(sol): fix flaky tests

- Cargo.toml
To improve test run time by using rust's aggressive compiler optimizations. This is generally done by testing multiple settings and levels, 1-2 could be done as well but the most improvement we get with this codebase is with 3. LTO and codegen unit numbers being 1 do not provide enough justification for build time increase, as they do not give good runtime improvements compared to this.
Set the optimization level for test profile to 3 to improve test performance and potentially catch more optimization-related issues.
Yes, manually.
/claim #557
> chore: increase test optimization level

- Cargo.toml
From https://github.com/spaceandtimelabs/sxt-proof-of-sql/actions/workflows/lint-and-test.yml it is clear that the recent optimization, while helping performance on local machines, actually makes CI slower. Hence we have to revert it.  
Revert the optimization
N/A
> chore: remove test profile since it slows down CI

- crates/proof-of-sql/src/base/commitment/column_commitment_metadata.rs
- crates/proof-of-sql/src/base/database/group_by_util.rs
- crates/proof-of-sql/src/base/database/group_by_util_test.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/tests/integration_tests.rs
Enables queries of the form:
```sql
"SELECT * FROM table WHERE a=b AND c=d AND e=f"
```
for the varbinary type.
Simple update to PoSQL to update the binary check operation to enable var binary support
> feat: equality between varbianry columns

- crates/proof-of-sql-planner/src/context.rs
- crates/proof-of-sql-planner/src/error.rs
- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql-planner/src/plan.rs
- crates/proof-of-sql/src/sql/proof_exprs/aliased_dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/table_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
I'm adding a few basic `LogicalPlan`s and convert them to `ProofPlan`s to get end to end running ASAP.
- adds conversion for `EmptyRelation` and `TableScan` whenever there is no fetch limit
- makes `AliasedDynProofExpr`, `ProofExpr` and `TableExpr` pub
Yes.
> feat: convert `LogicalPlan` to `ProofPlan`

- crates/proof-of-sql-planner/src/util.rs
Now that we have `LiteralValue::VarBinary` we need to support it in the planner.
- add `ScalarValue` -> `LiteralValue` conversion for binaries
Yes.
> feat: add `LiteralValue` conversion for binary to planner

- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql-planner/src/plan.rs
- crates/proof-of-sql-planner/src/util.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
Now that we have basic `LogicalPlan` -> `ProofPlan` we should support more features. Moreover a bug has been found in the code which is to be fixed and with a test checking for it.
- add `TableScan` with fetch
- add `Limit`, `Projection` and `Union`
- fix one error in `table_scan_to_projection` which accidentally uses output rather than input `ColumnField`s
Will be.
>  feat: convert `LogicalPlan` variants `Limit`, `Projection`, `Union` and `TableScan` with `fetch` to `ProofPlan`

- .gitignore
- crates/proof-of-sql-planner/Cargo.toml
- crates/proof-of-sql-planner/src/conversion.rs
- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql-planner/src/util.rs
- crates/proof-of-sql-planner/tests/e2e_tests.rs
In order to take advantage of name resolution and logical plan from datafusion we would like to add a new planner crate.
- add `sql_to_proof_plans`
Will be.
> feat: add `sql_to_proof_plans`

- .gitignore
- crates/proof-of-sql-planner/src/error.rs
- crates/proof-of-sql-planner/src/util.rs
- crates/proof-of-sql/src/base/arrow/scalar_and_i256_conversions.rs
- crates/proof-of-sql/src/base/math/i256.rs
We need to fully support decimal literals in the planner hence the PR.
- Add `From<i128>` and `From<arrow::datatypes::i256>` implementation for `I256` with unit tests
- Add `Decimal128` and `Decimal256` conversion in `scalar_value_to_literal_value`
Yes.
> feat: add decimal support to `I256` and `scalar_value_to_literal_value`

- .github/pull_request_template.md
- COMMIT_GUIDELINES.md
- scripts/check_commits.sh
Most of our contributors do not read or follow the conventional commit guidelines outlined [here](https://www.conventionalcommits.org/en/v1.0.0/#summary). This causes slowdowns and frictions in the review process when asking the contributors to reword or squash their commits to ensure they are clean enough to meet our standards.
This PR adds a required checkbox to the PR template that provides a simple and concise example of what the resulting commit history should look like before the PR is ready to merge.
> feat: enforce conventional commit guidelines

- crates/proof-of-sql/src/base/arrow/owned_and_arrow_conversions.rs
- crates/proof-of-sql/src/base/arrow/record_batch_errors.rs
This is a part of the process of removal of the parser crate. There are useless error variants referring to `proof_of_sql_parser` and they need to be removed.
See above.
Yes.
> refactor!: remove unused error variants

- crates/proof-of-sql-planner/src/error.rs
- crates/proof-of-sql/src/sql/error.rs
- crates/proof-of-sql/src/sql/mod.rs
- crates/proof-of-sql/src/sql/parse/dyn_proof_expr_builder.rs
- crates/proof-of-sql/src/sql/parse/error.rs
- crates/proof-of-sql/src/sql/parse/mod.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/parse/query_expr_tests.rs
- crates/proof-of-sql/src/sql/parse/where_expr_builder_tests.rs
- crates/proof-of-sql/src/sql/proof_exprs/add_subtract_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/comparison_util.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/inequality_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/multiply_expr_test.rs
- crates/proof-of-sql/src/sql/util.rs
- crates/proof-of-sql/tests/integration_tests.rs
In order to drop `sql/parse` it is necessary to make sure `proof-of-sql-planner` and `sql/proof-exprs` are not dependent on it. Hence we split out functionalities we expect to retain after the dropping.  
- add `AnalyzeError`
- move type checks out of `sql/parse`
Yes.
> refactor!: add `AnalyzeError` and make `sql/proof_exprs` no longer dependent on `sql/parse`

- crates/proof-of-sql-planner/Cargo.toml
- crates/proof-of-sql-planner/src/aggregate.rs
- crates/proof-of-sql-planner/src/error.rs
- crates/proof-of-sql-planner/src/lib.rs
This PR exists to prepare for adding support for `GROUP BY` in the planner.
- add `aggregate_function_to_proof_expr`
Yes.
> feat: add `aggregate_function_to_proof_expr`

- Cargo.toml
- crates/powers-of-tau-util/Cargo.toml
- crates/powers-of-tau-util/src/main.rs
This PR adds a crate that will create a binary file from a power of tau file found at https://github.com/privacy-scaling-explorations/perpetualpowersoftau.
Usage: `cargo run --release <ptau_file_path> <binary_file_path> <n>` where `n` is the number of points.
- A new crate `powers-of-tau-util` is added to the project.
Yes
> feat: add powers-of-tau-util crate for creating compressed binary element files

- crates/proof-of-sql/src/proof_primitive/hyperkzg/mod.rs
- crates/proof-of-sql/src/proof_primitive/hyperkzg/public_setup.rs
- crates/proof-of-sql/src/proof_primitive/hyperkzg/test_ppot_0080_02.bin
The hyperkzg setups publicized in our github releases have slightly more complicated serializations than a plain ark-serialized Vec. To handle this slight complication, this change provides couple deserialization methods. One of them iterates through a std reader, and the other uses a slice for no-std deserialization.
Two hyperkzg public setup deserialization methods have been added
Yes.
> feat: add deserialization utilities for hyperkzg public setup

- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql-planner/src/postprocessing/expression_evaluation.rs
- crates/proof-of-sql-planner/src/postprocessing/expression_evaluation_error.rs
- crates/proof-of-sql-planner/src/postprocessing/expression_evaluation_test.rs
- crates/proof-of-sql-planner/src/postprocessing/mod.rs
In order to support postprocessing we need to add a version of `base/database/expression_evaluation.rs` in `proof_of_sql_planner`.
- add `evaluate_expr` which evaluates DataFusion logical expressions [`datafusion::logical_exp::Expr`](https://docs.rs/datafusion/38.0.0/datafusion/logical_expr/enum.Expr.html)
Yes.
> feat: add `postprocessing/expression_evaluation` to the `proof-of-sql-planner` crate

- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql-planner/src/postprocessing/error.rs
- crates/proof-of-sql-planner/src/postprocessing/mod.rs
- crates/proof-of-sql-planner/src/postprocessing/postprocessing_step.rs
- crates/proof-of-sql-planner/src/postprocessing/select_postprocessing.rs
- crates/proof-of-sql-planner/src/postprocessing/select_postprocessing_test.rs
My first CLI-made PR here lol (Thanks @tlovell-sxt for reminding me of this!)
We need to add `SelectPostprocessing` to do `GROUP BY` with currently unsupported output column ordering as well as division.
- add `PostprocessingError` which looks like a stub but can be expanded whenever we need more postprocessing
- add `PostprocessingStep`
- add `SelectPostprocessing`
Will be.
> feat: add `PostprocessingError` and `SelectPostprocessing`

- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
- crates/proof-of-sql/src/sql/proof_gadgets/divide_and_modulo_expr.rs
- crates/proof-of-sql/src/sql/proof_gadgets/mod.rs
Because the div and mod gadget has so many constraints, it needs to be broken down into several PRs. This first PR provides a prover and verifier that returns the results but enforces no constraints. The constraints will be added in subsequent PRs.
New DivAndModExpr
Yes
> feat: add divide and modulo gadget skeleton

- .github/workflows/lint-and-test.yml
- crates/proof-of-sql-planner/Cargo.toml
- crates/proof-of-sql-planner/src/context.rs
We need to make sure the planner crate works with WASM.
- make the planner crate work with WASM
- add this to CI so that this will always be the case
N/A
> feat: make `proof-of-sql-planner` WASM-compatible && add CI to check that it builds

- crates/proof-of-sql/src/base/bit/bit_distribution.rs
This was a docs mistake.
A single doc change
No new tests
> docs: correct vary mask docs

- crates/proof-of-sql-planner/Cargo.toml
- crates/proof-of-sql-planner/src/aggregate.rs
This PR helps completely decouple the code we want to delete from the code we want to keep. 
- add `AggregateFunc`
- remove dependency on `proof_of_sql_parser` in `proof_of_sql_planner`
Yes.
> refactor: remove `proof_of_sql_parser` dependency from `proof_of_sql_planner`

- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql-planner/src/plan.rs
- crates/proof-of-sql-planner/tests/e2e_tests.rs
- crates/proof-of-sql/src/sql/proof_exprs/column_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_plans/dyn_proof_plan.rs
Depends on the following PRs:
We need to add provable group bys to `ProofPlan`.
See above.
Yes.
> feat: add group by support in the planner

- Cargo.toml
- crates/proof-of-sql-parser/src/intermediate_ast.rs
- crates/proof-of-sql-parser/src/intermediate_ast_tests.rs
- crates/proof-of-sql-parser/src/posql_time/timezone.rs
- crates/proof-of-sql-parser/src/posql_time/unit.rs
- crates/proof-of-sql/src/base/database/column_repetition_operation.rs
Started adding tests. Will try to cover code that would add value. 
/claim #560
Gradually increasing test coverage
```
proof-of-sql-parser/src/posql_time/timezone.rs
proof-of-sql-parser/src/posql_time/timestamp.rs
proof-of-sql-parser/src/identifier.rs
proof-of-sql-parser/src/intermediate_ast.rs
```
Additionally, added check for time zone boundaries, hours should not be over 12, and minutes should not be over 60 (please correct me if I am doing it wrong). This change is also tested
Ignored because some tests felt redundant, I am open for suggestions.
```
proof-of-sql/src/base/arrow/owned_and_arrow_conversions.rs
proof-of-sql/src/base/arrow/column_arrow_conversions.rs
proof-of-sql/src/base/database/column_repetition_operation.rs
```
Yes.
> test: Improving test coverage

- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test_utility.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr_test.rs
- crates/proof-of-sql/src/sql/proof_gadgets/membership_check_test.rs
- crates/proof-of-sql/src/sql/proof_gadgets/permutation_check_test.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/sort_merge_join_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/table_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/union_exec_test.rs
Tableless queries such as `select 'not_a_column', 0 as def_int;` are legitimate and can have non-trivial results. However we currently force the results to be empty since we currently don't allow tableless queries in `sql/parse` any way. Now this needs to be fixed in order for such queries to be allowed and return correct results. Note that we aren't going to enable it in `sql/parse` since it is legacy code that will be removed very soon but we will in the planner.
- remove restriction that at least one non-empty input table exists
> feat!: remove restrictions that at least one non-empty input table exists from `sql/proof`

- crates/proof-of-sql/src/base/commitment/table_commitment.rs
The current standard for serializing/deserializing table commitments uses bincode, and the order of struct fields in bincode serialization deterministically matches the order of the struct fields in rust. This standard was chosen because, despite it being a binary format, custom deserialization for it can easily be written in any language. So, at the moment, the serialization order for table commitments is something like..
1. commitments
2. column commitment metadata
3. range
Many use cases for custom deserialization don't care about the column commitment metadata, but do care about the commitments and range. So, it would be nice for these use cases to place the range first before the dynamically sized items so that custom deserializers don't have to worry about that dynamic sizing, and …
> feat!: rearrange serialization order of TableCommitment fields

- crates/proof-of-sql/src/sql/proof/mod.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs
It is helpful for apis to expose proofs and query results separately. These are both stored in a VerifiableQueryResult, which is the typical result type for provers. However, not only are its fields private, but the QueryProof type itself is private, so the two outputs cannot be accessed individually pre-verification. This change simply publicizes the necessary items to access the proof and query results individually.
- QueryProof publicized, fields are only public to super
- VerifiableQueryResult fields publicized
- QueryProof re-export publicized
These changes do not affect existing functionality, which should be verified by existing tests.
> feat: publicize `QueryProof` and `VerifiableQueryResult` fields

- crates/proof-of-sql/src/sql/evm_proof_plan/error.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/exprs.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/plans.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/proof_plan.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/tests.rs
There is a serialize implementation for `EVMProofPlan` but no deserialize implementation. There needs to be a deserialize implementation.
1. Adding functionality to the serialization implementation as needed to make deserialization possible.
2. Adding deserialize implementation.
No
> feat!: impl `Deserialize` for `EVMProofPlan`

- crates/proof-of-sql/src/sql/evm_proof_plan/error.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/exprs.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/plans.rs
Depends on #658 
Add unit tests to `evm_proof_plan` to make it more maintainable.
- add unit tests to `evm_proof_plan`
Yes.
> test: add unit tests for `evm_proof_plan`

- crates/proof-of-sql-planner/src/conversion.rs
- crates/proof-of-sql-planner/src/error.rs
- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql-planner/src/proof_plan_with_postprocessing.rs
- crates/proof-of-sql-planner/tests/e2e_tests.rs
We need to support postprocessing at every level.
- add `ProofPlanWithPostprocessing`
Yes.
> feat: add `ProofPlanWithPostprocessing`

- crates/proof-of-sql/src/sql/proof/mock_verification_builder.rs
- crates/proof-of-sql/src/sql/proof_exprs/and_expr_test.rs
- crates/proof-of-sql/src/sql/proof_gadgets/divide_and_modulo_expr.rs
- crates/proof-of-sql/src/sql/proof_gadgets/permutation_check.rs
There will be changes to `RangeCheck` relatively soon. This PR will make way for easier unit testing of `RangeCheck`, which uses `FirstRoundBuilder`.
- New functionality on `MockVerificationBuilder` to include first round commitments.
- Correction to `try_consume_final_round_mle_evaluation` to enforce the `TooFewMLEEvaluations` error.
Yes
> test: add first round builder to mock verification builder

- crates/proof-of-sql/src/base/database/column_operation_error.rs
- crates/proof-of-sql/src/base/database/column_type_operation.rs
This is a preparatory commit for the `CastExpr`
A new function to determine if a `ColumnType` can be cast to another `ColumnType`
Yes
> feat: add `try_cast_types`

- crates/proof-of-sql-planner/src/expr.rs
- crates/proof-of-sql-planner/tests/e2e_tests.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec_test.rs
Ever since #583 is merged we can now provably support tableless queries. Hence let's officially enable this in the planner. Moreover our current `GroupByExec` actually supports aggregations without `GROUP BY` which we are in fact already using so let's add tests so that this previously undocumented feature is explicitly supported.
- allow aliases in `logical_expr_to_proof_expr`
- add tests for tableless & `GROUP BY`-less aggregation queries 
Yes.
> feat: allow tableless queries in the planner && add aggregation examples without `GROUP BY`

- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/cast_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/cast_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
- crates/proof-of-sql/src/sql/proof_exprs/test_utility.rs
> feat: add cast expr

- crates/proof-of-sql/src/base/database/column_operation_error.rs
- crates/proof-of-sql/src/base/database/column_type_operation.rs
In order to prepare for a `ScaleCastExpr`, there is a need for a function that determines if one type can be scale cast to another type.
A new function `try_scale_cast_types`
Yes
> feat: add `try_scale_cast_types`

- Cargo.toml
Specifying `opt-level` actually increases test time in CI hence let's revert #688.
> ci: remove `opt-level` from `profile.test` in top level `Cargo.toml`

- crates/proof-of-sql/src/base/proof/error.rs
- crates/proof-of-sql/src/base/proof/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/placeholder_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/placeholder_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/test_utility.rs
Now we can add `PlaceholderExpr`.
- add variants to `PlaceholderError`
- add `PlaceholderExpr`
Yes.
> feat: add `PlaceholderExpr`

- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
The primary calculation that is needed to cast an integer or decimal type to another decimal type is the factor by which the original value needs to be multiplied.
New function `try_get_scaling_factor_with_precision_and_scale`, which returns a scalar, because the value can be as big 10^247.
Yes
> feat: try get scaling factor with precision and scale

- crates/proof-of-sql-planner/src/error.rs
- crates/proof-of-sql-planner/src/expr.rs
- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql-planner/src/util.rs
- crates/proof-of-sql-planner/tests/e2e_tests.rs
- crates/proof-of-sql/src/base/proof/error.rs
- crates/proof-of-sql/src/sql/error.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/placeholder_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/placeholder_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/test_utility.rs
Postgres which uses $1, $2 etc as placeholders doesn't allow $0 hence we shouldn't either to make our placeholders easier to use.
Moreover I added this feature to the planner.
- ban $0 as a placeholder
- add placeholder to the planner
Yes.
> feat!: ban $0 && add placeholders to the planner

- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/sql/proof_exprs/cast_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
> feat: support additional numeric types

- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
`CastExpr` needs to support casting from one decimal to another if the scale is the same in both decimals.
Additional support for casting decimals.
Yes
> feat: support scaling-free casting for nonzero scale

- Cargo.toml
- crates/proof-of-sql/src/base/map.rs
Now that `indexmap_with_default` and `indexset_with_default` were released by `indexmap` 2.8.0 and have been in use for 3 weeks without any compliants we should switch to them and simplify `base/map.rs` 
Simplify `base/map.rs`
Yes.
> refactor: use `indexmap_with_default` and `indexset_with_default`

- crates/proof-of-sql-planner/tests/e2e_tests.rs
- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/base/scalar/scalar.rs
- crates/proof-of-sql/src/sql/proof_exprs/cast_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
> feat: add scalar to int and decimal casts

- .github/workflows/lint-and-test.yml
We actually don't have any tests that `cargo test --all-features --package proof-of-sql --lib -- tests::sol_test --show-output` can run. Instead our EVM tests are located elsewhere.
Remove running of nonexisting tests
N/A
> ci: remove unused tests

- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
> refactor: refactor scale cast numerical utils

- .github/workflows/lint-and-test.yml
- Cargo.toml
- crates/proof-of-sql-parser/src/lib.rs
- crates/proof-of-sql-parser/src/posql_time/error.rs
- crates/proof-of-sql-parser/src/posql_time/timestamp.rs
- crates/proof-of-sql-parser/src/posql_time/unit.rs
- crates/proof-of-sql/benches/jaeger/bin/utils/queries.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/encode/varint_trait.rs
- crates/proof-of-sql/src/base/polynomial/interpolate.rs
- crates/proof-of-sql/src/proof_primitive/dory/dory_messages.rs
- crates/proof-of-sql/src/sql/proof_gadgets/mod.rs
/claim #545
* Changed Clippy annotations from `#[allow]` to `#[expect]` in multiple files to improve code clarity and maintainability. 
* Added `allow_attributes = "warn"` to the Clippy configuration in `Cargo.toml` to handle attribute warnings.
> fix: transition from allow to expect for turning off clippy lints

- .github/workflows/lint-and-test.yml
- crates/proof-of-sql-parser/src/lib.rs
- crates/proof-of-sql-parser/src/posql_time/error.rs
- crates/proof-of-sql-parser/src/posql_time/timestamp.rs
- crates/proof-of-sql-parser/src/posql_time/unit.rs
- crates/proof-of-sql-planner/tests/e2e_tests.rs
- crates/proof-of-sql/benches/bench_append_rows.rs
- crates/proof-of-sql/benches/jaeger/bin/utils/queries.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/encode/varint_trait.rs
- crates/proof-of-sql/src/base/polynomial/interpolate.rs
- crates/proof-of-sql/src/base/posql_time/unit.rs
- crates/proof-of-sql/src/base/scalar/scalar.rs
- crates/proof-of-sql/src/lib.rs
- crates/proof-of-sql/src/proof_primitive/dory/mod.rs
- crates/proof-of-sql/src/proof_primitive/dory/scalar_product.rs
- crates/proof-of-sql/src/sql/proof/provable_query_result.rs
- crates/proof-of-sql/src/sql/proof_gadgets/mod.rs
- crates/proof-of-sql/tests/decimal_integration_tests.rs
- crates/proof-of-sql/tests/integration_tests.rs
- crates/proof-of-sql/tests/timestamp_integration_tests.rs
This is a follow-up of #699. All remaining unjustified `allow`s are removed.
See above.
Yes.
> refactor: clean up all `allow`s

- crates/proof-of-sql/src/sql/evm_proof_plan/error.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/exprs.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/mod.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/plans.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/proof_plan.rs
The current code base in `evm_proof_plan` needs to be cleaned up for enhancement since a lot of the names are either too generic or identical to structs and enums in the rest of the crate.
The following renames have been done:
- `Error` -> `EVMProofPlanError`
- `Expr` -> `EVMDynProofExpr`
- `ColumnExpr` -> `EVMColumnExpr`
- `LiteralExpr` -> `EVMLiteralExpr`
- `EqualsExpr` -> `EVMEqualsExpr`
- `Plan` -> `EVMDynProofPlan`
- `FilterExec` -> `EVMFilterExec`
Yes.
> refactor: clean up names in `evm_proof_plan`

- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/proof_exprs/comparison_util.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/util.rs
> fix: correct visit_binary_expr

- crates/proof-of-sql/src/sql/proof_exprs/decimal_scaling_cast_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/decimal_scaling_cast_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
- crates/proof-of-sql/src/sql/proof_exprs/test_utility.rs
This PR finishes the creation of the `DecimalScalingCastExpr`. This will allow proof expressions to cast ints and decimals to decimals.
- Rename utility functions that are meant to cast to decimals to include the word decimal
- New `DecimalScalingCastExpr`
- New variant in `DynProofExpr`
Yes
> feat: scaling cast expr

- crates/proof-of-sql/src/sql/proof_exprs/add_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/subtract_expr.rs
In line with new Solidity code in #719 we need to split `AddSubtractExpr` into `AddExpr` and `SubtractExpr`.
See title.
Yes.
> refactor: split `AddSubtractExpr` into `AddExpr` and `SubtractExpr`

- crates/proof-of-sql/src/sql/evm_proof_plan/exprs.rs
- crates/proof-of-sql/src/sql/proof_exprs/add_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/subtract_expr.rs
This PR depends on #726.
In order to help test #719 we need to make sure `AddExpr` and `SubtractExpr` can work well with Solidity. Hence we need to add their EVM-friendly counterparts.
See title
Yes
> feat: add `EVMAddExpr` and `EVMSubtractExpr`

- crates/proof-of-sql-planner/src/expr.rs
- crates/proof-of-sql-planner/tests/e2e_tests.rs
We added `DecimalScaleCastExpr` in #701. Now we need to enable it in `proof-of-sql-planner`.
Allow `DecimalScaleCastExpr` in `proof-of-sql-planner`
Yes.
> feat: add scale cast to `proof-of-sql-planner`

- crates/proof-of-sql-planner/tests/e2e_tests.rs
- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/proof_exprs/add_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/add_subtract_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/comparison_util.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/inequality_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/multiply_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/multiply_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
- crates/proof-of-sql/src/sql/proof_exprs/proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/subtract_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec_test.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec_test.rs
- crates/proof-of-sql/tests/integration_tests.rs
Currently `ProofExpr` of numeric types require scale casting as well as explicit passing of scales since arithmetic ops on `ProofExpr` always return `Scalar` type columns. In order to port the code to Solidity we need to simplify the logic.  
1. Make sure all arithmetic `ProofExpr` have decimal types and return decimal columns to ensure consistency && prevent overflows from being a thing
2. Cap precision to 75 and wrap around as opposed to banning ops that cause precision to be too large
Yes.
> refactor!: ensure reasonable types for numeric ops

- crates/proof-of-sql-planner/src/expr.rs
- crates/proof-of-sql/src/sql/mod.rs
- crates/proof-of-sql/src/sql/parse/dyn_proof_expr_builder.rs
- crates/proof-of-sql/src/sql/scale.rs
Scale cast needs to be used for `sql/parse` or #737 will break integration tests
- move scale cast code to `scale.rs` inside `proof-of-sql/sql`
- add more tests to `scale.rs`
- refactor `DynProofExprBuilder` to use it for binary ops
Yes.
> refactor!: move scale cast code into `proof-of-sql` && use it in `sql/parse`

- crates/proof-of-sql-planner/src/expr.rs
- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
- crates/proof-of-sql/src/sql/proof_exprs/scaling_cast_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/scaling_cast_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/test_utility.rs
- crates/proof-of-sql/src/sql/scale.rs
We need to have timestamp scale casting, because inequalities rely on scaling.
New support for timestamp scale casting in the planner and the ScalingCastExpr. Note that the ScalingCastExpr has been renamed to eliminate Decimal from the name.
Yes.
> fix!: timestamp scale casting

- crates/proof-of-sql/src/sql/evm_proof_plan/exprs.rs
- crates/proof-of-sql/src/sql/proof_exprs/add_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/add_subtract_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/subtract_expr.rs
In order to guarantee that `AddExpr` and `SubtractExpr` are not ever constructed with invalid datatypes, the `new` functions shall be replaced with `try_new` functions.
The `new` functions are replaced with `try_new` functions.
Existing tests test these changes.
> refactor: exchange `new` for `try_new` on `AddExpr` and `SubtractExpr`

- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/exprs.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/plans.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/tests.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr_test.rs
- crates/proof-of-sql/src/sql/util.rs
We want the type checking for `EqualsExpr` to be done in object creation.
Replace `new` with `try_new` in `EqualsExpr`.
Yes
> refactor: replace `new` with `try_new` in `EqualsExpr`

- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/inequality_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/inequality_expr_test.rs
We want the type checking for `InequalityExpr` to be done in object creation.
Replace `new` with `try_new` in `InequalityExpr`.
Yes
> refactor: replace `new` with `try_new` on `InequalityExpr`

- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/multiply_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/multiply_expr_test.rs
We want the type checking for `MultiplyExpr` to be done in object creation.
Replace `new` with `try_new` in `MultiplyExpr`.
Yes
> refactor: replace `new` with `try_new` in `MultiplyExpr`

- crates/proof-of-sql/src/sql/proof_exprs/cast_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/cast_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/scaling_cast_expr.rs
> refactor: use `try_new` logic on cast exprs

- crates/proof-of-sql/src/base/database/column_type_operation.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/sql/error.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/proof_exprs/and_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/and_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/dyn_proof_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/not_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/not_expr_test.rs
- crates/proof-of-sql/src/sql/proof_exprs/or_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/or_expr_test.rs
We want type checks on the construction of `AndExpr`, `OrExpr`, and `NotExpr`.
The function `new` replaced with `try_new` for the above expressions.
Yes
> refactor: rename `new` to `try_new` for and, or, and not

- crates/proof-of-sql/benches/jaeger/bin/jaeger_benches.rs
- crates/proof-of-sql/benches/jaeger/bin/utils/queries.rs
This PR refactors the `queries` module in the `proof-of-sql` benchmarks. The goal is to make it easier to add new queries by deriving from a base trait instead of defining a number of new constants.
- The `queries` module is updated from using defined constants to have a base trait and deriving new queries from the base trait.
Yes
> refactor: it should be easier to add new queries to benchmarks

- crates/proof-of-sql-planner/src/conversion.rs
- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql/src/base/database/mod.rs
There a couple locations that are doing pre-parsing of sql text in order to retrieve the `TableRef`s for that sql. This seeks to centralize that logic.
New planner function `get_table_refs_from_statement` that retrieves the `TableRef`s from a `Statement`.
Yes.
> feat: add `get_table_refs_from_statement` to planner

- Cargo.toml
- crates/proof-of-sql-planner/Cargo.toml
Generally it's better to use workspace dependencies where possible to avoid accidentally introducing duplicate dependencies as new crates are developed. However, this is especially pertinent as we add automation to release proof-of-sql-planner to crates.io. This automation failed recently because the proof-of-sql dependency was defined with a path instead of from the workspace.
- proof-of-sql defined as default-features=false in workspace Cargo.toml
- all dependencies of proof-of-sql-planner are now defined from the workspace
These changes do not affect existing functionality, which should be verified by existing tests.
> fix: use workspace for all dependencies in proof-of-sql-planner

- crates/proof-of-sql-planner/src/aggregate.rs
- crates/proof-of-sql-planner/src/conversion.rs
- crates/proof-of-sql-planner/src/error.rs
- crates/proof-of-sql-planner/src/expr.rs
- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql-planner/src/plan.rs
- crates/proof-of-sql-planner/src/proof_plan_with_postprocessing.rs
- crates/proof-of-sql-planner/src/util.rs
- crates/proof-of-sql-planner/tests/e2e_tests.rs
- crates/proof-of-sql/src/base/database/mod.rs
- crates/proof-of-sql/src/base/database/test_schema_accessor.rs
The planner is currently using `DFSchema` in more places than is necessary, which makes use by external applications more difficult.
Replacing `IndexMap<TableReference, DFSchema>` with `impl SchemaAccessor`. This necessitates other changes as well.
Yes
> refactor: use schema accessor rather than index map

- Cargo.toml
- crates/proof-of-sql/Cargo.toml
- crates/proof-of-sql/benches/jaeger/bin/jaeger_benches.rs
- crates/proof-of-sql/benches/jaeger/bin/utils/mod.rs
- crates/proof-of-sql/benches/jaeger/bin/utils/results_io.rs
To further improve the benchmark binary, this PR adds both console output and CSV file saving to the benchmarks. The CSV will log the proof generation and verification time. The output will be written to the console by default and a CSV file optionally. 
A user will be able to define a CSV path or add `-w > file_name.csv` to the console command to generate CSV files.
- The `csv` create is added as optional to the project and included under the `benches` feature flag in commit https://github.com/spaceandtimelabs/sxt-proof-of-sql/commit/acf366bba7d9eb01e797a1fb6a40e89e754ba73e
- A new module,, `results_io` is added to the benchmark utils folder that will handle creating and appending data to a CSV file in commit https://github.com/spaceandtimelabs/sxt-proof-of-sql/commit/8d93fa29bce47a484b8d …
> bench: add CSV and console output for proof generation and verification 

- crates/proof-of-sql-planner/src/context.rs
- crates/proof-of-sql-planner/src/plan.rs
- crates/proof-of-sql/benches/jaeger/bin/utils/benchmark_accessor.rs
- crates/proof-of-sql/examples/posql_db/commit_accessor.rs
- crates/proof-of-sql/examples/posql_db/csv_accessor.rs
- crates/proof-of-sql/examples/posql_db/main.rs
- crates/proof-of-sql/examples/posql_db/record_batch_accessor.rs
- crates/proof-of-sql/src/base/commitment/column_commitments.rs
- crates/proof-of-sql/src/base/commitment/query_commitments.rs
- crates/proof-of-sql/src/base/database/accessor.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor_test.rs
- crates/proof-of-sql/src/base/database/table_test_accessor.rs
- crates/proof-of-sql/src/base/database/table_test_accessor_test.rs
- crates/proof-of-sql/src/base/database/test_schema_accessor.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/evm_tests.rs
- crates/proof-of-sql/src/sql/parse/query_context_builder.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof_exprs/test_utility.rs
It doesn't make any sense to let `ColumnType` be a part of the key to fetch columns and commitments. Moreover it doesn't make sense for accessors to consume `TableRef`s and `Ident`s. Hence we are fixing this.
- Remove `ColumnRef` from accessors
- Accessors shouldn't consume `TableRef`s or `Ident`s
Yes.
> refactor!: refactor accessors to remove `ColumnRef`

- ci/publish.sh
Sorry the script was wrong. Now it has been fixed.
Fixed publish script
Yes.
> fix: fix publish script

- ci/publish.sh
If local crate has version a.b.c it is always found and hence if we don't use `--index` in `cargo info` it will always succeed for the version we are about to publish and hence it will never actually publish anything.
Add `--index` to `cargo info` in CI so that local crates are ignored
Can not test till merge AFAIK
> ci: use crates.io for `cargo info`

- ci/publish.sh
This still failed because any error in the `publish.sh` script breaks CI. Now it shouldn't happen any more. 
See title.
Can't be tested prior to publishing. :(
> fix: avoid exit on cargo info error in publish script

- crates/proof-of-sql/src/sql/evm_proof_plan/evm_tests.rs
- solidity/src/base/Constants.sol
- solidity/src/proof_exprs/AddExpr.pre.sol
- solidity/src/proof_exprs/ProofExpr.pre.sol
- solidity/src/proof_exprs/SubtractExpr.pre.sol
- solidity/src/proof_plans/FilterExec.pre.sol
- solidity/src/proof_plans/ProofPlan.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/proof_exprs/AddExpr.t.pre.sol
- solidity/test/proof_exprs/ProofExpr.t.pre.sol
- solidity/test/proof_exprs/SubtractExpr.t.pre.sol
It is necessary to allow `AddExpr` and `SubtractExpr`.
- add `AddExpr` and `SubtractExpr`
Yes.
> feat(sol): add `AddExpr` and `SubtractExpr`

- crates/proof-of-sql/src/sql/evm_proof_plan/error.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/exprs.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/plans.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/proof_plan.rs
- crates/proof-of-sql/src/sql/proof_exprs/and_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/mod.rs
- crates/proof-of-sql/src/sql/proof_exprs/multiply_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/not_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/or_expr.rs
We need to add * and logical exprs to `evm_proof_plan` so that we can do cross-language tests.
See title.
Yes.
> feat: add * and logical exprs to `evm_proof_plan`

- .github/workflows/lint-and-test.yml
`evm_tests.rs` contain cross-language tests that for some reason codecov mistakes as untested code leading to unwarranted red status on CI.
Ignore `evm_tests.rs` in codecov
Yes.
> ci: evm_tests are tests hence shouldn't be counted by codecov as untested code

- solidity/src/base/Errors.sol
- solidity/src/proof_exprs/ProofExpr.pre.sol
- solidity/src/verifier/PlanUtil.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/base/Errors.t.sol
- solidity/test/verifier/Verifier.t.pre.sol
We need to address the following issues. 
- add to docs for plan name skipping with respect to what is returned
- fix typo in Doc
- replace `mulmod` with `mul` in `make_transcript`
N/A.
> fix: address issues

- crates/proof-of-sql/src/sql/evm_proof_plan/plans.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/tests.rs
Add more `ProofExec` to `evm_proof_plan`
See title
Yes.
> feat: add `EVMEmptyExec` and `EVMTableExec`

- crates/proof-of-sql/src/sql/evm_proof_plan/plans.rs
- crates/proof-of-sql/src/sql/proof_plans/projection_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
Add more `ProofExec` to `evm_proof_plan`
See title
Yes.
> feat: add `EVMProjectionExec` and `EVMSliceExec`

- .github/workflows/lint-and-test.yml
- crates/proof-of-sql/src/sql/evm_proof_plan/evm_tests.rs
- solidity/src/base/Constants.sol
- solidity/src/proof_exprs/AndExpr.pre.sol
- solidity/src/proof_exprs/EqualsExpr.pre.sol
- solidity/src/proof_exprs/MultiplyExpr.pre.sol
- solidity/src/proof_exprs/NotExpr.pre.sol
- solidity/src/proof_exprs/OrExpr.pre.sol
- solidity/src/proof_exprs/ProofExpr.pre.sol
- solidity/src/proof_exprs/SubtractExpr.pre.sol
- solidity/src/proof_plans/FilterExec.pre.sol
- solidity/src/proof_plans/ProofPlan.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/proof_exprs/AndExpr.t.pre.sol
- solidity/test/proof_exprs/MultiplyExpr.t.pre.sol
- solidity/test/proof_exprs/NotExpr.t.pre.sol
- solidity/test/proof_exprs/OrExpr.t.pre.sol
- solidity/test/proof_exprs/ProofExpr.t.pre.sol
We need to add more `ProofExpr` to Solidity.
See title.
Yes.
> feat(sol): add `MultiplyExpr`, `AndExpr`, `OrExpr`, `NotExpr` in Solidity

- crates/proof-of-sql/src/sql/evm_proof_plan/error.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/plans.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
Add more `ProofExec` to `evm_proof_plan`
See title
Yes.
> feat: add `EVMGroupByExec`

- crates/proof-of-sql/src/sql/evm_proof_plan/exprs.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/plans.rs
- crates/proof-of-sql/src/sql/proof_exprs/add_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/column_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/inequality_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/literal_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/subtract_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec_test_dishonest_prover.rs
- crates/proof-of-sql/src/sql/proof_plans/table_exec.rs
This refactor improves encapsulation of our `proof_exprs` and `proof_plans` types by hiding internal fields behind explicit getter methods. It paves the way for future internal representation changes without breaking downstream code, and ensures we’re consistently using a stable, well-defined API rather than relying on direct struct field access.
---
- **Expose public getters** for all AST and proof-plan structs:
- `AddExpr`, `SubtractExpr`, `EqualsExpr`, `InequalityExpr` each get `lhs()` and `rhs()` accessors.  
- `ColumnExpr` gets `column_ref()` and `get_column_field()`.  
- `LiteralExpr` gets `value()`.  
- **Hide internal fields** by …
> refactor!: Switch to using getters in `proof_exprs` and `proof_plans`

- solidity/foundry.toml
- solidity/test/sumcheck/Sumcheck.t.pre.sol
To enforce zero-tolerance for new compiler warnings in our Solidity code and catch any regressions early in CI, we enable `deny-warnings` and update our tests to satisfy purity requirements. This keeps our codebase clean, prevents long-lived warnings, and ensures Forge will fail fast on any new issues.
- **Enable warnings-as-errors**  
- In `solidity/foundry.toml`, set `deny-warnings = true` under `[profile.default]`.  
- Exclude `.pre.sol` files from matching and coverage checks via  
`no-match-path = "**/*.pre.sol"` and `no-match-coverage = "pre.sol"`.  
- **Update Sumcheck tests**  
- In `solidity/test/sumcheck/Sumcheck.t.pre.sol`, mark both  
`testValidSumcheckProof` and the fuzz test as `public pure` instead of `public`,  
eliminating the “can be restricted to pure” compiler …
> ci: eliminate foundary warnings and add ci check

- crates/proof-of-sql/Cargo.toml
GPU support was added to the Microsoft Nova project in a [recent PR](https://github.com/microsoft/Nova/pull/374). By building the crate with the `blitzar` feature flag, we can unlock performance gains during the `EvaluationEngine::prove` step.
Benchmarks on a Multi-A100 system using the `hyper-kzg` commitment scheme and a table size of `1,000,000` show a `1.75x` performance improvement related to `EvaluationEngine::prove`.
Without `blitzar`, `EvaluationEngine::prove` took `859.07 ms`
With `blitzar`, `EvaluationEngine::prove` took `489.53 ms`
- `blitzar` is added as a feature flag to the `nova-snark` crate.
Yes
> build: add the `blitzar` feature flag to the `nova-snark` crate

- .github/workflows/lint-and-test.yml
GitHub Actions’ `actions/checkout` v4 brings performance improvements, bug fixes, and new features over v3. Bumping to v4 ensures our CI workflows stay up-to-date with the latest stable version and take advantage of those enhancements.
- In `.github/workflows/lint-and-test.yml`:
- Replaced all 9 occurrences of  
```yaml
uses: actions/checkout@v3
```  
with  
```yaml
uses: actions/checkout@v4
```
Yes — the updated workflows have been exercised in CI and all jobs complete successfully using `actions/checkout@v4`.
> ci: bump GitHub checkout version to 4

- crates/proof-of-sql-benches/Cargo.toml
- crates/proof-of-sql-benches/src/README.md
- crates/proof-of-sql-benches/src/main.rs
- crates/proof-of-sql-benches/src/utils/benchmark_accessor.rs
- crates/proof-of-sql-benches/src/utils/queries.rs
- crates/proof-of-sql-benches/src/utils/random_util.rs
The next step in improving benchmarks is to use the `proof-of-sql-planner` crate when creating the proof plan. This PR moves all the old benchmarks to new proof planner. Additionally, two new queries are added to the benchmarks along with a number of quality of code improvements. 
- The `proof-of-sql-benches` crate now only uses `proof-of-sql-planner` for proof plans.
- Random column generation for `Decimal75` and `TimeStampTZ` column types are added.
- The query module is refactored.
- Two new queries are added to the query module.
Yes
> bench: the benchmarks should use the `proof-of-sql-planner` crate when creating proof plans

- crates/proof-of-sql-planner/src/plan.rs
- crates/proof-of-sql-planner/tests/e2e_tests.rs
- crates/proof-of-sql/src/base/database/test_schema_accessor.rs
- crates/proof-of-sql/src/sql/proof_plans/mod.rs
- crates/proof-of-sql/src/sql/proof_plans/sort_merge_join_exec.rs
We need to support joins in the planner
New planner code for converting a logical plan to dyn proof plan including joins
Yes
> feat: join in planner

- crates/proof-of-sql-planner/src/conversion.rs
> fix: use config in planner

- .github/workflows/code-coverage.yml
- .github/workflows/lint-and-test.yml
Please be sure to look over the pull request guidelines here:  
https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/CONTRIBUTING.md#submit-pr
---
https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/CONTRIBUTING.md  
(breaking changes use `!`)
```bash
source scripts/run_ci_checks.sh
```
```bash
source scripts/check_commits.sh
```  
and the commit history follows the clean-commit guidelines:  
https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/COMMIT_GUIDELINES.md
---
Moving code coverage into its own workflow decouples coverage reporting from the main lint-and-test pipeline, ensuring coverage checks no longer block release merges while still enforcing our minimum coverage threshold.
---
- **Add** `.github/workflows/code-coverage.yml`  
- Defines a …
> ci: move code coverage to its own file and not make it block releases

- crates/proof-of-sql-planner/src/lib.rs
- crates/proof-of-sql-planner/src/uppercase_column_visitor.rs
`sqlparser::Statement` does not have a built in way to capitalize all the column and table idents, and we would like that functionality.
New function for capitalizing all the idents in a `Statement`.
Yes
> feat: uppercase column visitor

- crates/proof-of-sql-benches/src/main.rs
- crates/proof-of-sql-benches/src/utils/queries.rs
Recently the benchmarks were updated using a filter, complex filter, and group by query. This PR updates the `proof-of-sql-benches` crate to have those queries.
- The Single Column Filter query is renamed to Filter
- The Multi-Column Filter query is updated and renamed to Complex Filter
- The Group-By query is updated to a more realistic query 
Yes
> bench: update filter, complex filter, and group by queries

- crates/proof-of-sql/src/sql/proof_gadgets/range_check.rs
There are a few places in range check that could be written more succinctly.
Reduction of code.
Yes
> refactor: simplify range check syntax

- crates/proof-of-sql/src/sql/proof_gadgets/range_check.rs
- crates/proof-of-sql/src/sql/proof_gadgets/range_check_test.rs
> fix: move produce_chi_evaluation_length to range check from planner

- crates/proof-of-sql-benches/src/main.rs
- crates/proof-of-sql-benches/src/utils/queries.rs
In order to support benchmarking operations like `JOIN`,  the benchmark framework needs to support defining multiple tables for a query. This PR refactors the benchmarking query framework to support adding multiple tables. None of the queries have changed. Follow up work will add the `JOIN` query.
- The benchmark framework now supports defining multiple tables
Yes
> refactor: benches should support multiple tables

- Cargo.toml
> fix: fix ahash to 0.8.11 and downgrade uuid to 1.12.1 to avoid breaking change on getrandom 0.3

- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
> fix: make sure group by doesn't error out if 0 rows are returned

- crates/proof-of-sql/src/sql/proof_gadgets/range_check.rs
This is a slight improvement in the verification of range check
Removing a vec that is unneeded
Yes
> refactor: remove unnecessary vec from range check verification

- crates/proof-of-sql/src/base/mod.rs
- crates/proof-of-sql/src/base/proof/transcript.rs
- crates/proof-of-sql/src/base/standard_binary_serde.rs
- crates/proof-of-sql/src/proof_primitive/hyperkzg/commitment.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/tests.rs
Just for the sake of clarity, and some conciseness, it would be helpful to have functions that serialize and deserialize our objects using a standard config.
New functions `try_standard_binary_serialization` and `try_standard_binary_deserialization`.
Yes
> feat: binary serde standard functions

- crates/proof-of-sql-planner/src/expr.rs
> refactor: fallback to scale casting if casting is invalid

- crates/proof-of-sql/src/sql/proof/mock_verification_builder.rs
- crates/proof-of-sql/src/sql/proof_exprs/and_expr_test.rs
- crates/proof-of-sql/src/sql/proof_gadgets/divide_and_modulo_expr.rs
- crates/proof-of-sql/src/sql/proof_gadgets/permutation_check.rs
Because range check uses post result challenges, it will be helpful to add functionality to the mock verification builder for them.
Adding functionality for post result challenges in the `MockVerificationBuilder`.
Yes
> test: add post result challenges to mock verification builder

- crates/proof-of-sql-benches/src/main.rs
- crates/proof-of-sql-benches/src/utils/queries.rs
This PR adds a `JOIN` query to the benchmarks and ensures the `HyperKZG` setup has enough generators to handle the table size.
- A `JOIN` query is added to the benchmarks
- The HyperKZG setup doubles the setup table size if running the `JOIN` query
Yes
> bench: add JOIN query to benchmarks

- crates/proof-of-sql/src/base/database/owned_column.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/evm_tests.rs
- solidity/src/base/Constants.sol
- solidity/src/base/DataType.pre.sol
- solidity/src/base/Errors.sol
- solidity/src/proof_exprs/LiteralExpr.pre.sol
- solidity/src/verifier/PlanUtil.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/base/DataType.t.pre.sol
- solidity/test/base/Errors.t.sol
- solidity/test/proof_exprs/LiteralExpr.t.pre.sol
- solidity/test/verifier/PlanUtil.t.pre.sol
We need to support a wider range of data types (booleans, 8-/16-/32-/64-bit integers, decimals, and timestamps) and ensure the EVM proof-plan and verifier correctly serialize, deserialize, and validate them in both the Rust and Solidity code.
- **Rust (`proof-of-sql` crate)**  
- **`OwnedColumn<S>` enum**: Rearranged in line with how variants are ordered in **ColumnType** for serialization consistency
- **EVM tests**: Extended `evm_tests.rs` with end-to-end Forge tests that exercise `boolean`, `tinyint`, `smallint`, `int`, `bigint`, `decimal75`, and `timestamptz` literals through the full EVM verification pipeline
- **Solidity**  
- **`Constants.sol`**: Defined size & padding constants for the new primitive types (e.g. `BOOLEAN_SIZE`, `INT8_SIZE`, `UINT8_SIZE`, `INT16_SIZE`, …
> feat(sol): support more datatypes (booleans, ints, decimals, timestamps)

- crates/proof-of-sql-benches/src/utils/queries.rs
- crates/proof-of-sql/src/sql/proof/query_proof.rs
- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
This PR makes sure traces are placed around all critical sections of code used in the Filter query in the benchmarks. This will help us identify performance improvements that can be made.
- Traces and spans are added throughout the Filter query execution path.
- The Filter query in the benchmarks is updated to use `BigInt` column type.
Yes. Below is an example of the filter query on a laptop.
> bench: add spans for filter query

- crates/proof-of-sql-benches/scripts/run_benchmarks.sh
This PR adds a script the the `proof-of-sql-benches` folder that makes generating benchmarks easier. In order to generate a CSV file with benchmark data used in the `proof-of-sql` project's README, you can simply run:
```
./crates/proof-of-sql-benches/scripts/run_benchmarks.sh
```
- A benchmark running helper script is added to the `proof-of-sql-benches` crate
Yes
> bench: add benchmark running helper script

- crates/proof-of-sql/src/base/byte/byte_distribution.rs
- crates/proof-of-sql/src/base/byte/mod.rs
- crates/proof-of-sql/src/base/mod.rs
Range check will benefit from a `ByteDistribution`, which will reduce the number of columns it needs to commit.
New `ByteDistribution`.
Yes
> feat: add byte distribution

- crates/proof-of-sql/src/sql/evm_proof_plan/exprs.rs
> refactor: reorder variants in `EVMLiteralExpr`

- crates/proof-of-sql/src/sql/evm_proof_plan/evm_tests.rs
- crates/proof-of-sql/src/sql/evm_proof_plan/exprs.rs
- crates/proof-of-sql/src/sql/proof_exprs/cast_expr.rs
- solidity/src/base/Constants.sol
- solidity/src/proof_exprs/AddExpr.pre.sol
- solidity/src/proof_exprs/AndExpr.pre.sol
- solidity/src/proof_exprs/CastExpr.pre.sol
- solidity/src/proof_exprs/MultiplyExpr.pre.sol
- solidity/src/proof_exprs/NotExpr.pre.sol
- solidity/src/proof_exprs/OrExpr.pre.sol
- solidity/src/proof_exprs/ProofExpr.pre.sol
- solidity/src/proof_exprs/SubtractExpr.pre.sol
- solidity/src/proof_plans/FilterExec.pre.sol
- solidity/src/proof_plans/ProofPlan.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/proof_exprs/CastExpr.t.pre.sol
- solidity/test/proof_exprs/ProofExpr.t.pre.sol
We need to allow casting in the Solidity verifier.
See title.
Yes.
> feat(sol): add `CastExpr` to solidity

- .github/workflows/stale.yml
- CONTRIBUTING.md
- Uses the `actions/stale@v9` action to mark pull requests inactive after 30 days and close them 7 days later
- Configures custom messages, labels, and exemptions (e.g. drafts, dependency/security PRs)
- Grants only the minimum permissions needed (write on PRs and issues)
- Updates the CONTRIBUTING guide to explain the new stale-and-close policy to contributors
> ci: close stale PRs beyond 30 days

- crates/proof-of-sql/src/base/byte/byte_distribution.rs
- crates/proof-of-sql/src/base/byte/byte_matrix_utils.rs
- crates/proof-of-sql/src/base/byte/mod.rs
We want to be able to break a column of data into its byte matrix.
New function `compute_varying_byte_matrix`.
Yes
> feat: byte matrix

- crates/proof-of-sql/src/sql/proof/sumcheck_random_scalars.rs
When benchmarking the `Filter` query, the initialization of the vector `v` when computing entrywise multipliers was taking longer than expected. This PR updates the `Default::default()` initializer to `S::ZERO`, which showed a `1.35x` performance improvement during benchmarks.
Before, `18.71ms`
After, `13.82ms`, `1.35x` improvement
- Tracing is added to `compute_entrywise_multipliers`
- `Default:::default()` is updated to `S::ZERO`
Yes
> perf: use `S::ZERO` for vector initialization in `compute_entrywise_multipliers`

- crates/proof-of-sql/src/base/polynomial/multilinear_extension.rs
- crates/proof-of-sql/src/sql/proof/make_sumcheck_state.rs
During benchmarking for the `Filter` query, it was identified that the `flattened_ml_extensions` method in the `make_symcheck_state` module could benefit from using parallelism if the `Rayon` crate was being used. This PR add the `if_rayon` macro to the `flatten_ml_extensions` method.
Before, `31.54ms`
After, `9.91ms`, `3.18x` performance improvement of the `flatten_ml_extensions` method.
- `Sync` is added to the `MultilinearExtension` trait
- The `flattened_ml_extensions` method in the `make_symcheck_state` module now uses the `if_rayon` macro
Yes
> perf: `flattened_ml_extensions` should be parallel if using `Rayon`

- crates/proof-of-sql/src/sql/evm_proof_plan/evm_tests.rs
- solidity/slither.config.json
- solidity/src/base/Constants.sol
- solidity/src/base/DataType.pre.sol
- solidity/src/proof_exprs/AddExpr.pre.sol
- solidity/src/proof_exprs/AndExpr.pre.sol
- solidity/src/proof_exprs/CastExpr.pre.sol
- solidity/src/proof_exprs/EqualsExpr.pre.sol
- solidity/src/proof_exprs/LiteralExpr.pre.sol
- solidity/src/proof_exprs/MultiplyExpr.pre.sol
- solidity/src/proof_exprs/NotExpr.pre.sol
- solidity/src/proof_exprs/OrExpr.pre.sol
- solidity/src/proof_exprs/ProofExpr.pre.sol
- solidity/src/proof_exprs/SubtractExpr.pre.sol
- solidity/src/proof_plans/FilterExec.pre.sol
- solidity/src/proof_plans/ProofPlan.pre.sol
- solidity/src/verifier/ResultVerifier.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/base/DataType.t.pre.sol
- solidity/test/proof_exprs/LiteralExpr.t.pre.sol
This PR adds support for `VARCHAR` and `VARBINARY` literals in the Solidity‐based proof code, enabling variable-length string and binary data types in Proof-of-SQL.
- **Constants.sol**  
Added new data-type variant constants `DATA_TYPE_VARCHAR_VARIANT = 7` and `DATA_TYPE_VARBINARY_VARIANT = 11`
- **DataType.pre.sol**  
Implemented `case 7` (varchar) and `case 11` (varbinary) in `__readEntry` to:
1. Read a 64-bit length prefix  
2. Copy the payload into EVM memory at `FREE_PTR`  
3. Compute `keccak256` over that data  
4. Update `FREE_PTR` and advance the result pointer  
- **DataType.t.pre.sol**  
Added unit tests covering:
- `testReadVarcharEntryExpr`, `testReadNonAsciiVarcharEntryExpr`, `testFuzzReadVarcharEntryExpr`  
- `testReadVarbinaryEntryExpr`, `testFuzzReadVarbinaryEntryExpr`
- …
> feat(sol): support varchar and varbinary literals

- solidity/src/base/MathUtil.sol
- solidity/src/hyperkzg/HyperKZGBatch.pre.sol
- solidity/src/hyperkzg/HyperKZGHelpers.pre.sol
- solidity/src/hyperkzg/HyperKZGVerifier.pre.sol
- solidity/src/proof_exprs/AddExpr.pre.sol
- solidity/src/proof_exprs/AndExpr.pre.sol
- solidity/src/proof_exprs/CastExpr.pre.sol
- solidity/src/proof_exprs/EqualsExpr.pre.sol
- solidity/src/proof_exprs/LiteralExpr.pre.sol
- solidity/src/proof_exprs/MultiplyExpr.pre.sol
- solidity/src/proof_exprs/NotExpr.pre.sol
- solidity/src/proof_exprs/OrExpr.pre.sol
- solidity/src/proof_exprs/ProofExpr.pre.sol
- solidity/src/proof_exprs/SubtractExpr.pre.sol
- solidity/src/proof_plans/FilterExec.pre.sol
- solidity/src/proof_plans/ProofPlan.pre.sol
- solidity/src/sumcheck/Sumcheck.pre.sol
- solidity/src/verifier/ResultVerifier.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/base/MathUtil.t.sol
There's loads of places where code like `addmod(lhs, rhs, MODULUS)` is repeated. There's no need to constantly indicate the mod is `MODULUS`, so it's would be far more succinct to have arithmetic functions that apply the modulus.
New add, sub, and mul functions.
Yes
> feat(sol): add arithmetic utils

- solidity/src/base/Constants.sol
- solidity/src/builder/VerificationBuilder.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/base/Constants.t.sol
- solidity/test/builder/VerificationBuilder.t.pre.sol
In order to port `EmptyExec` and the monotonic proof gadget used in joins to Solidity we need to have singleton chi eval added.
See title.
Yes.
> feat(sol): add singleton chi eval to verification builder

- crates/proof-of-sql-parser/src/sqlparser.rs
- crates/proof-of-sql-planner/src/error.rs
- crates/proof-of-sql-planner/src/expr.rs
- crates/proof-of-sql-planner/src/plan.rs
- crates/proof-of-sql-planner/src/proof_plan_with_postprocessing.rs
- crates/proof-of-sql-planner/src/uppercase_column_visitor.rs
- crates/proof-of-sql/src/base/arrow/arrow_array_to_column_conversion.rs
- crates/proof-of-sql/src/base/database/owned_table_test_accessor_test.rs
- crates/proof-of-sql/src/base/database/slice_operation.rs
- crates/proof-of-sql/src/base/database/table_test_accessor_test.rs
- crates/proof-of-sql/src/base/encode/scalar_varint.rs
- crates/proof-of-sql/src/base/encode/varint_trait.rs
- crates/proof-of-sql/src/base/math/big_decimal_ext.rs
- crates/proof-of-sql/src/proof_primitive/dory/blitzar_metadata_table.rs
- crates/proof-of-sql/src/proof_primitive/dory/eval_vmv_re.rs
- crates/proof-of-sql/src/proof_primitive/dory/pack_scalars.rs
- crates/proof-of-sql/src/proof_primitive/dory/public_parameters.rs
- crates/proof-of-sql/src/proof_primitive/dory/setup.rs
- crates/proof-of-sql/src/proof_primitive/dynamic_matrix_utils/matrix_structure.rs
- crates/proof-of-sql/src/proof_primitive/sumcheck/test_cases.rs
- crates/proof-of-sql/utils/generate-parameters/main.rs
- rust-toolchain.toml
- **rust-toolchain.toml**  
- Bumped the Rust channel from `1.85.0` to **`1.87.0`**, ensuring the project now compiles with Rust 1.87’s toolchain.
- **GitHub Actions workflows**  
- Updated all `actions/setup-rust` steps to install **Rust 1.87.0** instead of 1.85.0, so CI uses the new compiler.
- **Cargo.toml (workspace root)**  
- Raised any MSRV-related comments or metadata from `1.85` to **`1.87`** to match the new toolchain.  
- No other dependency versions were changed—this commit only moves the minimum Rust version forward. 
- **clippy.toml**  
- (Indirectly) Since Clippy now ships with Rust 1.87, the CI config no longer pins an older Clippy; it inherits the version that comes with 1.87.0. No manual flags were added or removed.
> feat!: bump to 1.87.0

- crates/proof-of-sql/src/base/bit/bit_distribution.rs
- crates/proof-of-sql/src/base/bit/bit_distribution_test.rs
- crates/proof-of-sql/src/sql/proof_gadgets/sign_expr.rs
> refactor: simplify sign expr verification

- ci/publish.sh
Semantic release updates `Cargo.toml` during the release process. Our release process publish script has failed since we upgraded to Rust version 1.87. There does not appear to be any other indication of people experiencing this online, but we suspect adding the `--allow-dirty` flag to the `cargo publish` call will allow us to work around the issue.
Re-running the release script in Github's Actions UI has succeeded in 3 of the 4 failing jobs. One job has not succeeded: https://github.com/spaceandtimefdn/sxt-proof-of-sql/actions/runs/15476798627/job/43576240647.
This issue is likely related to https://github.com/rust-lang/cargo/pull/15276.
- `--allow-dirty` is added to the publish script
No, I can only think to run the release process to test this?
> ci: add allow dirty flag to crate publishing script

- solidity/src/base/Errors.sol
- solidity/src/proof_gadgets/Monotonic.pre.sol
- solidity/test/proof_gadgets/Monotonic.t.pre.sol
Add monotonic gadget to Solidity
See above
Yes.
> feat(sol): add monotonic proof gadget

- crates/proof-of-sql-planner/tests/evm_tests.rs
- solidity/src/base/Constants.sol
- solidity/src/proof_plans/FilterExec.pre.sol
- solidity/src/proof_plans/ProofPlan.pre.sol
- solidity/src/proof_plans/TableExec.pre.sol
- solidity/src/verifier/ResultVerifier.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/proof_plans/ProofPlan.t.pre.sol
- solidity/test/proof_plans/TableExec.t.pre.sol
Support for table execution plans is required to enable Proof-of-SQL’s verifier to handle queries that read directly from tables rather than only from filtered or aggregated sources. Adding a dedicated `TableExec` library and wiring it into the existing Yul libraries completes the proof plan’s coverage of core SQL operators.
- **New library**: Add `solidity/src/proof_plans/TableExec.pre.sol`, implementing the `__tableExecEvaluate` external wrapper for table execution plans in Yul (table reference decoding, chi lookup, column iteration, evaluation assembly). 
- **ProofPlan integration**: Update the `ProofPlan` Yul library to import and dispatch `table_exec_evaluate` for the new `TABLE_EXEC_VARIANT` case in `proof_plan_evaluate`.
- **ProofPlan tests**: Extend …
> feat: add `TableExec` to solidity

- solidity/src/proof_gadgets/FoldUtil.pre.sol
- solidity/test/proof_gadgets/FoldUtil.t.pre.sol
> feat: add `fold_column_expr_evals`

- crates/proof-of-sql-benches/src/main.rs
- crates/proof-of-sql-benches/src/utils/queries.rs
- crates/proof-of-sql-benches/src/utils/random_util.rs
Benchmarks should cover all of the supported [SQL syntax](https://github.com/spaceandtimefdn/sxt-proof-of-sql/blob/6f0938f5ca72b7d2475eb39fa31c47c7eca618ce/docs/SQLSyntaxSpecification.md#posql-sql-syntax). This PR adds benchmarks that cover the remainder of the syntax. These benchmarks will be used to identify performance optimizations that can be made.
- Support for random Uint8 columns are added to the benchmark crate
-  Benchmark queries are added to cover all of the supported SQL syntax listed here https://github.com/spaceandtimefdn/sxt-proof-of-sql/blob/6f0938f5ca72b7d2475eb39fa31c47c7eca618ce/docs/SQLSyntaxSpecification.md#posql-sql-syntax
- The SQL syntax was cleaned up for the all of the benchmark queries
Yes
> bench: add queries to cover currently supported syntax

- solidity/src/base/LagrangeBasisEvaluation.pre.sol
- solidity/test/base/LagrangeBasisEvaluation.t.pre.sol
> feat(sol): compute rho evaluations

- solidity/src/base/Constants.sol
- solidity/src/base/Errors.sol
- solidity/src/proof_plans/GroupByExec.pre.sol
- solidity/src/proof_plans/ProofPlan.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/proof_plans/GroupByExec.t.pre.sol
- solidity/test/proof_plans/ProofPlan.t.pre.sol
> feat: add `GroupByExec` in solidity

- solidity/src/base/Array.pre.sol
- solidity/test/base/Array.t.pre.sol
> feat(sol): `get_uint512_array_element`

- solidity/src/base/LagrangeBasisEvaluation.pre.sol
- solidity/src/builder/VerificationBuilder.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/base/LagrangeBasisEvaluation.t.pre.sol
- solidity/test/builder/VerificationBuilder.t.pre.sol
- **Refactor**:  
- Renamed `__computeEvaluations` → `__computeChiEvaluations`  
- Updated doc comments to refer to “chi evaluations” instead of generic evaluations  
- **Add**:  
- Doc comments for a new Yul wrapper `compute_rho_evaluations` to compute rho evaluations in-place
- **Add**:  
- `__getRhoEvaluations(Builder memory)` function  
- Yul wrapper `builder_get_rho_evaluations` to expose the builder’s `rhoEvaluations` array
- **Add**:  
- Yul imports for `builder_get_rho_evaluations` and `builder_consume_rho_evaluation`  
- Import of `compute_rho_evaluations` from the Lagrange basis lib  
- **Refactor**:  
- Switched from `compute_evaluations` → `compute_chi_evaluations` in imports and calls  
- **Enhance**:  
- In `verify_proof`, after chi evaluations, now calls …
> feat: make sure rho evals are actually computed

- crates/proof-of-sql/src/sql/proof/mock_verification_builder.rs
- crates/proof-of-sql/src/sql/proof/query_proof_test.rs
- crates/proof-of-sql/src/sql/proof/verifiable_query_result_test.rs
- crates/proof-of-sql/src/sql/proof/verification_builder.rs
- crates/proof-of-sql/src/sql/proof_gadgets/membership_check_test.rs
- crates/proof-of-sql/src/sql/proof_gadgets/monotonic.rs
- crates/proof-of-sql/src/sql/proof_gadgets/monotonic_test.rs
- crates/proof-of-sql/src/sql/proof_gadgets/permutation_check_test.rs
- crates/proof-of-sql/src/sql/proof_gadgets/range_check.rs
- crates/proof-of-sql/src/sql/proof_gadgets/shift.rs
- crates/proof-of-sql/src/sql/proof_plans/filter_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/sort_merge_join_exec.rs
- crates/proof-of-sql/src/sql/proof_plans/union_exec.rs
- solidity/src/base/LagrangeBasisEvaluation.pre.sol
- solidity/src/builder/VerificationBuilder.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/base/LagrangeBasisEvaluation.t.pre.sol
- solidity/test/builder/VerificationBuilder.t.pre.sol
- solidity/test/proof_gadgets/Monotonic.t.pre.sol
- solidity/test/proof_plans/FilterExec.t.pre.sol
- solidity/test/proof_plans/GroupByExec.t.pre.sol
- solidity/test/proof_plans/ProofPlan.t.pre.sol
We want to be able to access the length of the chi evals we use in our verifier code.
- Refactoring the rust function `try_consume_chi_evaluation` to return the length of the chi column.
- Refactoring the solidity to store the length and chi eval together on the builder.
- New solidity function that also returns the length with the chi eval.
Yes
> refactor: expose length with try consume chi evaluation

- solidity/src/proof_plans/GroupByExec.pre.sol
- solidity/src/proof_plans/ProofPlan.pre.sol
- solidity/src/verifier/Verifier.pre.sol
> fix(sol): group by should return output chi

- solidity/src/proof_plans/GroupByExec.pre.sol
We need to be able to add another local variable to group by, so we need to make space for it.
Rearranging group by code so that local variables are dropped as quickly as possible. In the process, the FREE_PTR is only loaded once now.
Yes
> refactor(sol): reduce group by local variables

- solidity/src/base/Array.pre.sol
- solidity/test/base/Array.t.pre.sol
We want to be able to retrieve the length of chi evaluations for a particular table. The easiest way to do that is to store the lengths and evals together, so we will need space in the array.
A new function for reading a word array as an array of two word elements.
Yes
> feat(sol): read_word_array_as_uint512_array

- crates/proof-of-sql-benches/src/main.rs
Like the `Join` benchmark query, `UnionAll` also uses two input tables. To help get a more accurate picture of the performance in regards to things like MSM, the `UnionAll` query is added to the `table_size` check in the benchmarks crate.
- `UnionAll` will also run benchmarks at half size, like the `Join` query.
Yes
> refactor: add UnionAll query to table_size benchmark half size check

- crates/proof-of-sql/src/sql/proof_gadgets/monotonic.rs
- crates/proof-of-sql/src/sql/proof_gadgets/shift.rs
- solidity/src/proof_gadgets/Monotonic.pre.sol
- solidity/src/proof_gadgets/Shift.pre.sol
- solidity/src/proof_plans/GroupByExec.pre.sol
- solidity/src/proof_plans/ProjectionExec.pre.sol
- solidity/src/proof_plans/ProofPlan.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/proof_gadgets/Shift.t.pre.sol
There is logic in the monotonic gadget that should be in the shift gadget.
Moving creation and retrieval of shifted columns and chis into the shift gadget.
Yes
> refactor: move shift logic from monotonic code to shift code

- crates/proof-of-sql/src/sql/proof_plans/slice_exec.rs
> fix!: move slice mles to first round

- crates/proof-of-sql/src/sql/proof_gadgets/fold_log_expr.rs
- crates/proof-of-sql/src/sql/proof_gadgets/mod.rs
- crates/proof-of-sql/src/sql/proof_plans/union_exec.rs
Many of our plans use the same folding logic to achieve zero sum constraints. Ideally this code/logic is not going to be duplicated everywhere. This is a start in that direction.
1. New `FoldLogExpr` gadget.
2. Replacing folding logic in `UnionExec` as a proof of concept.
Yes
> feat: fold log gadget

- solidity/src/base/MathUtil.pre.sol
- solidity/test/base/MathUtil.t.pre.sol
This is needed to simplify #959 since Yul doesn't have any opcode that can do min and that we need it in #959 and potentially other places.
> feat: add `min` function to `MathUtil`

- solidity/src/proof_gadgets/FoldLogExpr.pre.sol
- solidity/test/proof_gadgets/FoldLog.t.pre.sol
> feat(sol): fold-log-gadget

- solidity/src/proof_gadgets/MembershipCheck.pre.sol
- solidity/test/proof_gadgets/MembershipCheck.t.pre.sol
> fix(sol): retrieve multiplicity from first round for membership

- crates/proof-of-sql/src/sql/proof_plans/sort_merge_join_exec.rs
> refactor: remove unnecessary usage of `apply_slice_to_indexes` in join

- solidity/src/verifier/Verifier.pre.sol
> fix(sol): read table chi evaluations as uint512s

- solidity/src/proof_gadgets/FilterBase.pre.sol
- solidity/src/proof_plans/FilterExec.pre.sol
- solidity/src/proof_plans/GroupByExec.pre.sol
- solidity/src/proof_plans/ProjectionExec.pre.sol
- solidity/src/proof_plans/ProofPlan.pre.sol
- solidity/src/proof_plans/SliceExec.pre.sol
- solidity/src/proof_plans/UnionExec.pre.sol
- solidity/src/verifier/Verifier.pre.sol
- solidity/test/proof_gadgets/FilterBase.t.pre.sol
> feat(sol): filter base

- solidity/src/proof_gadgets/FoldLogExpr.pre.sol
> refactor(sol): add `fold_log_evaluate_from_mles` to fold gadget

- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
- solidity/src/proof_plans/GroupByExec.pre.sol
- solidity/src/proof_plans/ProjectionExec.pre.sol
- solidity/src/proof_plans/ProofPlan.pre.sol
- solidity/src/proof_plans/SliceExec.pre.sol
- solidity/src/proof_plans/UnionExec.pre.sol
- solidity/src/verifier/Verifier.pre.sol
> refactor: use fold in group by

- solidity/src/proof_gadgets/FoldLogExpr.pre.sol
- solidity/test/proof_gadgets/FoldLog.t.pre.sol
> feat(sol): `fold_log_star_evaluate_from_expr_evals`

- crates/proof-of-sql/src/sql/proof_exprs/equals_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/multiply_expr.rs
- crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs
- crates/proof-of-sql/src/sql/proof_gadgets/fold_log_expr.rs
- crates/proof-of-sql/src/sql/proof_plans/group_by_exec.rs
This PR simply adds tracing around all the sections of code executed during the SumCount benchmark query. No code changes have occurred.
- Tracing is added in various functions
Yes
> bench: add tracing to all code sections executed in the SumCount benchmark query

- crates/proof-of-sql-benches/Cargo.toml
- crates/proof-of-sql/Cargo.toml
This is a follow up to a recent PR, https://github.com/spaceandtimefdn/sxt-proof-of-sql/pull/984. That PR needed to turn off the default features in the `nova-snark` crate in order to use WASM, but that introduced a performance regression in Nova specific code since that turned `halo2curves/asm` off. This PR adds the `halo2curves/asm`  feature flag back, but under the `cpu-perf` feature flag.
The following is an example of the `filter` benchmark query on the Multi-A100 system using a table size of `1,000,000`.
Currently in the `main` branch, without the `halo2curves/asm` feature flag, Nova specific code takes 531.23 ms to execute.
This PR, with the `halo2curves/asm` feature flag, Nova specific code takes 490.04 ms to execute.
- `halo2curves/asm` is added to the `cpu-pref` feature flag
- …
> feat: add the `halo2curves asm` feature to the `cpu-perf` feature flag

- crates/proof-of-sql/src/base/database/table_ref.rs
This is the last piece of `proof_of_sql` crate that is meaningfully dependent on the `proof_of_sql_parser` crate that needs to be retained after removal of the latter crate. Hence let's copy its implementation out.
Move serde impl of `TableRef` to `proof_of_sql` crate
> refactor: move serde impl of `TableRef` to `proof_of_sql` crate
